### ISSUE TITLE
Raid Invites

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#1]
So this hit me on the way to work. So in the EPGP/DKP window, if you could add an invite function, that'd kind of stream line the process as well. Additionally, maybe add in a check to see if they're online, or filter out offline people from the list. But I imagine it being something similar to adding points to all the people highlighted, just highlight people and invite them.

**Comment by Drutol** [comment]
Maybe just more options to the mass edit toolbar (select online players/invite to group) and display players not in group option? Or maybe some grouping mechanism where you assign certain players to group and then invite whole group?

**Comment by Aeotoc** [comment]
Assigning the players to a "group" and then inviting them will get too clunky I think because I have more raider than I do raid spots, so each week I'd be developing a new group or pruning the group or having like 10 different groups being different combinations of people. 

Increasing options to the mass edit toolbar wouldn't be a bad idea, as long as there is a check to make sure that person is online before I invite them, or if there isn't, it doesn't prompt the user with an error, just the normal system message that so-and-so isn't online.

**Comment by Drutol** [comment]
![](https://cloud.githubusercontent.com/assets/6102530/6319023/efbdcdcc-baad-11e4-96eb-e1bf33330aff.PNG)

You will be able to see all online players . Set their main/off spec role and group them by those roles . Then you are going to select who you want , press invite button and then this window will appear with summary.That's the plan.On those class/role icons numbers will be displayed.

**Comment by Aeotoc** [comment]
That's effing incredible

**Comment by Drutol** [comment]
This is meant to come in rev 130.

**Comment by Drutol** [comment]
Added in rev 130.
