### ISSUE TITLE
Auto Linking in Chat

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#101]
Any chance you could make it so that when i start the bid on an item for Network bidding it links the item in party chat so people can see the tooltip? i'm having random issues with members not being able to see the item tooltip

**Comment by Drutol** [comment]
It's already there , check network bidding settings.

**Comment by Drutol** [comment]
I may have forgotten to change the channel to /party though...

**Comment by Drutol** [comment]
I'm closing this then.
