### ISSUE TITLE
Leaving Beta.

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#105]
So , it's time to leave beta (yay!). We are pretty good feature-wise in my opinion to do this , here's the plan for the coming weeks:
:star: - for completed.
:star2: - in progress.
- Fix bugs with chat bidding that came with rev 141. :star:
- Add more filters to Loot Logs. :star: 
- Code and UI clean-up: :star:
  - Remove obsolete windows from xml files. :star:
  - Remove windows that are no longer needed (is there even a point to the Hub?). :star: 
  - Consolidate different settings and pieces into one window if necessary. :star: 
  - Create credits / thank you window. :star:
- QoL enhancements. :star:
  - Saving window positions , resizable windows ,slash commands etc... :star:
- Ensure stability , we don't want to encounter LUA errors or missing data. :star:
  - (AKA press every button you can find and see what happens). :star: 
- Documentation:
  - Delete current wiki. :star:
  - Write new wiki. (it's that simple xd) :star: 
  - Video showcase (?)
- Upload version 2.0 to curse. :star:
- Advertise on reddit/forums. :star:  
- Prepare for ninja API 10 changes that come with drop 5. :star2: 

I want to have this done before May - the month of my finals , I won't be available for 2-3 weeks that month. Any kind of help greatly appreciated!

**Comment by Hysteriana** [comment]
What about the Attendance and Raid Summaries ?

**Comment by Drutol** [comment]
Both will come after that , it's going to take a while to do them and I want to have something stable before May.

**Comment by Aeotoc** [comment]
Biggest thing I see here is the API 10 changes, which you should be able to do with the PTR. I mentioned a while back I'd help with the wiki, but it'd be a lot easier to start from scratch, so I like your idea of deleting it. I'm also better at talking than I am typing, so I'd almost rather just make a video, and then let you go from there? But... it's entirely up to you. It's your addon. I'll probably make a video regardless.

**Comment by Drutol** [comment]
All I can see on PTR is errors that some function wants integer instead of string + missing/changed assets. And only entry on PTR page is : 

```
ICComm Rewrite Work In User/Party
    ICComm now supports group and guild channels with better defined and more accessible limits for addon developers.
```

I just have to hope that they release documentation sometime in April and not day before drop 5 because I won't be able to fix this(probably?).

Video is greatly appreciated as I don't see myself talking about it ^^.Just wait till we're done with clean-up. I have 1 week of free time beginning this Wednesday and I'm planing to go through some of those things.

Most importantly I need reports of losing data / issues with Master Looter not showing stuff and some small things ("Oh , I wish it would be here but it's not a big issue so I won't bother him") that I'm unable to notice.

**Comment by Drutol** [comment]
If you want to make a video , you have green light from me , I'm not going to make drastic changes to UI any time soon.

**Comment by Drutol** [comment]
I'm done here :D.
