### ISSUE TITLE
Bug : r141 : Lua error on Start

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#107]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:234: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:234: in function 'BidCompleteInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:109: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:106>

**Comment by Drutol** [comment]
Fixed rev 141a
