### ISSUE TITLE
Bug : r141 : Being Data Provider causes freeze if someone is fetching.

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#108]
Everytime someone click the Fetch Button or auto fetch by timer, i get a total freeze for 1-2 sec
not sure if it matters, but fetcher is maybe still using previous version.

**Comment by Drutol** [comment]
Umm , and there's a problem. The more players/logs etc. is in db the bigger it gets , the bigger the database the closer we are to threshold (API limitatins), so I have to compress it . Compressing such big strings (the export ones) takes up quite big chunk of processing power. Sending those strings over time may be solution but it's not that easy to implement , right now you can setup a chain of data providers (idk how many of you are there) and I can add option to remove logs from those strings as they are the culprits.

**Comment by Hysteriana** [comment]
is r141 the first version with that compression ? cause there were no freezes with r140.
and what about the fetcher ? doesnt he need to decompress the datas ? cause there were no freezes on fetcher´s side.

**Comment by Drutol** [comment]
Nothing has changed in the code responsible for this... odd... Try with rev 140 again and report if the freezes are not an issue there.

**Comment by Hysteriana** [comment]
i will check it out.

what about this:
the Fetch button could get the complete database and the timed auto fetching only gets the session changes ? like a temporary database, similar to the undo log, while in raid ?

example:
everything that happens will get merged into my main database M as usual, but will be stored in temporary database T too. 
database T will be purged when i relog or reloadui. 
so it will be like a fresh installed clean database
if someone use the Fetch button, he will get database M, like for first time or if he missed some sessions.
this way my database M will replace his database M and we are in sync.
but the timed auto fetch will only get my database T, which is a small one since it contains no history.
and my database T will be merged with his database M and we will be in sync again.

maybe there could be a option to check for database sync on join raid or first fetch attempt.

**Comment by Hysteriana** [comment]
i tested down to rev 139a
got always the freeze on fetch, but the freeze with r141a seems 3x longer than with r139a

**Comment by Drutol** [comment]
Ok then , moar magic to the code needed :D. I have plan , update is coming ... on ... let's say ... Wednesday.

**Comment by Drutol** [comment]
... aand I'm done , now only differences will be sent. There're two drawbacks though , First fetch from each requester is likely to cause a freeze (even more power is needed on startup) and it's going to take quite a bit of space for comparsion sample. I'd like to test it on Wednesday :).

**Comment by Hysteriana** [comment]
nice to hear. let me know if you need me to be ingame for testing

**Comment by Drutol** [comment]
Fixed rev 142
