### ISSUE TITLE
Bug : r141 : Lua Error on Massedit

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#109]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:5141: attempt to compare two table values
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:5141: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:5140>
    [C]: in function 'sort'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:466: in function 'UndoAddActivity'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1942: in function 'MassEditModify'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1099: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1097>

**Comment by Aeotoc** [comment]
Got this error as well.

**Comment by Drutol** [comment]
Meh.. typo... update today.

**Comment by Drutol** [comment]
Fixed rev 142
