### ISSUE TITLE
Request : More Export Options

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#11]
Id like to Export the Member Detail History and Loot too

**Comment by Drutol** [comment]
I'm currently rewriting whole module that is tightly connected with this, you will have to wait a bit :(

**Comment by Drutol** [comment]
I'm going go to add now "Loot History" to the context menu , with this I can provide more export options. Is there any format you desire?

**Comment by Hysteriana** [comment]
not sure how complicated it is to export it to html.

maybe something like this ? http://epgp.gilde-vii.de/

with player details on demand by click on them ? but with collapsing / expanding maybe ?

**Comment by Drutol** [comment]
I'm not going to build whole website ^^(at least not in the near future). I'm just asking for the format of data so you can easily import it to your website :).

**Comment by Hysteriana** [comment]
simple table would suffice, what, who, how much.

**Comment by Drutol** [comment]
Added rev 136
