### ISSUE TITLE
Bug : r142 : Lua Error on (Sort by Name maybe ?)

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#111]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:364: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:364: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:351>

**Comment by Drutol** [comment]
Fixed rev 143
