### ISSUE TITLE
Bug : r142 : Lua Error on Start Chat Bid

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#112]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:898: attempt to get length of field 'tLastChatWinner' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:898: in function 'BidUpdateLastWinner'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:535: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:526>

**Comment by Mordonus** [comment]
Hmm it bugs the whole thing or just whines and moves forward?

**Comment by Hysteriana** [comment]
no timer and no message in party chat about start and stuff
but !bid and !off is collected and shown

**Comment by Drutol** [comment]
Yea , the troublesome part is just before messages and that's the reason. The rest went smoothly?

**Comment by Hysteriana** [comment]
well since no message when start, when end and who one, there was not much to test

**Comment by Drutol** [comment]
Hmm , you are now selecting the winner. Just click on entry in the grid. We'll check this on the hill today.

**Comment by Drutol** [comment]
Fixed rev 143

**Comment by Hysteriana** [comment]
im ingame now
