### ISSUE TITLE
SS request.

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#117]
I need screenshots of Network Bidding and ML window in action for new wiki. The ones with only one entry don't depict stuff well. (Yup , wiki is now deleted) So take some screenshots during raid if you can :).

:star: - I got it!

List of stuff I need:
- Network Bidding screenshots.
- ML window screenshots.
- Alts indicator live screenshot.
- Full representative DB in .xml file :star: 
  - \AppData\Roaming\NCSOFT\WildStar\AddonSaveData\EasyDKP_0_Gen.xml
- If you have or happen to have some screenshots that shows things nicely they are greatly appreciated.
- Mass invites screenshots.

Thanks!

**Comment by Hysteriana** [comment]
here ya go: http://pastebin.com/w1EuJf8e

**Comment by Drutol** [comment]
Thanks :) , can anybody confirm that mass invites are working?
