### ISSUE TITLE
Bug : RC1 : Lua Error on Random Assign

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#120]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2033: attempt to index field '?' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2033: in function 'Bid2CloseOnAssign'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1311: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>
    [C]: in function 'PostOnChannel'
    ui\ChatLog\ChatLog.lua:1944: in function <ui\ChatLog\ChatLog.lua:1943>
    [C]: in function 'Event_FireGenericEvent'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2121: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2118>
    (tail call): ?

**Comment by Hysteriana** [comment]
also on direct assign (token in this case)

**Comment by Drutol** [comment]
Fixed rev 145.

**Comment by Hysteriana** [comment]
how come this error comes with the older versions too ?
be back to 139a and still got that error

**Comment by Drutol** [comment]
This is caused by Network Bidding's close on assign option. Maybe you have had it disabled?

**Comment by Hysteriana** [comment]
Pretty sure I did

gesendet vom Handy
Am 08.04.2015 03:10 schrieb "Mordonus" notifications@github.com:
