### ISSUE TITLE
Request: ML Popup Item lvl/quality filter ability

### ISSUE THREAD

**Issue by xeroiv** [Mordonus/RaidOps#121]
Is there currently a way for the stop the popup for items lower item level or filter by item quality?  IE I am looking for a way to only have the popup appear for orange quality items (ilvl 68 for GA).

**Comment by Drutol** [comment]
Right now there's no option for that but there will be one in next update.

**Comment by xeroiv** [comment]
Thanks as always for the good support!

**Comment by Drutol** [comment]
Added rev 145
