### ISSUE TITLE
Bug-ish : RC1 : First time fetcher dont get any data displayed

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#122]
guild / raid buddy fresh installed easy dkp for the first time, so clean database and stuff.
he fetched data from me, 2 times
he also got the chat message that data has been received and processed but still dont get any data displayed on screen, only the default stuff from guild import.

**Comment by Hysteriana** [comment]
when i changed my data after his initial fetch, and he then fetched again, then the data showed up for him.

**Comment by Drutol** [comment]
Hmm , I thought I have fixed it. We will have to check this again.

**Comment by Drutol** [comment]
Turned out to be working.
