### ISSUE TITLE
Bug : RC1 : Lua Error on Start and while fight against Convergence Fight in GA

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#123]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

**Comment by Drutol** [comment]
Fixed rev 145
