### ISSUE TITLE
Bug: RC1 : Recent Activity - Auto assign EP keeps  Comment from manuel edit

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#124]
see picture:

![comment](https://cloud.githubusercontent.com/assets/11199863/7053182/7c244f90-de33-11e4-9fbe-cce1dba95e7c.png)

**Comment by Drutol** [comment]
Oww , I forgot that I'm passing there already formated string and as a result I'm comparing this formated string with the default string -.-.

**Comment by Drutol** [comment]
Fixed rev 146
