### ISSUE TITLE
Bug : RC1 : Lua Error on Start and while fight against Ohmna Fight in GA

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#125]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: attempt to concatenate global 'strTextTrade' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1390: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1263>

**Comment by Drutol** [comment]
Yes , this is the same as it was during convergence fight. Fixed in rev 145 which is now on Curse.
