### ISSUE TITLE
Request : r145 : Chatbidding sort Participant List 

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#126]
it would be helpfull if the list would be sort !bid > !off first and then by PR.

so all who use !bid will be at the top of the list, sort by their PR, followed by all who used !off, also sort by their PR too.

**Comment by Drutol** [comment]
How about two lists , one for main specs and one for off specs?

**Comment by Hysteriana** [comment]
yeah sure that would work too

**Comment by Drutol** [comment]
Added/Changed/Fixed rev 146
