### ISSUE TITLE
Bug : r145 : Lua Error Chatbid

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#127]
selected one, clicked assign button twice: 

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:821: attempt to index field 'Bidders' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:821: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:801>

**Comment by Drutol** [comment]
Fixed rev 146
