### ISSUE TITLE
Bug : r145 : Chatbid - Assign / Select

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#128]
Buttons doesnt seem to do anything
i started the bidding, selected the winner, clicked on stop
then i clicked on assign, but nothing happened, winner didnt get the items
tried select, winner didnt get selected at masterloot window.

**Comment by Drutol** [comment]
What the heck . On the hill everything was working perfectly... Prepare for next session ^^

**Comment by Drutol** [comment]
Ah , you can assign/select only during bidding ,  what was I thinking?

**Comment by Hysteriana** [comment]
maybe.. "why easy if I can do it complicated" ?
😁

**Comment by Drutol** [comment]
Fixed rev 146. Let me know when you are in-game,
