### ISSUE TITLE
Bug : Lootmaster Window PopUp

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#13]
the "Enable Pop-Up" option does not work. 
that option only stop the little assign ep gp window from popping up when loot has been assigned.. 
but not that fat masterloot window where all the loot is shown and that pops up everytime some epic drops

**Comment by Drutol** [comment]
This is something I have nothing to do whatsoever. It's just how the default addon works , there's an addon on curse that does the hiding.

**Comment by Hysteriana** [comment]
but isnt it your lootmaster addon that comes with the easy ep/gp addon ?
doesnt it replace the default lootmaster ?

**Comment by Drutol** [comment]
Nope , it works with default one.
It overrides quite a few methods but it still the default addon.
