### ISSUE TITLE
Error when mass selecting 

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#131]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:2216: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:2216: in function 'UpdateItem'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:2082: in function 'RefreshMainItemList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1799: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:1795>

**Comment by Drutol** [comment]
I have already fixed this is in rev 146. Try disabling color icons for now ;d. Update today.
