### ISSUE TITLE
Bug : r145 : set alts apear again on data fetch

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#132]
i have set some chars as alts to other chars, to make them disappear from the list.
guild mate had imported guild members, then full fetched from me to get the data.
he did the epgp stuff for one day. then when i fetched from him,  i still got the alts set to the main chars, 
but also the alts it self in my list again.

**Comment by Drutol** [comment]
Hmm so ... while processing fetched data I need to check alt tables with main roster. Noted

**Comment by Drutol** [comment]
Fixed rev 146
