### ISSUE TITLE
ML SS

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#133]
![1](https://cloud.githubusercontent.com/assets/11199863/7148129/a314e73c-e300-11e4-8d41-ff62ff117ebf.png)
![2](https://cloud.githubusercontent.com/assets/11199863/7148128/a314e1ba-e300-11e4-832d-103061f1059b.png)
![3](https://cloud.githubusercontent.com/assets/11199863/7148132/a315affa-e300-11e4-9cdc-56812e70e887.png)
![4](https://cloud.githubusercontent.com/assets/11199863/7148130/a3157918-e300-11e4-81e1-9ae1eb38ef83.png)
![5](https://cloud.githubusercontent.com/assets/11199863/7148133/a31609a0-e300-11e4-883e-51eb7c5b4759.png)
![6](https://cloud.githubusercontent.com/assets/11199863/7148131/a315c616-e300-11e4-9217-e5f2b7bfddae.png)
![7](https://cloud.githubusercontent.com/assets/11199863/7148135/a3291a54-e300-11e4-9a95-f9bf1f6742fa.png)

**Comment by Drutol** [comment]
Thanks ! Not seeing a wall of issues makes me guess that RC2 "works"?

**Comment by Hysteriana** [comment]
guild mate had some serious problems with latest version and also some lua error, but i dont know what. giving him my *.xml fixed it.
did you implement the shorten chat bidding text or did i just miss the settings for it ?
