### ISSUE TITLE
Bug-ish : r147 : assigned item doesnt show in personal log and didnt cause popup window

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#134]
no problems so far at my end.
did you implement the shorten chat bidding text or did i just miss the settings for it ?

but one item i assigned for offspec didnt trigger the epgp popup. 
it was a ilvl 74 breast.  
the item does also not show in his personal log, although it shows up at the loot log with his name.
i will keep an eye on it.

guild mate had some serious problems with latest version and also some lua error, but i dont know what. giving him my *.xml fixed it.

**Comment by Drutol** [comment]
Short bidding strings are implemented. Check chat bidding settings.( next to whisper responses checkbox). If item appears in Loot Logs then it passed filters so something went wrong during recipients identification , umlauts maybe? 

I'll be checking everything once more before release so maybe I'll find something.
