### ISSUE TITLE
Bug : v2.0 : EP GP add sub set greyed out while in massedit

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#135]
as soon as i enter the massedit mode, the buttons become grey.
only works in single edit mode

![1](https://cloud.githubusercontent.com/assets/11199863/7166127/386759f4-e3ac-11e4-89f2-c17bac4b414d.png)
![2](https://cloud.githubusercontent.com/assets/11199863/7166130/3aff47c6-e3ac-11e4-9077-2ada46f78422.png)

**Comment by Hysteriana** [comment]
clean install fixed it

**Comment by Drutol** [comment]
Still odd, I'll investigate.

**Comment by Drutol** [comment]
Turns out to be typo... fixed v2.01
