### ISSUE TITLE
Bug: v2.0 : Recent Activity Number Sort

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#136]
Recent Activity Sort by Numbers

![4](https://cloud.githubusercontent.com/assets/11199863/7166957/a1107102-e3b1-11e4-81c9-24058027ba1f.png)

**Comment by Drutol** [comment]
I have no clue how it's sorted , it's a stock functionality that I cannot change.

**Comment by Drutol** [comment]
It sorts alphabetically , I'll research whether I can change it somehow.
