### ISSUE TITLE
Request : v2.01 : Third option for Chatbit like !style or so

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#138]
see title, a third option would be nice, like with netbidding, like !bid !off !style or so

**Comment by Drutol** [comment]
will be a thing... this weekend maybe? who knows! ^^

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/7208866/fdd74634-e543-11e4-84d1-696ae54fcaf4.png)

This is current prototype...

**Comment by Hysteriana** [comment]
nice

**Comment by Drutol** [comment]
Added version 2.02
