### ISSUE TITLE
Request : v2.01 : Chatbid : Offspec winner will also select offspec option at popup

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#139]
see title.
if someone from the mainspec window is the winner, the popup could auto assign it for mainspec
if someone from the offspec window is the winner, the popup could auto assing it for offspec,
if someone from the 3rd option window is the winner, the popup could auto assign for offspec or guildbank

maybe dont even need the popup if winner is selected by a bidding ?

**Comment by Drutol** [comment]
With 2.03 or 2.04 pop-up window will get some brain.
