### ISSUE TITLE
Bug : Auto EP/GP Event Log

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#14]
Event Overviews Log shows Dreadphage Ohmna on all auto Events

**Comment by Drutol** [comment]
Not an issue for me... can you post ss?

**Comment by Hysteriana** [comment]
there you go.

![unbenannt](https://cloud.githubusercontent.com/assets/11199863/6414801/a13215aa-be9a-11e4-9803-f1ba443e0ef9.png)

**Comment by Drutol** [comment]
Fixed in rev 130.
