### ISSUE TITLE
The month of May

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#140]
With my next sub expiration I'm taking a break (beggining of May). Why you ask. Well , May is the month of my final exams and priorities and stuff ^^. My last exam takes place on 22th of May and this is the estimated break end. Having 2 more weeks now , post the most naggling issues (aka. anything :D)  so you can happily use the addons throughout my absence.

As far as API 10 is concerned , code is rewritten waiting to be tested next week probably. If something crucial breaks with drop 5 release I'll fix this. That said , I'm checking forums/curse/github daily so feel free to ask , request , report.

**Comment by Aeotoc** [comment]
Will you be coming back after May? I would still love it if you developed some kind of website for the purpose of posting logs/points/loot. It was brought up before, and you said it'd be down the road before you got to such a thing, but the API does support such an exchange of information as WildStar Logs does something similar, but with combat data. 

Also, I was wondering if you were still considering overhauling/reworking the Raid Summary module. I, for one, would like this to be a one-stop shop information display for attendance, time in raid, loot, point gains, and etc. I also think this information would synergize well with a website for information hosting.

**Comment by Drutol** [comment]
Yes I'm definitely back with 4 months of free time ^^. This is going to be huge thing to do , especially considering me not having any experience with websites aside from simple html stuff. Not to mention data collection in-game . Even if , Idk whether there's enough users to make it worthwhile. If there's demand why not to try.

I believe that W\* logs has separate program to upload data from clipboard to it's website. API does not allow for communication stuff because 'security'.

**Comment by Drutol** [comment]
(Having said that... I wanted to get into websites for quite some time sooo I'm going to learn this)

**Comment by Aeotoc** [comment]
You're absolutely correct in that regard. It requires a second program. Idk if this is asking too much for you to make something like that, but I also think it could be possible to reverse engineer the WSLogs program to do this for you. Regardless, I'd be happy to support you in this endeavor, and I think having a website upload ability will also increase the usage of the addon. I've talked to several Raid Leads and their hesitancy to use any kind of dkp addon stems mainly from losing the data. If there were a website that operated on a server that they didn't ahev to worry about, they'd all use it.

**Comment by Drutol** [comment]
Let's start off with simple stats display and see where it takes me.

Creating such a program cannot be that hard , I'd say that the challenge here is the website itself.
Also keep in mind that I'm here alone with pretty big project (12k lines of code) so it will take time.
