### ISSUE TITLE
Database Reset

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#141]
With one of the new updates since Thursday, my DB has been reset.

**Comment by Aeotoc** [comment]
Addendum: Everything reset. It's as if I fresh installed.

**Comment by Drutol** [comment]
With 2.0 I've changed addon's name , therefore the game searches for save file for current name not the old.

> Addon name has been changed and you need to copy the contents of EasyDKP_0_Gen.xml to RaidOps_0_Gen.xml . Both files can be found in %appdata%\NCSOFT\WildStar\AddonSaveData .

If that's not the case , we have a problem....

**Comment by Aeotoc** [comment]
yeah, I checked the changelog last night to see if something happened, and I found your instructions!

**Comment by Drutol** [comment]
Uff , you scared me :D
