### ISSUE TITLE
Bug : v2.01 : Lua Error : on stop chatbidding

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#143]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:822: attempt to index global 'bidder' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:822: in function 'BidUpdateBiddersList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:679: in function 'BidProcessMessageEPGP'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:631: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:618>

**Comment by Drutol** [comment]
Typo - fixed v2.03
