### ISSUE TITLE
Bug: v2.02 : Lua Error on non existant player

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#144]
i manual added a player, but wrote his name wrong,
he was added to raid by queue, thats why i could select him to assign loot
when i did, i got lua error

**Comment by Drutol** [comment]
Oh now I get it , chat bidding assign to be clear?

**Comment by Hysteriana** [comment]
in think i assigned by ML, used chatbidding only for testing

**Comment by Drutol** [comment]
He couldn't have appeared with wrong name in ML window , two different data sources.
