### ISSUE TITLE
Bug: v2.02 : Lua Error after reloadui

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#146]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1507: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1507: in function 'Bid2GetTargetsTable'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1596: in function 'Bid2BroadcastMySuperiority'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1062: in function 'InitBid2'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:156: in function 'BidCompleteInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:134: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:131>

**Comment by Drutol** [comment]
Fixed v 2.03
