### ISSUE TITLE
Bug : v2.02 : Epgp Popup didnt trigger by chest item

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#148]
its the 2nd time now, that a chest item didnt trigger the popup window, but it triggered by another raid member
its the  Ordinal Alloy Vest

**Comment by Hysteriana** [comment]
same with Treads of Passage

**Comment by Hysteriana** [comment]
i had again a chest that didnt triggerd the popup. but there were a masterloot chat message.
buddy had a mission popup with a token, that hat worked for me.
i guess there could be a problem with the (whitelist) filter.. i will investigate further..

**Comment by Drutol** [comment]
the question is : does this item appear in loot logs?

**Comment by Hysteriana** [comment]
sometimes yes, sometimes not.. atm it appears to be total random.. didnt find out any pattern yet.

**Comment by Drutol** [comment]
umm , and how about skip random assign and skip bid winner?

**Comment by Hysteriana** [comment]
skip random is enabled, but it happened when i assigned directly by select recipient first
skip bid winner is disabled
