### ISSUE TITLE
Bug : Master Loot Item Assign Lua Error

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#15]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2351: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2351: in function 'BidAddNewAuction'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:556: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:555>

happens random, last when i tried to assign support item to stalker.
clicked ignore error, tried to assign again and it worked.
was also the last item to assign.

**Comment by Drutol** [comment]
Fixed in rev 130.
