### ISSUE TITLE
Bug : v2.03 : Lua Error : Lootlog

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#150]
when click on the + inside lootlog:

...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:170: bad argument #1 to 'ipairs' (table expected, got nil)
stack trace:
    [C]: in function 'ipairs'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:170: in function 'IBPopulate'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:85: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:84>

**Comment by Hysteriana** [comment]
but only if you open lootlog by player right click menu
if you open the lootlog for whole roster its fine,

**Comment by Drutol** [comment]
Fixed v2.04
