### ISSUE TITLE
Bug: v2.03 : Lua Error - Random Loot Assign

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#154]
i guess i clicked on random without any item selected

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:402: bad argument #1 to 'random' (interval is empty)
stack trace:
    [C]: in function 'random'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:402: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:390>

**Comment by Drutol** [comment]
Fixed v2.04
