### ISSUE TITLE
Bug-ish: v2.03 : Chatbid recipient out of range

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#155]
in chatbid window, you cant see if ppl are out of range, like with the ML window.
when i click assign in chatbid window, and recipent is not in range, i get message, item no longer exist.
if i try again when in range, he gets the item, but no epgp popup.

**Comment by Drutol** [comment]
Maybe you have checked to ignore ppl if they won by chat bidding?

**Comment by Hysteriana** [comment]
nope, its not checked, since i still want to see of they get the gp values.
