### ISSUE TITLE
Bug : v2.04 : Loot Log Date sort

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#158]
when using EU Date Format, same dates are odd:

![na](https://cloud.githubusercontent.com/assets/11199863/7318788/dac505d6-ea8f-11e4-9822-a6c59360abec.png)
![eu](https://cloud.githubusercontent.com/assets/11199863/7318790/dcd9055c-ea8f-11e4-9cce-c1a574f57db7.png)

maybe the eu format needs to be dd/mm/yyyy and not just dd/m/yyyy
like 20/04/2015 and not just 20/4/2015

**Comment by Drutol** [comment]
fixed v2.05
