### ISSUE TITLE
Request : Undo Option / Restore removed player with epgp

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#16]
Accidentally removed some selected Member. Clicked Undo Last Action.
Member have been restored but without EP/GP and Logs

**Comment by Drutol** [comment]
Hmm it restores removed players with all their things...

**Comment by Hysteriana** [comment]
just tried with only 2 selected, and it worked.

last time i had the whole raid selected, 19 ppl, clicked on remove, but only 6 or so had been removed.
when i clicked restored, those 6 where restored blank just with default start ep/gp.

will test it again as soon as the export / import is working :)

**Comment by Drutol** [comment]
Oh okay , now I may know where the issue is.

**Comment by Drutol** [comment]
Fixed in rev 130.
