### ISSUE TITLE
Bug : 2.03 : Chat bid assign doesnt trigger popup window when randiom assigned stuff between

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#160]
i start the chat bid.. while im waiting for the ppl to bid, i use the waiting time to random assign stuff like signs, when i stop the chatbidding and then click assign at the chat bidding window, the winner will get the item (if hes in range) but it wont trigger the popup window, even with the masterloot chat notice.

**Comment by Drutol** [comment]
Soo, this looter won both chat bidding and something at random? If so , fixed v2.05

**Comment by Hysteriana** [comment]
i dont think it does matter who won the random stuff..

**Comment by Drutol** [comment]
If you have skip random enabled , the name of random winner is saved but never removed. Therefore he will be skipped on every pop up.

**Comment by Hysteriana** [comment]
so still fixed or just stop random while Chatbid?

**Comment by Drutol** [comment]
Should be fixed now
