### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#161]
Soooo , thanks to @Aeotoc i have been learning how to build simple website. Built in ruby on rails now provides basic functionality , there's no ETA when this will be hosted somewhere because I don't know what am I doing :D.(typing random stuff seems to work)

This is meant to be an update issue as I'll be adding stuff.

The question is , are you even interested in such a thing... or you'd rather me working more on addon.

Source hosted [here](https://github.com/Mordonus/RaidOpsWeb).

![image](https://cloud.githubusercontent.com/assets/6102530/7338293/c68fad64-ec47-11e4-9fe0-bf5d8d85f506.png)
![image](https://cloud.githubusercontent.com/assets/6102530/7338302/2388b3bc-ec48-11e4-80eb-db7698eb9c80.png)

**Comment by Drutol** [comment]
I'd be grateful for your database's dump. All you have to do is to type /dbgf and paste the result (http://pastebin.com/). Thanks!

**Comment by Hysteriana** [comment]
i like it, especially the "epic music mix" :D 
http://pastebin.com/wpp7mV2p

**Comment by Drutol** [comment]
http://youtu.be/DhXA-9T_FNM this is the one ^^. I have had marathon yesterday with the website and it's taking shape , writing logic is fun , designing layout in CSS is painful... If somebody knows how to make websites look nice I'll be grateful for guidance  :D

**Comment by Drutol** [comment]
Moar screenshots:

![image](https://cloud.githubusercontent.com/assets/6102530/7363461/d96a866e-ed7a-11e4-87d5-61c9affc5472.png)
![image](https://cloud.githubusercontent.com/assets/6102530/7363470/ff609f98-ed7a-11e4-9fb8-422b570e054f.png)
![image](https://cloud.githubusercontent.com/assets/6102530/7363472/1905700e-ed7b-11e4-9156-a0beb2e1e882.png)

**Comment by Hysteriana** [comment]
dont forget the lua errors about this ;)

**Comment by Drutol** [comment]
Ok , **early** version is up https://raid-ops-web.herokuapp.com/guilds . It's free hosting so give it a few seconds to wake up. I'm probably going to wipe db a few more times so treat this as a sneak peak :).

The main issue is that the item tooltips from Jabbithole don't want to appear in the live version...
Also , the export string you are getting from /dbgf may be incomplete because it's too long to display.

In order to create guild you need to set up an account.
The activation part is sketchy for now:

> Welcome to example.com, dogier140@gmail.com =============================================== You have successfully signed up to example.com, your username is: dogier140@gmail.com. To login to the site, just follow this link: http://0.0.0.0:3000/users/sGvTTTBhVDUBAJGZnqzG/activate . Thanks for joining and have a great day! 

This it the message that will be sent to you more or less. The link should look like this:

> https://raid-ops-web.herokuapp.com/users/sGvTTTBhVDUBAJGZnqzG/activate

Modify and paste this to your browswer and you're good to go.

Now , back to addon we go...

**Comment by Drutol** [comment]
The issue with item tooltips , is on the Jabbithole's side . Waiting for fix from them.

**Comment by Drutol** [comment]
Aaaand it works. http://raid-ops-web.herokuapp.com/guilds/3/items_all

**Comment by Aeotoc** [comment]
how do we upload data?

**Comment by Drutol** [comment]
Log in , go to your guild , on the left there's menu wtih stuff. Click Upload data , paste this string you obtained from addon and press the button. Give it a bit of time to procces and it should be there.

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/7397685/71c83818-eeaa-11e4-9d39-6a37a81142ec.png)
![image](https://cloud.githubusercontent.com/assets/6102530/7397725/a41b9ab2-eeaa-11e4-8cd4-d5b62a00b218.png)

**Comment by Aeotoc** [comment]
this is from the RaidOps epgp addon right?

**Comment by Drutol** [comment]
Yes , with v2.06 there's new export option.

**Comment by Aeotoc** [comment]
Got this error 
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3583: bad argument #1 to 'ipairs' (table expected, got nil)
stack trace:
    [C]: in function 'ipairs'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3583: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3500>

**Comment by Drutol** [comment]
Now that's strange , can you send me you database .xml file?

**Comment by Aeotoc** [comment]
RaidsOps_0_Gen ?

**Comment by Drutol** [comment]
w8

**Comment by Drutol** [comment]
http://pastebin.com/qFSGMUP2 replace your DKP.lua file with this paste

**Comment by Aeotoc** [comment]
that seemed to have worked! thanks

**Comment by Aeotoc** [comment]
item names are shown as numbers. Is that the issue you were talking about earlier with jabbit?

**Comment by Drutol** [comment]
if you want names you have to swittch from https to http just remove "s" from url

**Comment by Drutol** [comment]
I'm waiting for a fix from jabbithole

**Comment by Drutol** [comment]
In terms of space , approx 20 guilds will fit for now , and 20 users can be on this website at the same time.

**Comment by Aeotoc** [comment]
so when I try to search through the classes, since they're all symbols, it's not letting me display only stalkers, when I type that in the text box

**Comment by Drutol** [comment]
something has broke when I transitioned from development to "production" . two different modes with different rulesets , investigating

**Comment by Drutol** [comment]
It turns out that I'll have to tweak db to fix this , something to do tommorow :D. But what's your general impression , is it worth to go further or just ditch the whole thing?

**Comment by Drutol** [comment]
I had to clear db , I don't foresee more wipes for now.

**Comment by Drutol** [comment]
You can now download imported data

**Comment by Aeotoc** [comment]
You know I'm all for the idea :D

**Comment by Drutol** [comment]
So which essential features are missing (aka what you want to have there), bearing in mind we have currently what we have from export. Layout and design is different cup of tea ;d Searching is now functional.

**Comment by Drutol** [comment]
Next update is up.

**Comment by Hysteriana** [comment]
website cant tell if items went for free ?

edit: time stamp / sort is a bit off

![time](https://cloud.githubusercontent.com/assets/11199863/7417961/3da869ca-ef6a-11e4-8ba8-30109005f5ef.png)

**Comment by Drutol** [comment]
Currently this data is exported as such string , I'll modify this to contain the actual number , if item was assigned for free then it should be there.

**Comment by Drutol** [comment]
- any more details about items are currently unvailable because free hosting.

![image](https://cloud.githubusercontent.com/assets/6102530/7418860/693723e0-ef71-11e4-8c6a-5d6b10bf7c23.png)

When it hits 10000 we're doomed :D

**Comment by Mordonus** [comment]
I was thinking about giving every user ability to upload items they are currently wearing , something like small armory. Good idea , or just obsolete feature?

**Comment by Drutol** [comment]
Next update is live. Now I need to build "home page" somehow...

**Comment by Hysteriana** [comment]
why a "home page" ? wouldnt it be better to make it modular so guilds could integrate it into their guild pages ? i mean most ppl have their own guild page hosted somewhere, if they could install your database page on their own webserver, you wont need to host it anymore and they could just link it intern.

**Comment by Drutol** [comment]
And god knows how to do this. By homepage I mean " welcome! Have a great day!". I have posted on reddit to get the idea what ppl want

**Comment by Drutol** [comment]
Update with "landing page" uploaded.

**Comment by Drutol** [comment]
Yet another update live.

**Comment by Drutol** [comment]
Fix for https issues + recent activity page has been added.You may need to reupload your data to take advantage of that.
