### ISSUE TITLE
Someone fetched from me while running the main addon, and it gave me this error.

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#162]
Lua event handler has exceeded 2501 ms.
stack trace:
    ...aming\NCSOFT\WildStar\Addons\RaidOps\libs/Base64.lua:39: in function 'Encode'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5871: in function 'GetEncodedData'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5784: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5781>

Also, caused a pretty large lag spike

**Comment by Drutol** [comment]
It was reoccuring or single case?

**Comment by Aeotoc** [comment]
Yeah, here it is again.

Lua event handler has exceeded 2501 ms.
stack trace:
    ...aming\NCSOFT\WildStar\Addons\RaidOps\libs/Base64.lua:38: in function 'Encode'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6012: in function 'GetEncodedData'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5928: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5922>

**Comment by Aeotoc** [comment]
that's what I get when he clicks the X or the fetch button

**Comment by Drutol** [comment]
With api 10 I have ditched this encoding , so this should do the trick. It may be caused by the length of the string that is sent.
