### ISSUE TITLE
Bug : v2.05 : Lua Error : Link Items from Roster LootLog Group by Day

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#163]
...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:114: attempt to index local 'wndBubble' (a nil value)
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:114: in function 'IBPopulate'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:199: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:198>

**Comment by Drutol** [comment]
Fixed v2.06
