### ISSUE TITLE
Bug-ish : v2.05 : Loot Log : Group by Day shows wrong recipients

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#164]
the items in the by day bubble show more player than the actual recipient.
maybe ppl who won it in the past ?

**Comment by Drutol** [comment]
Can you send me db(.xml) with this bug? I cannot reproduce this myself.

**Comment by Hysteriana** [comment]
hmm pastebin wont let me, the .xml is bigger than 512 kb now...

there you go: http://www.xup.in/dl,10155163/RaidOps_0_Gen.xml/

**Comment by Hysteriana** [comment]
as you can see:
group by day, selected the 28.04, it was Sir Bumsky who got that chest, but 2 more are listed.

![loot](https://cloud.githubusercontent.com/assets/11199863/7389597/d1b28e58-ee6f-11e4-91e5-0ba4d81192cc.png)

**Comment by Drutol** [comment]
Yeah , that was the case. 
![image](https://cloud.githubusercontent.com/assets/6102530/7391693/37e5ae4a-ee83-11e4-8c69-2ed47d503420.png)

**Comment by Drutol** [comment]
Fixed v2.06 , damn it really stutters with that much data floating around.

**Comment by Hysteriana** [comment]
its kinda useless then to sort by day if it shows data from the past :D 
maybe it needs to get limited to a week or month max
