### ISSUE TITLE
PTR testing

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#167]
do you need help today for ptr testing ?
let me know

**Comment by Drutol** [comment]
yup , how about now?

**Comment by Hysteriana** [comment]
ööhmmmmmm.. :/ just updating the ptr client... again... :D 
i will let you know asap when its ready

**Comment by Hysteriana** [comment]
i guess in around 20 min..

**Comment by Drutol** [comment]
https://dl.dropboxusercontent.com/u/50108505/addons.rar

**Comment by Drutol** [comment]
It will go either smoothly or .... . I bet for the 2nd option :D

**Comment by Drutol** [comment]
I have to admit that Drop 5 works much more smoothly :)

**Comment by Drutol** [comment]
I have to go , we will do this tomorrow.

**Comment by Hysteriana** [comment]
ok, write me if you are up for it

**Comment by Hysteriana** [comment]
im online now for a while

**Comment by Drutol** [comment]
https://www.dropbox.com/s/ya8xx4605ii1wqk/addons.rar?dl=0

**Comment by Hysteriana** [comment]
let the bugfixing beging :D 

...g\NCSOFT\WildStarPTR\Addons\RaidOps\libs/Serpent.lua:133: attempt to call a nil value
stack trace:
    ...g\NCSOFT\WildStarPTR\Addons\RaidOps\libs/Serpent.lua:133: in function 'load'
    ...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:1172: in function <...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:1170>

**Comment by Drutol** [comment]
https://www.dropbox.com/s/ya8xx4605ii1wqk/addons.rar?dl=0

**Comment by Drutol** [comment]
http://pastebin.com/ws8P6V8T

**Comment by Hysteriana** [comment]
...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:1180: attempt to call method 'BidRegisterCheckResponse' (a nil value)
stack trace:
    ...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:1180: in function <...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:1173>

**Comment by Hysteriana** [comment]
...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:1972: attempt to index field '?' (a nil value)
stack trace:
    ...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:1972: in function <...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:1970>

**Comment by Hysteriana** [comment]
...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:1206: table index is nil
stack trace:
    ...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:1206: in function <...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:1173>

**Comment by Hysteriana** [comment]
![hysteriana_doomstar 150501 170445](https://cloud.githubusercontent.com/assets/11199863/7431941/ca4d1902-f023-11e4-955a-aaf1d344b69c.png)

**Comment by Hysteriana** [comment]
![hysteriana_doomstar 150501 170846](https://cloud.githubusercontent.com/assets/11199863/7431999/51143718-f024-11e4-8d84-8353701c4e0b.png)
![hysteriana_doomstar 150501 170851](https://cloud.githubusercontent.com/assets/11199863/7432001/511788fa-f024-11e4-9f2b-9d344f1365ae.png)
![hysteriana_doomstar 150501 170854](https://cloud.githubusercontent.com/assets/11199863/7432000/51168eb4-f024-11e4-8791-b69cbfd15241.png)

**Comment by Drutol** [comment]
http://pastebin.com/GGBfSctZ

**Comment by Hysteriana** [comment]
![hysteriana_doomstar 150501 174118](https://cloud.githubusercontent.com/assets/11199863/7432500/ecd9a314-f028-11e4-80d1-b137f547ecde.png)

**Comment by Hysteriana** [comment]
...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\DKP.lua:5944: bad argument #1 to 'SendPrivateMessage' (string expected, got nil)
stack trace:
    [C]: in function 'SendPrivateMessage'
    ...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\DKP.lua:5944: in function <...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\DKP.lua:5940>

**Comment by Drutol** [comment]
http://pastebin.com/VaddZzY7

**Comment by Hysteriana** [comment]
...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:443: attempt to call method 'EPGPInit' (a nil value)
stack trace:
    ...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:443: in function <...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:280>
