### ISSUE TITLE
Bug-ish : v2.06a : Loot Log Minimum GP cost

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#168]
am i right, that this filter only looks at what am item would cost, depending on the EPGP settings ?
and not what it actually did cost ?

imho it would be much better to filter the actual costs.

im asking, cause we give random and offspec items for free, aka 0 gp.
setting the filter to at least 1 GP would filter all random and offspec stuff, and only show items that have been paid for.

**Comment by Drutol** [comment]
When you assign for free via pop-up gp value should be changed appropriately.

**Comment by Hysteriana** [comment]
then it is buggy...
28.04.15 i assigned some items random for free with skipped popup option, 
some other items i assigned offspec for free (0 gp) with popup option.

but they are still listed at the loot log, even if i set the min gp value to >0, in this case to 1000.
for example that chest item: 
as you can see it is listed for 0 GP at Spider Parker´s log, its also listed as his last item in the main window. 
in my understanding it should not be shown in the loot log if i set the min gp cost value > 0 .

![loot](https://cloud.githubusercontent.com/assets/11199863/7430018/c5bc2854-f00c-11e4-9acb-b43b6d372acf.png)

**Comment by Drutol** [comment]
It's because the update with that rolled in on 29.04 . Previous entries are not affected.

**Comment by Hysteriana** [comment]
ah ok, i kinda suspected that :D
