### ISSUE TITLE
Bug : v2.08 : Lua Error on start

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#172]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1158: attempt to index field 'channel' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1158: in function 'BidJoinChannel'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1093: in function 'InitBid2'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:163: in function 'BidCompleteInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:136: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:133>

**Comment by Drutol** [comment]
Oww it crashes because the length of your channel is shorter than 5 characters , I'll upload fix later today. For now you can just change it to "gviiiiiiii" for example :D

**Comment by Hysteriana** [comment]
-.- never play on patchday :D

**Comment by Drutol** [comment]
API 10 is love ... API 10 is life

**Comment by Drutol** [comment]
Lol I cannot even log in...  client crashes every time. Going in blind.

**Comment by Drutol** [comment]
Fixed v2.08b
