### ISSUE TITLE
Error when distributing DS loot

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#173]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1235: table index is nil
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1235: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1181>

Get that error, then it breaks.

**Comment by Drutol** [comment]
Update pushed... Have you noticed any delays during network bidding , or anything concerning client information exchange?

**Comment by Aeotoc** [comment]
I couldn't use anything with the above error. I'll have to test it thursday

**Comment by Drutol** [comment]
Okay then , I hope that this delay is only PTR thing ;d
