### ISSUE TITLE
Request : Webseite : Edit options

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#175]
id like to make adjustments via web page, then download the data and import it into the addon.
sometimes its just a small adjustment, and then i dont need to start wildstar first, make the change with the addon and upload the data again.

**Comment by Drutol** [comment]
This is something I will do after my break finishes , editing involves quite a lot of effort as I have to alter the export string somehow.

**Comment by Larnen** [comment]
Will that also need the ability to pull the data from the webpage back to the in game client, as otherwise the two will get out of sync and website edits will be overwritten at the next export?

**Comment by Hysteriana** [comment]
that ability already exists.

**Comment by Drutol** [comment]
Update with editing is almost done , but we need to wait for more storge space. I've 6.5$ already so there's little to go.

**Comment by Drutol** [comment]
Editing is ready , now we need to resolve the issue concering hosting...

**Comment by Hysteriana** [comment]
close ?
