### ISSUE TITLE
Request : v2.08 : On Screen Notification in case of auto assigned ep

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#176]
id like a extra control to see if the auto ep assign has been triggered.
like a big on screen error message with event + value.

**Comment by Drutol** [comment]
Error you say...

**Comment by Hysteriana** [comment]
thats how aflogicloot informs about profile switching.
something like that for automatic events would be nice, so you dont have to check every time.
and problems like that all bosses are ep awarded at once would be discovered sooner and quicker be undone.

![hysteriana_doomstar 150523 205952](https://cloud.githubusercontent.com/assets/11199863/7785403/c7901c1a-018e-11e5-84f2-631405031efe.png)

**Comment by Drutol** [comment]
Added v2.10
