### ISSUE TITLE
Bug When Viewing Logs

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#177]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4515: bad argument #3 to 'SetCellData' (string expected, got nil)
stack trace:
    [C]: in function 'SetCellData'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4515: in function 'LogsPopulate'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4504: in function 'LogsShow'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4278: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4277>

**Comment by Drutol** [comment]
Hmm your log somehow does not contain modifier value...
Can you send me export string or xml file? And the name of troublesome player ^^

**Comment by Drutol** [comment]
Fixed v2.09
