### ISSUE TITLE
Add Loot Manually

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#178]
Hi,
A couple of times I've had a UI error when the master looter assign happens. I'll try and catch the next one. This would be fine, except I cannot see a way to manually assign loot to a user other than when it first drops. 

Could we have a way to manually add loot. We can manually add the GP with a comment but then it doesn't appear in the loot logs which could be confusing.

Thanks

**Comment by Drutol** [comment]
This can be easily added , all you need is item ID as there's no other way to specify an item.

**Comment by Drutol** [comment]
Added v2.09
