### ISSUE TITLE
Logs Not Showing Timed Awards

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#179]
Hi,
The logs for users do not appear to be showing everything. For example in last nights raid we had hourly EP awards. We saw the message appear several times on the party line as expected, but the logs for each individual do not show them. 

This makes it hard to tally up the EP/GP totals, as we should be able to start at base and then apply everything in the logs to reach the current total.

Could I confirm that the following should all appear in the logs:
- Events (appearing)
- Timed awards (not appearing)
- Decay (appearing)
- Manual awards (appearing)
- Loot drops (appearing)

It may be really useful for each line of the log to have an extra field showing what the running total is after that amendment.

Thanks!

**Comment by Drutol** [comment]
Hmm, I somehow did not put the line that registers events there. The "after" value will be added after 22th.

**Comment by Hysteriana** [comment]
another "copy paste" mishaps ? :D

**Comment by Drutol** [comment]
Oh there's no THAT much copy paste...

**Comment by Drutol** [comment]
Timed award logs now appear in Logs window. v2.09
