### ISSUE TITLE
Bug : Convergence Kill was not recognized by the auto ep handler

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#18]
same as with prototype, the kill didnt trigger the auto ep handle

**Comment by Hysteriana** [comment]
convergence kill has been auto added, guess this issue can be closed ?

![unbenannt](https://cloud.githubusercontent.com/assets/11199863/6606773/36fea532-c83a-11e4-9cb5-d19c9898cd41.png)

**Comment by Drutol** [comment]
I like when things fix all by themselves :D.
