### ISSUE TITLE
Rename Users

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#180]
Minor thing - can we rename manually added users. Or export/import their data. We have had a raider name change and the system cannot seem to be updated to reflect the new name.

**Comment by Drutol** [comment]
For the time being you can export to JSON (website export) change the name and import back. After I'm back I'll add rename option.

**Comment by Hysteriana** [comment]
i just added the new name as raider, and the old name converted as twink.

**Comment by Drutol** [comment]
Added v2.09
