### ISSUE TITLE
Bug : v2.08 : Chat Bidding auto start

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#181]
when using start auction automatically, the wrong item will be used for auction.
like when i random assign some stuff first, then select another item and click start chat bidding, the item i have already assigned will be used for auction.

**Comment by Hysteriana** [comment]
v2.10 Chat bidding still broken

**Comment by Drutol** [comment]
I'm working/trying to set up attendance now , right now I've made the main window resizeable what will automatically add new columns + revamp of labels.( need more space for new data types). You mean it's broken entirely?

**Comment by Hysteriana** [comment]
not entirely. it just selects the wrong item.
the last already assigned one

gesendet vom Handy.
Autolorektur hat Schuld :)

**Comment by Drutol** [comment]
Fixed v2.11
