### ISSUE TITLE
Request: Attendance

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#182]
Hi,
Would it be possible to add a report which basically summarises number of runs (total/over last X days/user selectable) attended by each player. So if there were 10 runs over the period in question and player Z had been to 5, they would report as 50%.

Thanks

**Comment by Drutol** [comment]
I'm currently trying to decide whether I want to build whole "Raid Summaries" with items , attendance , ep/gp fluctuations , boss stats etc. or a few modules separately. I don't want to code something useless again... ^^. This is the plan after 22th.

**Comment by Drutol** [comment]
I'm currently trying to implement this ...

**Comment by Drutol** [comment]
I've general concept on how I want to do it. Fighting with UI right now.

**Comment by Drutol** [comment]
#211
