### ISSUE TITLE
Bug when importing

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#183]
Testing the import/export.

1) Click Export Importable Database
2) CLick Export/Import
3) Click Copy to CLipboard
4) Paste this into an editor
5) Make a manual edit to one members GP
6) Click Import Database
7) Click Export/Import

If you click on this it throws the following bug:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3502: bad argument #1 to 'ipairs' (table expected, got nil)
stack trace:
    [C]: in function 'ipairs'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3502: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3435>

**Comment by Drutol** [comment]
If the textbox says that the string is too large , then you need to split the string copied to clipboard in 30k characters parts and paste each part with clicking "+" button to concatenate each part .Once you are finished just press import.There's no other way round unfortunately.The bug itself is now prevented.
