### ISSUE TITLE
Fetching with the main module

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#184]
So whenever I fetch from someone to sync up the DB's, or someone fetches from me, with the master module, it doesn't actually update the DB.

**Comment by Drutol** [comment]
Do you get entry in the log about fetch attempt? If so , does it say yes or now in the "sent data?" column? There were some problems on PTR before drop5 , can anyone else relate?

**Comment by Hysteriana** [comment]
sometimes it takes quite the time for the data to arrive... same as on ptr

**Comment by Aeotoc** [comment]
it says "yes" but none of the data changes

**Comment by Drutol** [comment]
There's very little I can do then , the data is sent but W\* just delays the process.

**Comment by Aeotoc** [comment]
@Hysteriana How long is quite some time?

**Comment by Hysteriana** [comment]
I think carbine changed stuff again with last patch and it's broken for now
Am 22.05.2015 02:24 schrieb "Aeotoc" notifications@github.com:

**Comment by Hysteriana** [comment]
@Mordonus let me know if you want to test the sync / share / fetching.
maybe they just changed something with last patch.

**Comment by Drutol** [comment]
Update , Carbine has broken the system of data exchange and I can do NOTHING about it. So there's that...
