### ISSUE TITLE
Important : Website hosting!

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#185]
So... everything comes to an end and so does the storage space on free hosting plan. I had to close new guild's registration because there's no more space.
Each guild , user , item , log consumes one row. On free hosting 10k of them is available but right now we've hit **8440/10000**.
![image](https://cloud.githubusercontent.com/assets/6102530/7748911/3d833802-ffc9-11e4-842c-72cd1e305e1a.png)
I've just graduated from high school and cannot justify spending money on this , especially when I'm not the user. And down to the point : I need donations so that other guild accounts can be created.

**How much do I need now : 9$/month**
How much will I need in the future : 9$/month + 7$/month

9$ are for database for this sum we will have not 10K rows but 10M rows which will be sufficient for eternity.
![image](https://cloud.githubusercontent.com/assets/6102530/7749073/a4fd02b4-ffca-11e4-8485-e5006eceff12.png)

7$ are for CPU share , on free hosting webiste must be offline for 6(or so) hours and will go to sleep after 30 minutes of inactivity.You may have noticed long loading times when entering for the first time ; it was waking up from sleep.
![image](https://cloud.githubusercontent.com/assets/6102530/7749061/9163e9d4-ffca-11e4-94a9-37afcc305041.png)

Either that or ads , but I don't know whether ads will bring enough money + they will be polluting the whole site.

To conclude , I'm not asking for money for myself , I'm doing this for learning and entertainment purposes (odd hobby , isn't it? :D) but if you want to use it there's no other way.

[![](http://www.lagunabeachdogpark.com/images/paypal_donate_button.png)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=EYCJF65UGLD82)

**Comment by Hysteriana** [comment]
how about privat hosting ? since i got access to root servers

**Comment by Drutol** [comment]
What do you mean by root servers , if we can setup mysql/postgress database there , that would solve the biggest issue. I don't know how hard is it to setup rails in "raw" environment though...

**Comment by Hysteriana** [comment]
root means, it is a rent linux server with full root access.. no v-server or such..
i can do what ever i like, means i could host a copy of that page for my guild.
not sure if database access from extern is possible cause security reasons

**Comment by Drutol** [comment]
External DB is possible I just need address username and password , postgress preferably , but let's wait a bit with this. If you want to host it all by yourself just grab source from github and you are good to go.

**Comment by Drutol** [comment]
Got 6,5$ already , I'm currently setting up bank account for this and next week we should be up and running ^^.

**Comment by Hysteriana** [comment]
@Mordonus what do you mean by "just grab source from github and you are good to go" ?
do i need to install / setup anything first ? since i dont see any index php / htm or html pages ?

**Comment by Drutol** [comment]
If you know what you are doing , then this option is for you. The whole page is written in ruby ( rails framework ) there's no PHP or plain html , there is html.erb instead (html with embedded ruby ) There's quite some work to set it up but nothing that prevents you from trying ^^

**Comment by Drutol** [comment]
It requires some basic knowledge about ruby on rails and you will have to make some changes in the code here and there.

**Comment by Hysteriana** [comment]
peeeeeeewwwwwwwwwww...

a felt eternity of "i have no idea what im doing"
a lot of reading....
a bigger lot of try and error....

 I GOT IT !!! :D 

little issues here and there like the register, i activated my self directly in the database it self...
and the items are not shown yet, only the ids..
but at least i can upload so far ^^ need to fix the download yet :/

**Comment by Drutol** [comment]
Congrats! I've written to you in curse PM. See ? It isn't that hard ^^

**Comment by Hysteriana** [comment]
IT IS THAT HARD... from scratch with no idea what im doing..

but then i am a genius.. so .. :D

**Comment by Drutol** [comment]
You will be developing this thing in no time!

**Comment by Drutol** [comment]
Website is now hosted on the server that @Hysteriana has provided , thanks! Money from donation was spent entirely on domain name "raidops.net" - waiting for it to be set up.

This is the current website address http://148.251.194.214:9292/
The old website now redirects to the new one.
