### ISSUE TITLE
Bug : v2.08 : Mega Error since last Wildstar Patch

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#186]
today the auto assign ep tool went wild... it assigned everything added to everyone at once.
i could not access the auto adding cause the button goes to "show invite dialog" too

i will try and purge to gain access back

also the sync doesnt seem to work anymore, neither not full database sync.
the sender get the sent data yes entry in his log, but the recipient gets nothing

**Comment by Hysteriana** [comment]
did purge and still no access to auto assign tool.
is there a slash command to access it ?
if not i hope the purge deleted those entries too.

**Comment by Drutol** [comment]
I'm coming back today , just in time I guess. But that's odd that patch would break this.

**Comment by Hysteriana** [comment]
woot woot welcome back 😁

**Comment by Drutol** [comment]
22th isn't it? Just one more exam in next 7 hours.

**Comment by Hysteriana** [comment]
wish u luck

**Comment by Drutol** [comment]
Hah they have probably resized sprites' sizes that's why. Update today.

**Comment by Hysteriana** [comment]
not sure if the sprite sizes was the reason for adding ep wild.

**Comment by Drutol** [comment]
It went wild during raid or just at random?

**Comment by Hysteriana** [comment]
during raid. we were 2nd lvl ga and for no reason the raid got every added
boss ep assigned at once. from x89 to avatus.

**Comment by Drutol** [comment]
Hmm , I've made some changes to prevent such a thing happening in the future but we have yet to see.
