### ISSUE TITLE
Bug : v2.09 : Lua Error setting Guildchannel

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#187]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1150: attempt to index field 'wndBid2Settings' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1150: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1144>

**Comment by Drutol** [comment]
Hmm seems to be working for me... does the problem persist? How quickly have you done this since /reloadui ?

**Comment by Hysteriana** [comment]
the guild name " gviiiii " seemed to be set after reloadui, but everytime i click into that field, and press enter, i get the lua error again.
with shorter guildname too..

![hysteriana_doomstar 150524 142736](https://cloud.githubusercontent.com/assets/11199863/7787838/01713648-0221-11e5-89ab-0cc8b2d63271.png)

**Comment by Hysteriana** [comment]
also the Network Bidding Button is inactive for me now. maybe there is a connenction ?

**Comment by Drutol** [comment]
That means that the whole module wasn't activated... Have you disabled ML changes in settings?

**Comment by Hysteriana** [comment]
inject controls to carbines masterloot addon is enabled.
network bidding button still disabled.

**Comment by Drutol** [comment]
Do you have Master Loot Dependency addon enabled?

**Comment by Hysteriana** [comment]
only RaidOps,
no raidopsmasterloot and and no raidopsmm

**Comment by Drutol** [comment]
Aaaa , I know what I have done

**Comment by Drutol** [comment]
Fixed v2.10

**Comment by Hysteriana** [comment]
from now on I can say: you know what you did last summer..  :-D

gesendet vom Handy.
Autolorektur hat Schuld :)
Am 25.05.2015 20:05 schrieb "Mordonus" notifications@github.com:
