### ISSUE TITLE
Request: v2.10 : Surpress Master Loot Popup

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#188]
since "NotNowMasterLoot" doesnt work anymore, it would be nice to be able to disable the BIG HUGE masterloot window popup, at least while in fight and some stupid trash drops a Sign of XXX.

**Comment by Drutol** [comment]
It works , just change in the LUA file of not now master loot :
line 44 at NotNowMasterLoot.lua from:

addonMasterLoot = Apollo.GetAddon("MasterLoot")

to:

addonMasterLoot = Apollo.GetAddon("MasterLootDependency")

**Comment by Hysteriana** [comment]
good to know thx

gesendet vom Handy.
Autolorektur hat Schuld :)
