### ISSUE TITLE
Bug : v2.10 : Custom Events Notify doesnt stay enabled.

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#189]
when i activate the notify option, and do a reloadui, its deactivated again.

**Comment by Hysteriana** [comment]
is it bound to single entries ? do i need to activate notify for every entry seperate ?
i just tested it, and even without notify active, i get the on screen message when i kill a test mob

**Comment by Drutol** [comment]
It triggers on every award right now , notify affects chat only.

**Comment by Drutol** [comment]
Fixed v2.12
