### ISSUE TITLE
Bug : v2.10 : single ep edit does not show in recent activity.

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#190]
see title

**Comment by Drutol** [comment]
Hmm , for me it adds entry for each action (add/sub/set) in both mass edit mode and single selection. Any more points on how to reproduce?

**Comment by Hysteriana** [comment]
see its listed in sanya log, but not in the recent activity log

![hysteriana_doomstar 150526 215436](https://cloud.githubusercontent.com/assets/11199863/7831114/c368f2de-0453-11e5-8aef-f01987a33f09.png)

**Comment by Hysteriana** [comment]
has been fixed with a purge.
