### ISSUE TITLE
Bug-ish : v2.10 : Added Alts doest prevent to alts again as standalone player

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#191]
when i someone import data, from the page, other player, backup, guildmember, what ever,
names that have been added as alts, are shown again in the roster.

**Comment by Hysteriana** [comment]
still an issue, maybe a button to remove all player names that has already been flagged as alts ?

**Comment by Drutol** [comment]
Fixed v2.12 , but report if it still occurs.
