### ISSUE TITLE
Important : Network Bidding , Data Sync and Sharing 

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#192]
Carbine has broken addon data exchange system , so these features are just broken.Nothing that I can do with it.

Forum topic for interested : https://forums.wildstar-online.com/forums/index.php?/topic/124371-130-api-patch-notes/page-2

**Comment by Aeotoc** [comment]
Wow. Read through that whole thing. Way to fucking go, Carbine. Right now, does the network bidding use Global or party? My assumption is party. Also, chatbidding should still work, correct?

**Comment by Drutol** [comment]
Chat bidding will work , I've tested network bidding on guild channel but it was breaking after a while because of traffic , on PTR at least (2 ppl). I doubt that party will solve that especially when messages are flying between 20 people. Fetching and syncing is impossible. I'll try to further optimize network bidding but no promises...

**Comment by Aeotoc** [comment]
Hopefully they just decide to increase the limits by 100x

**Comment by Hysteriana** [comment]
carbine respond: https://forums.wildstar-online.com/forums/index.php?/topic/124371-130-api-patch-notes/page-2#entry1325197

**Comment by Hysteriana** [comment]
so the full sync means 50k max counting as 100k penalty and then nothing for a while ?
4000 chars / member in party chat, means 200 chars per sec in a 20 member raid for smart sync ?
thats some hardcore delay...

**Comment by Hysteriana** [comment]
what may be the whisper limit ? sending sync per whisper message ?
and custom channels = global channels ?

**Comment by Drutol** [comment]
I've not played with those custom chat channels yet. Probably there's no documentation for them... Once you go smart sync the size depends on the differences but generally it should be much smaller. Network bidding may work over those chat channels as the messages are fairly short but there's a lot of them. I've no idea how sync on chat channels.

**Comment by Hysteriana** [comment]
in wow add-ons could intercept messages before they would be displayed.
like that raid invite trigger word or the chatbidding. don't know if the ws
Api allows to suppress the message display. if so one need to know the max
length of a chat message and then split the sync Infos. even if the message
can't be hijacked you could set a custom channel and then use it to send
stuff

gesendet vom Handy.
Autolorektur hat Schuld :)
Am 28.05.2015 07:41 schrieb "Mordonus" notifications@github.com:

**Comment by Drutol** [comment]
Optimistic results for Network Bidding , chat channels may be the solution.

**Comment by Drutol** [comment]
Data Sync would take approx 6 minutes  with 50k characters as db sample.

**Comment by Hysteriana** [comment]
no guild has 50000 Charakters 😂

gesendet vom Handy.
Autolorektur hat Schuld :)

**Comment by Drutol** [comment]
It has , but over chat channel it takes approx. 6 minutes. All in all ICComm would take ( hoping that it'd work) roughly the same time due to throttle cd.

**Comment by Hysteriana** [comment]
Charakters as in people 😇

gesendet vom Handy.
Autolorektur hat Schuld :)
