### ISSUE TITLE
Assign Loot Manually error

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#193]
Sure youve had this one many times, but when you try to close the new 'Assign loot manually' window you get:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6431: attempt to index field 'wndMAL' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6431: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6430>

Great addition though, thanks for adding it :) 
Larn

**Comment by Drutol** [comment]
Yay , instead of wndMA I've written wndMAL...

**Comment by Drutol** [comment]
Fixed v2.12
