### ISSUE TITLE
Delete Loot

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#194]
Side by side with the ability to add loot manually, can we have the ability to DELETE loot. There are several items that are appearing which date from when we were learning to use the addon which are misassigning GP. More generally there may be circumstances where something is assigned and then traded within the new 2 hour window. At the moment it needs a manual GP edit and the loot logs/logs will not tally.

So could we:

1) Have the ability to DELETE an assigned item
2) Have the ability to REASSIGN an assigned item

Both should probably record an event that this has happened in case of paranoia, but this would make life a bit easier!

Many thanks - loving the addon!
Larn

**Comment by Drutol** [comment]
Oh so you can trade loot now? Sure then :D

**Comment by Drutol** [comment]
Added v2.12
