### ISSUE TITLE
Bug when renaming player

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#198]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6678: attempt to index field '?' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6678: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6672>

Thanks!

**Comment by Drutol** [comment]
Fixed v2.13
