### ISSUE TITLE
Website Upload - Duplicate User

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#199]
Hi,
Given that the rename user option was bugging, I edited the RaidOps save file directly to change user "ashuan eruai" to "Ashuan Eruai". This shows up fine in game, but on the website i now have a duplicate user - both "ashuan eruai" AND "Ashuan Eruai".

If I had to take a guess the website upload is merging not replacing? So will this also occur if you delete a user ingame and then upload?

So 3 things:

1) Is there a general issue with delete and then upload?
2) Any chance of a 'Delete User' on the website
3) Or if not could you just delete user "ashuan eruai" manually

Thanks!

**Comment by Drutol** [comment]
I'll add remove member option today to the website.

The reason is that IDs in addon are different than on the website and the primary key there is member's name. I'll probably switch from merge and update to full replace.

**Comment by Drutol** [comment]
Added in newest update.
