### ISSUE TITLE
Point Modification logging

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#2]
As it is, the logs for changes to points on epgp/dkp seem to reset daily or so. Is it possible to keep it from resetting but every two weeks? Or have an auto logfile created after every reloadui/logoff (preferably the latter if there is a way to distinguish between the two.

**Comment by Drutol** [comment]
They are resetting every time the UI is reloaded. They consume quite a bit of space but they can be easily saved if you so desire.

**Comment by Drutol** [comment]
Changed in rev 129ish
