### ISSUE TITLE
Looking for help with wiki!

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#20]
As new updates are emerging , the UI is changing , some things go away and new things come.I'd rather prioritise the code itself than writing a wiki , if you wanna help write here! + I'm hardly any good at it ^^.

**Comment by Aeotoc** [comment]
I would be happy to help. I was planning on making a video setup guide once we got everything settled with UI functionality. Honestly, my goal has been since you've been working so diligently on this to get the addon to a point where you can proudly remove the "beta" tag from the addon.

**Comment by Drutol** [comment]
Tbh , I think that we are much closer the point where we ditch this "beta" thingy than we were month ago.(It's smaller already xd).Right now the only "big thing" to do is to rewrite/redesign/reimagine raid summaries.This weekend I'll try to implement some things from your spreadsheet and then off to rewrites we go. I greatly appreciate your help as this is my first public project ever and I have little to no experience about running such a thing ^^. Wiki should be editable by anyone eager to do so now.

**Comment by Aeotoc** [comment]
Sorry I've been somewhat AWOL. I've had to get some things straightened out in guild since we downed Ohmna on Thursday and are prepping for some QT in DS. Hopefully, if all goes well, I should have some spare time Tues/Thurs this week to dedicate to editing the wiki.

**Comment by Drutol** [comment]
No need to rush ^^ .Gratz on your Ohmnomohmna :D.

**Comment by Drutol** [comment]
I'm closing this as the UI needs to stabilize , I'll open new issue once it happens.
