### ISSUE TITLE
Error on startup / reloadUI

### ISSUE THREAD

**Issue by ElmRR** [Mordonus/RaidOps#201]
Hi,

Not too sure whether this is isolate to me (as others in the guild appear to be using RaidOps ok with the same data) but I'm getting the below error on game startup / reloadUI:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2658: 'for' limit must be a number
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2658: in function 'LabelUpdateList'
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:282: in function 'EPGPChangeUI'
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:100: in function 'EPGPInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:443: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:283>

Seemed to begin happening a few updates ago and will clear if I delete the addon & addon save data then reinstall. RaidOps will then run fine on the first startup after reinstall but once I restart Wildstar I get the error again and RaidOps will refuse to startup / function from that point on without removing all data again.

**Comment by Drutol** [comment]
Ups.. Try resizing main window I'll fix this today.

EDIT: Fixed v2.13

**Comment by Drutol** [comment]
Just btw , you seem to be using DKP and I've been neglecting this for some time. What are the features that need to be updated in terms of missing DKP functionality?

**Comment by ElmRR** [comment]
That's worked great - thanks :)

With regard to features that I'd look to be updated or are missing there's nothing which springs to mind at the moment as we're using a system which has been designed around RaidOps. That said I'll let you know should anything come up that I can think of which would be useful or I feel may improve it's functionality for us.
