### ISSUE TITLE
Bug-ish : v2.13 : Chat Bid Loot Assign

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#204]
the assign button from the chatbidding depends on the setting in the masterloot addon.
when in masterloot addon i set show only usable player, and someone use chatbid for style need or what ever, i cant assign it to him by chatbidding until i set masterloot addon to show all.

**Comment by Drutol** [comment]
I'm going to add those players as an exception in separate "bidders" group . This will need to be tested on the hill :)

**Comment by Drutol** [comment]
Just btw , have you tested this thing with tokens?

**Comment by Drutol** [comment]
Fixed v2.14
