### ISSUE TITLE
Error When Assigning Loot

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#205]
Seems new in the latest version (2.13):

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:735: attempt to concatenate global 'strRoller' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:735: in function 'BidProcessMessageRoll'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:656: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:647>
    [C]: in function 'PostOnChannel'
    ui\FriendsList\FriendsList.lua:565: in function <ui\FriendsList\FriendsList.lua:556>

This happened a few times tonight.

**Comment by Drutol** [comment]
Just the matter of moving something a few lines up ;d . Somebody has tried to roll in different range. Fixed v2.14
