### ISSUE TITLE
Random Error

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#206]
Seems new in the latest version (2.13). No idea why this happened, nothing was happening at the time (no rolls on party line etc):

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:735: attempt to concatenate global 'strRoller' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:735: in function 'BidProcessMessageRoll'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:656: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:647>

Thanks,
Larn

**Comment by Larnen** [comment]
Damn, pasted wrong error in. This is a duplicate of the other bug raised earlier. However there was another error that occurred randomly when nothing was happening. I will append to this when it recurs. In the course of this evening we had the one above twice and the one I failed to post in once.

**Comment by Drutol** [comment]
Closing this then , just open new issue when you spot the bug in the wild :)
