### ISSUE TITLE
Events Handler

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#207]
This is going to be a bit vague I'm afraid, but last week we killed Phagetech Prototypes and Phage Maw. The event handler didn't trigger for either. Phagetech Prototypes has triggered in the past.

Events were triggering today, although we didn't do those 2 bosses, so I can't check until Sunday if its working.

Was there a fixed issue in the version that was live last Sunday?

**Comment by Drutol** [comment]
Unit death detection is kinda wonky as I have to check every "damage dealt" event fore "Kill" flag , and there's no event "encounter ended - wipe/success". The other possibility is to track what NPCs say , just like I've tried with phageborn council but I'd need their phrase(s) on death.
I didn't change anything in this part of an addon recently(logic at least).

**Comment by Drutol** [comment]
Fixed in the past...
