### ISSUE TITLE
Offspec Assign Not in Loot Logs

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#208]
We had an item tonight that was assigned offspec to a member. Another member who was dc'ed as the roll went through then asked if he could have it and we reassigned.

However the original member did not have the item in his loot logs, but DID in his logs. When it was assigned to the new person main spec, it appeared in the loot logs as expected.

We charged 0 EP for offspec - could that be messing it up somehow?

Thanks!

**Comment by Hysteriana** [comment]
the loot log has a filter, by default min gp is set to 1
check the settings

**Comment by Larnen** [comment]
I don't have a value set for Minimum GP cost. I do have a minimum ilvl of 1. If no min GP cost is set, does it have a default value?

Which reminds me - the 'Only equippable' is an excellent filter and very helpful, but fails on armour tokens. Can the armour tokens be classed as equippables as while they are technically not, you trade them for things that are. As it is the 'equippable only' ignores probably the most important loot in the instance.

**Comment by Drutol** [comment]
Filter now includes tokens. It turns out that I forgot to fill in minimal GP value to the setting on startup and it defaults to 1 and stayed this way... we have the culprit then.

**Comment by Hysteriana** [comment]
_duck_ and stay still in a corner. waiting for the answer

gesendet vom Handy.
Autolorektur hat Schuld :)

**Comment by Drutol** [comment]
About the default value?
