### ISSUE TITLE
Cosmetic Error in Timed Award Screen

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#209]
Please see attachement. 

![epgp](https://cloud.githubusercontent.com/assets/12396880/7975458/f52e0364-0a65-11e5-8405-3e9f56fabbcc.png)

Note the 'Next Award in:" reads "0-1:56:12" where it should have read "00:56:12"

Thanks!

**Comment by Drutol** [comment]
Fixed v2.14
