### ISSUE TITLE
Bug : v2.0 ref 130 : Lua Error : Empty Import erased everything

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#21]
testing the export / import, i selected Import Database and and clicked Export/Import without anything inside the copy/paste window
got this lua error, and now everything is gone... also cant import guildmembers.. 
but the EasyDKP_0_Gen.xml is still 54kb big, any chance to get the data back ?
if not i guess i have to purge again and start over again :(

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3085: attempt to index local 'tImportedTables' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3085: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3037>

**Comment by Drutol** [comment]
Hmm , my bad I'll fix this asap.

**Comment by Drutol** [comment]
Send me this .xml file

**Comment by Hysteriana** [comment]
as requested: http://pastebin.com/NLSKm2z7

**Comment by Drutol** [comment]
Not much that I can do sadly :(. Do you have any .xml file that refuses to be exported/imported ?

**Comment by Hysteriana** [comment]
i will reinstall... start over and then make a fresh export and will see whats happen if i try to import it.

**Comment by Drutol** [comment]
I'll close this issue for now , if anything bad happens just open new one.
