### ISSUE TITLE
How this addon is done :D

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#210]
![5mwcbre](https://cloud.githubusercontent.com/assets/11199863/7983099/3f341b5e-0abd-11e5-90f7-14989e3e7549.jpg)

**Comment by Drutol** [comment]
![](http://i.imgur.com/ULWUPTp.jpg)

My seal of Quality Assurance :D

**Comment by Aeotoc** [comment]
So, can you take down the "Carbine has broken addon data exchange system, and therefore this feature is broken." thing?

**Comment by Drutol** [comment]
*Not applies everywhere
I'll be trying to revive Network Bidding now , so maybe I'll be able to take this down...
