### ISSUE TITLE
Current plan

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#211]
Sooo , there are 2 big and 2 small things on the horizon...:
- Raid Summaries
  - To which I'm fairly reluctant , I have some code for them but every now and again I keep asking myself whether it's relevant at all. I'm not convinced that it would be helpful a tiny bit , and tracking attendance is not something that can be done with a few lines of code but it requires a fair amount of foundations. I'm just starting writing and after a while I'm like "Meh , let's play some Anno2070 or whatever" ;d
- Master Loot
  - This one came to my mind writing the bullet point above. I want to write my very own ML addon and stop being reliant on carbine's one (provided that I'm already overriding like 70% of it). This is something I'd like to do . Maybe reuse some ideas, throw something new... what do you want as a Master Looter?
- Website
  - Any thoughts or feedback? Those are some stats from the last month:
    ![image](https://cloud.githubusercontent.com/assets/6102530/7989390/7f907cf2-0ae9-11e5-8c67-18c94def1d74.png)
- Documentation
  - We are quite behind again... @Larnen suggested creating FAQ a while back , but I cannot ask those questions because I can take something for granted. So maybe you can ask them and I or anyone else will write the answer.

This is what comes to my mind as of now. What's your view?

**Comment by Drutol** [comment]
I have a very nifty concept for separate ML addon (imo)  , more info soon. Entering design mode.

**Comment by Aeotoc** [comment]
I'm excited to see it.

**Comment by Drutol** [comment]
I'll share it as soon as I've working prototype , I'm currently on the third iteration of UI ^^

**Comment by Drutol** [comment]
Soo... this is my idea for Master Loot addon: (it's just a prototype)
![image](https://cloud.githubusercontent.com/assets/6102530/8020301/f2a7e956-0c73-11e5-9162-23eb2763377a.png)

When loot appears , items will be present in the:
- Loot Pool
- Random Pool
  - All items that end up there will be randomly distributed across recipients , I want to add filters so for example signs will always start there.

Instead of : select Item -> select Looter -> press the button  I want to drag&drop items to recipients and when you are done , start shipping loot to happy recipients :D.

This is the core concept , there's a TON of stuff to do. Probably a week worth of time ;d

What do you think?

**Comment by Hysteriana** [comment]
@Raid Summaries : i kinda like the attendance feature to determine the priority on who may sit on the waiting list. or to make it a factor on loot distribution, like consider it into the PR.

@Master Loot : i like it fast and simple.. assigning loot waste quite some time. 
i like the random pool idea. im not sure about the drag and drop, sounds like mistakes waiting to happen :)

@Website: id like something like a account system: different logins with different permissions
also a log would be nice, who uploaded/downloaded what when, who did a edit and what.

**Comment by Drutol** [comment]
- Raid Summaries
  - Due to my personal preferences I'll focus on 2 other things first ;d
- Master Loot
  - I was planning to have final confirmation window. I have to do this anyway as I've to cut off myself from the default one. From my perspective it may be a bit quicker , but who am I to say this ^^. If this turns out to be inefficient I can always switch to "select,select,press" mode.
- Website
  - Cool idea , next thing to do after master loot (or in-between).

**Comment by Larnen** [comment]
@Raid Summaries: Well I'm biased as I suggested it, but its there to fix a specific problem. We have 2 types of raiders, and one of the distinctions between them is that one group makes a commitment to a certain attendance level. This helps in planning and ensuring that we don't over-recruit. It can also, as Hysteriana said, be helpful if you need to make a decision between who to bench - someone who has been a regular may be given priority over someone with very low attendance. At the moment in order to do this I'd have to go to something like Wildstar Logs for each raid as far back as I want and enter it all into a spreadsheet. One of the things that makes RaidOps so great is that it eliminates spreadsheets. Plus you have all the data about who was in each run already there (or if not it could be added with a stub log entry or the like). In terms of how to implement it, itd be great to simply have a report that lets you choose 'Last X Raids', 'Last X Days' or 'Selected Raids' and then just run days attended/days max. This is definitely something I need to do and something I used a lot in the RaidBuilder web based system I used in Wow until about 2010.

@Master Loot: Nice to have but for me a functionality sidegrade versus something new. If you could build in Not Now Master Loot and make it resizeable (I still cant resize the RaidOps one for some reason) that'd be good. I'd love to see wildcard whitelists for auto assign so that just happens on its own. Eg "Sign of *" gets randomly assigned with no loot logs etc although thats not a big deal.

@Website: I quite like the website as is. Accounts may be useful so I can give other Officers the ability to upload and see who did and when. Generally though I love the website although there are some cosmetic tweaks that would be good to make it more sparkly :) But the functionality is solid at the moment.

**Comment by Drutol** [comment]
- Raid Summaries
  - Unfortunately the implementation is not that simple , and there's no data as of yet. If that's how the things are I could add attendance somewhat like this : 
  - Upon entering GA/DS/Y-something you get the prompt asking whether you want to start session.
  - Timer starts running and adding up time to raiders.
  - When certain time ( percentage etc.) threshold is met their account gets credited with raid attendance.
    The data would be visible in label in form of percentage or "raids attended/all raids" in the set 
    period or in the big summary window like the first one (there's command for that in the cmd list in settings).This also makes great material for website :).
- Master Loot
  - I want to automate this process as much as I can , a while back I said I wanted to implement "Not Now Masterloot" functionality , but I want to create my own playground and not be surprised again that carbine has rewritten whole addon the day before drop 5 hit.  We will see how is efficiency once I'm done . I treat this as a little experiment ^^. 
- Website
  - My first website ever and if it weren't for http://getbootstrap.com/ the page would look real crappy  as CSS and javascript are still magic contraptions for me... So forgive me not adding flashy stuff here and there.

**Comment by Drutol** [comment]
I need somebody to go to GA/DS and type this in chat:       

> local tMap = GameLib.GetCurrentZoneMap() for k , id in pairs(tMap) do Print(k .. " " .. id) end

Take a screenshot of chat window and post it here. :)

Going to different floors would be helpful as i don't know how the results will change.

EDIT : Halfway through attendance...

**Comment by Hysteriana** [comment]
you forgot to mention that you have to write /eval first.
or your guild mates will give you a weird look :)
but google is my friend :D 

![floor](https://cloud.githubusercontent.com/assets/11199863/8024870/65166ccc-0d43-11e5-812e-ec29009d5b02.png)

**Comment by Drutol** [comment]
thanks , sorry for this /eval ^^

**Comment by Drutol** [comment]
So what I have now:
- PopUp prompting for "Start/Pause/End" when needed.
- Toolbar with "Start/Pause/End" and timer.
- Restore
- Location detection
- Data for further processing 

What I need:
- More ids from DS (incentive to progress xd) and this Y-something raid.

What I'll do tommorow:
- Labels in % or raw numbers (2nd label profile will come in handy I suppose)
  - Attendance in GA,
  - Attendace in DS,
  - Attendance in Y-something,
  - Attendance in total.
  - Anything else?
- Big summary window.
- Settings.
- Other misc stuff.

I'm going to name this raid Y-something , I'm not gonna google it xd

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/8031371/0f3acbf0-0dce-11e5-8288-72370027c19e.png)

What do you think?

**Comment by Hysteriana** [comment]
looks good. lucky I have a wide screen monitor :-D

gesendet vom Handy.
Autolorektur hat Schuld :)

**Comment by Drutol** [comment]
There're 8 labels in total but you don't have to display all of them. I'm now adding attandance grid to website.

**Comment by Drutol** [comment]
Attendance update is live on curse. It's rather big so let the issues start flood :)

**Comment by Hysteriana** [comment]
y-83 : there you go:

![location](https://cloud.githubusercontent.com/assets/11199863/8053493/859d22f2-0e91-11e5-9595-7e476e999228.png)

**Comment by Drutol** [comment]
**Raid Summaries**
So , we have been discussing them in context of attendance. With v2.16 I'll be pushing window with the list of raids with 2 buttons:
- Show all players who took part in. Special rule will be applied to main window to consider only those players.
- Show loot awarded during this session. Opens Loot Logs and shows items looted between start and finish.

Is there anything else you would like to see added as we are entering "nice but useless" zone and I'm wondering where I should stop?

There'll be separate update for website with the same features.

**Comment by Drutol** [comment]
- Website
  - Pushing assistants update right about now , no logs at this time.

How does it work?
Assistant has to set up new account , log in , go to guild's page. In controls there will be button to apply for assistant role. Once he/she does this guild owner has to go to this page open "Review assistants" window and Accept (or reject) applicant. Once approved , assistant can do everything but guild removal and assistant management.

Please report any odd behaviour.

**Comment by Renira** [comment]
So far, the only issue I've seen with attendance deals with those characters that may switch between alts/mains for the duration of the raid.  We've had some members from time to time change out mid-raid depending on our needs. :)   Besides that, attendance and raid summary are both looking good!

**Comment by Drutol** [comment]
You're right , I've forgotten about them. I'll do something with them in next update.

Edit: With 2.20 all alt names will be converted to main's name. + This is probably the reason for either multiple attendances credited to one player or lack of certain players due to not reaching time threshold. So much stuff overlaps that it's hard to keep track.

**Comment by Drutol** [comment]
New Current plan issue posted.
