### ISSUE TITLE
Bug on Login

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#212]
Received this bug after logging in after a DC due to inactivity. I wasn't in a raid at the time, just idling in Thayd:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1169: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1169: in function 'Bid2PackAndSend'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1661: in function 'Bid2BroadcastMySuperiority'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1096: in function 'InitBid2'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:163: in function 'BidCompleteInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:136: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:133>

**Comment by Drutol** [comment]
Fixed v2.15
