### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#213]
I'm going to add some unobtrusive ads in some places of the website. I'm doing this for 2 reasons:
- Out of curiosity , to see how or whether it'll work.
- It'd nice to get something different than pure satisfaction , I think I'm working on this long enough to justify ads.
  - If there's any profit I'll be able to buy subscription for W\* and survive until F2P arrives.

As hosting is provided by @Hysteriana , tell me if you want a share of this money , provided that there will be any money.

How will it look like ? ( + attendance :) )
![image](https://cloud.githubusercontent.com/assets/6102530/8034904/910f5538-0dec-11e5-8f1c-abde533c8031.png)

**Comment by Hysteriana** [comment]
as far as i am concerned, i dont mind about some ads, as long as will help to keep this nice addon running, im all for it.

**Comment by Drutol** [comment]
I'll be checking out different ad providers as google says I have not enough text on the pages for their ad engine. Right now it's http://www.bidvertiser.com/.

**Comment by Larnen** [comment]
I'd be happy to pay a sub for the site/addon. I used to use a site called RaidBuilder back in 2010 for DKP in Wow, and I think that was about £5 a month. I don't know if the audience is big enough that enough £5's a month would add up to cover costs, and it may put some people off, but personally it'd be no barrier at all. 

Of course if people are paying the support expectations go up, and while its been excellent, you may find lots of folk with limited knowledge of how 'stuff' works making unreasonable demands. I suspect Hysteriana and I are both extremely old hands at this sort of thing ;) 

Anyway, saw the post earlier about the add revenue, and wanted to add that in the mix if it'd help.

**Comment by Drutol** [comment]
Yeah , I'm probably going to ditch those ads as they are giving less than curse at a current rate (2yrs for 10$ in amazon coupons) and are polluting the site. I'm targeting rather niche audience so I wasn't expecting much to begin with , and especially now with free hosting. 

I wouldn't mind some money considering time devoted to this whole project but I won't force anyone to pay . It's far too much rough around the edges to request any money + as you've said expectations would be much much higher. If you want to support me do so if not I'm cool with it.

I've taken a few days semi-off (finishing today) , to rest a bit and I'm having my driving course right now , and good god how stressful it is ! ^^. 

Right now I'll finish writing those in game tutorials as they are going to do the best job at introducing to different windows and functions imo. It's the matter of writing text now :) . Maybe with F2P traffic will increase .. who knows. For now the project shall grow :)

**Comment by Hysteriana** [comment]
"I'm having my driving course right now"

you should not be on your phone while driving :D

**Comment by Drutol** [comment]
Shh... I'm in incognito mode :D

**Comment by Drutol** [comment]
A bit unrelated but ... https://www.youtube.com/watch?v=NL0uG7F6GuA&ab_channel=Ubisoft . I'm sooo hyped... it's beyond words :D , back to work now xd

**Comment by Drutol** [comment]
Ads are gone , (I'll remove the one in member's page today , I forgot about this place :))
