### ISSUE TITLE
Bug : v2.15 : WebPage Upload

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#217]
did export upload with v2.15 after i did the weekly decay and got this message:

" no implicit conversion of String into Integer "

**Comment by Drutol** [comment]
Can you sand me this data?

**Comment by Hysteriana** [comment]
you got mail :)

**Comment by Hysteriana** [comment]
looks like that upload fucked something up, cause now all data seem gone

**Comment by Drutol** [comment]
Try now

**Comment by Hysteriana** [comment]
looks good it's working

gesendet vom Handy.
Autolorektur hat Schuld :)

**Comment by Drutol** [comment]
btw can you visit this Y-83 raid?

**Comment by Hysteriana** [comment]
was with random last time, will ask guild if we may visit it this id..
anything specific you need ?

2015-06-09 8:52 GMT+02:00 Mordonus notifications@github.com:

**Comment by Drutol** [comment]
Just the screenshot with id :)

**Comment by Hysteriana** [comment]
done in original issue

https://github.com/Mordonus/RaidOps/issues/211

**Comment by Drutol** [comment]
Ty
