### ISSUE TITLE
Bug : v2.0 ref 130 : Lua Error : Import option

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#22]
just for the record, import of fresh exported database still does not work

...ming\NCSOFT\WildStar\Addons\EasyDKP\libs/Serpent.lua:133: attempt to call a nil value
stack trace:
    ...ming\NCSOFT\WildStar\Addons\EasyDKP\libs/Serpent.lua:133: in function 'load'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3081: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3037>

**Comment by Drutol** [comment]
I exported about 10 databases , all of which exported correctly. What's happening...

**Comment by Hysteriana** [comment]
the export isnt the import :) the import is ^^ get this lua error everytime i try to reimport the fresh export

**Comment by Drutol** [comment]
By exporting I mean exporting and importing xd.

**Comment by Hysteriana** [comment]
did fresh install rev 131 and filled the database again.
so fare export / import works,.
will test again tue, wed and thu after the raid.

**Comment by Drutol** [comment]
Till then I'm closing this.
