### ISSUE TITLE
Bug-ish : v2.16 : Attendance Setting (3) o_O :D

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#220]
Setting stays on Day now, but chat is flodded by "Debug : table"

Also, what is this "allow popup window" supposed to do ? have it active but being in raid now, i havent noticed any popup yet,

**Comment by Hysteriana** [comment]
edit... that "debug : table" is spamming when ever i switched window ^^

**Comment by Drutol** [comment]
It should appear when you enter raid zone ,  Fixed v2.16b

**Comment by Drutol** [comment]
Fixed pop-up in next update.
