### ISSUE TITLE
Bug : v2.15 : Lua Error : Loot Rooster

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#221]
when click on "open loot log for whole rooster"

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6104: attempt to compare nil with number
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6104: in function 'LLMeetsFilters'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6073: in function 'LLPrepareData'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6257: in function 'LLPopuplate'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5983: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5977>

**Comment by Drutol** [comment]
Fixed v2.16b
