### ISSUE TITLE
Request: Webpage : More than just 14 Log Entries.

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#222]
everytime i make an update, die data from the addon overwrite the data on the page.
it would be much better, if the new data would just be added.
sometimes its difficult to find mistakes or errors, if you have only the last 14 log entries.
cause a single raid evening could produce already more.

**Comment by Drutol** [comment]
Hmm I can set this limit higher as we have plenty of space.

**Comment by Hysteriana** [comment]
as in unlimited space :) 
log for at least 30 days would be neat :+1:

**Comment by Drutol** [comment]
I have added that , 30 days and they are gone. Let's see how will this work.
