### ISSUE TITLE
Bug When Zoning Into GA

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#223]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1176: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1176: in function 'Bid2PackAndSendPrivate'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1192: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1181>

**Comment by Drutol** [comment]
Wat , the same bug over and over...

**Comment by Drutol** [comment]
Which version are you running? There's nothing at line 1176...

**Comment by Larnen** [comment]
Believe it was 2.15, although i update this every new push so may have been 2.14

**Comment by Drutol** [comment]
2.14 was the version you reported the same bug :)
