### ISSUE TITLE
Bug : v2.16 : Webpage import to addon

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#224]
for me nothing happened when i try to import from webpage.
guild mate got lua error. will ask him to post it here

**Comment by Drutol** [comment]
With v2.16 export has slightly changed make sure that he is using the newest version

**Comment by ZoyaYurijan** [comment]
Hey there, I am said guildmate. Downloaded version 2.16a today, can't import from the webpage. 

Lua Error:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3927: bad argument #1 to 'ipairs' (table expected, got nil)
stack trace:
    [C]: in function 'ipairs'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3927: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3857>

Newest version, 2.16b, another Lua Error

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3926: bad argument #1 to 'ipairs' (table expected, got nil)
stack trace:
    [C]: in function 'ipairs'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3926: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3856>

**Comment by Drutol** [comment]
Oh , fixed v2.16c
