### ISSUE TITLE
Bug : v2.16 : Raid attendance 

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#226]
we were DS today, and i tested the attendance.
now some ppl have 100% total but the DS tab is still empty

**Comment by Drutol** [comment]
Send me .xml file with db. Any resumes during raid?

**Comment by Drutol** [comment]
Oww I see what's wrong , fixing.

**Comment by Drutol** [comment]
I have fixed this export string for you : http://pastebin.com/4Z5vkLSY .
