### ISSUE TITLE
Bug : v2.16c : Webpage import to addon

### ISSUE THREAD

**Issue by ZoyaYurijan** [Mordonus/RaidOps#229]
Even after your update (thanks for the insanely fast work by the way!) the problem still remains. It actually might be a issue with our guilds (VII) record and/or the total lenght of the import, since I had no problem importing data from the other guilds on the website (solely for testing purposes). Importing 64k characters from Conclave of Darkness works just fine, whereas trying to import 73k characters from our data just gives me this lua error.

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3929: bad argument #1 to 'insert' (table expected, got nil)
stack trace:
    [C]: in function 'insert'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3929: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3851>

**Comment by Drutol** [comment]
I have tested import of your guild's db on this string http://pastebin.com/4Z5vkLSY , try this.

**Comment by ZoyaYurijan** [comment]
Okay, thanks a bunch. I made a clean "reinstall" of RaidOps and deleted the old .xml file. 
Got it now after a few tries, but only after I clicked "Exactly the same as in main window" in the Import/Export settings. Isn't this supposed to be an Export-only setting? I've no idea why, but without using this, it won't work for me. "EPGP", "DKP" and "Website Export" did nothing for me, the UI did reload but I didn't get any data. Using none of the settings gave me the same lua error as mentioned earlier.

**Comment by Drutol** [comment]
That's odd... all you have to do is select "Import database" and press "Export/Import" button. I'll check this

**Comment by ZoyaYurijan** [comment]
I know, did it more than once the "normal" way before. I watched carefully that I did not exceed the ~30k character limit when copying from pastebin and double checked everything. 

I'll make more tests after today's raid with the new data. Let's hope it is a mistake on my side and not some strange carbine-data-sharing-thingy.

**Comment by Drutol** [comment]
It's not carbine's fault here , something behaves oddly and I need to find the source.

**Comment by Hysteriana** [comment]
i saw enough movies to know that this is how the zombie Apocalypse is about to begin.

**Comment by ZoyaYurijan** [comment]
Still getting lua errors when trying to import from the webpage. Import's working tho. I got all the data.

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3929: bad argument #1 to 'insert' (table expected, got nil)
stack trace:
	[C]: in function 'insert'
	...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3929: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3851>
