### ISSUE TITLE
Bug : rev131 : Guild Import does not work while Filter Account Creation active

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#23]
No LUA Error or such but nothing happens when i click Import.
i figured it was the "filter account creation" enabled that prevented the guild import.

**Comment by Drutol** [comment]
Odd , will investigate.
Just btw , can you label issue by yourself or is it just me allowed?

**Comment by Hysteriana** [comment]
i dont see any lable options

**Comment by Drutol** [comment]
K , good to know :)

**Comment by Drutol** [comment]
Fixed in rev 132.
