### ISSUE TITLE
Bug When Opening Loot Logs

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#230]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6102: attempt to index local 'tTimeWindow' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6102: in function 'LLMeetsFilters'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6045: in function 'LLPrepareData'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6256: in function 'LLPopuplate'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5973: in function 'LLOpen'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4734: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4733>

**Comment by Drutol** [comment]
Fixed v 2.17
