### ISSUE TITLE
Bug: v2.16 : Attandance PopUp

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#231]
Clicking on No starts the Timer too :D

**Comment by Hysteriana** [comment]
this also leads to micro sessions,
i have 3 raid sessions today, 2 of them only 1-2 sec long.
maybe a filter to discard session < X min. ?

**Comment by Hysteriana** [comment]
or maybe option to delete sessions before the upload.

**Comment by Drutol** [comment]
Both options sound nice , I'll fix things today again :)

**Comment by Drutol** [comment]
Fixed and added v2.17
