### ISSUE TITLE
Bug-ish: v2.16 : Webpage Upload

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#232]
upload processing takes a while longer now, is that normal ?

**Comment by Drutol** [comment]
Now I have to cache every log , create new members , assign those logs back , check if they duplicate and finally I have to check the 30 day limit , I think I'll decrease it due to processing times. I'll also try to find a way to import in the backgrund.

**Comment by Hysteriana** [comment]
I wonder if that's all necessary. the calculation and management is already
done by the add-on. so in fact it would only need the latest info about
name ep and gp. all the history stuff is just nice to have but not really
necessary for my job as lootmaster. so if I or my backup has to download
from the page, all what's necessary is name, actual ep and gp, and maybe
the attendance and last item.

on the other side all the calculation is not really necessary for the
webpage. it's more like an archive, a log to check for errors or mistakes.
so maybe all you need is to add the latest uploaded data to the page and
then delete the same data from the add-on?  this way the add-on only has
the minimum data from upload to upload. and it will reduce the data size
for export and import and maybe that would be even small enough for sync to
work again?

gesendet vom Handy.
Autolorektur hat Schuld :)

**Comment by Drutol** [comment]
In fact , all the calculation in the addon is done "on the go" and site caches everything on import so it takes less time to load individual webpages. The reason is that the add-on has limited space and I want to use it efficiently unlike the website which has more stuff to compute but tons of space. In theory I can strip this string out of data while processed by website (logs namely as they are taking the most space) but data will again accumulate in the addon and sync won't work anyway. Something new to the TODO list ;d

**Comment by Hysteriana** [comment]
the sync problem is cause the data limit afaik ? if you have only one session to sync, it would be much less data, wouldnt it ?

and thats what i meant, let the addon do the calculation with the least amount of data as possible, while the webpage stores all the history.

**Comment by Drutol** [comment]
Hmm so why we even try to sync logs , I'm dumb... brb fixing sync

**Comment by Hysteriana** [comment]
im old school, when computers were running on 640kb ram and 20mb hdd :) 
thats why i always go with "as much as necessary and as least as possible" :)

**Comment by Drutol** [comment]
If you happen to be online we can test it

**Comment by Drutol** [comment]
https://www.dropbox.com/s/3l52b6oqt9vqsa6/RaidOps.rar?dl=0
