### ISSUE TITLE
Chat Bidding Oddity

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#233]
Every once in a while I have an issue whereby I select an item from master looter and go to chat bidding. But then item selected doesn't appear in the window where you can click to start bidding, and instead the last item auctioned is still there. This has happened maybe once a run on average ever since i had the addon, so hasn't been an issue. It can be solved by a /reloadui.

However tonight this happened on virtually every second item of loot. It may be that I was just unlucky, and I didnt reloadui every time, but instead just pasted stuff on the line myself, but for whatever reason something isnt quite right and has been that way since I first started using it.

You can click, double click, click on something else and click back etc and it doesn't change until a reloadui.

Sorry theres no actual error log, but no error is thrown by it. But given the reloadui fixes it, it suggests maybe something is bugging but not being throw up.

**Comment by Drutol** [comment]
I know what you are talking about , I have already fixed this once. No idea why it came back as I did not change any code there.

**Comment by Hysteriana** [comment]
ppl need to add the version they are using.. much less confusing for mordonus...

**Comment by Drutol** [comment]
Yeah , that way I have to assume that it's the newest one ;d

**Comment by Larnen** [comment]
Yeah, I update before every raid and post right after, but yes! Version in all new posts! :)

**Comment by Larnen** [comment]
Think I may know whats causing this. At least sometimes.

When you run a bid, if you assign before you 'close' it the bidding automatically ends, gives a message like "Bidding ended early as item assigned" or the like, and correctly assigns the item. However I noticed tonight that if I did this, it would sometimes bug out like this. But if I close it fully I had no incidences of it bugging.

Its sometimes useful to just assign rather than letting the countdown tick down, although I accept waiting 5 or so seconds isnt a big deal ;)

It probably needs to either not let you assign while open, or to make it so that doing so clears the item in the same way that closing does. I can't say catagorically that this is the only ways its happening, but from my tests today I could only reproduce it this way.

Ta!

**Comment by Drutol** [comment]
I may have found the source and I'll try to test it out today.

**Comment by Hysteriana** [comment]
hill? :-)

gesendet vom Handy.
Autolorektur hat Schuld :)

**Comment by Drutol** [comment]
I'm unable to replicate this , I've even found different bug trying to do so :D I have taken some countermeasures so maybe they will be sufficient.
