### ISSUE TITLE
Bug: v2.17 : Lua Error on Assign EP

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#234]
...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:304: attempt to call method 'RaidRegisterEPManipulation' (a nil value)
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:304: in function 'EPGPAdd'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1324: in function 'AddDKP'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2215: in function 'MassEditModify'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1282: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1280>

**Comment by Drutol** [comment]
Leftovers from old module.

**Comment by Hysteriana** [comment]
just closed, or fixed too ? :D

**Comment by Drutol** [comment]
2.17a should be on curse

**Comment by Hysteriana** [comment]
:+1:
