### ISSUE TITLE
My subscription...

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#235]
Yet another month passes and F2P is still far far away , if you want to see the addon grow further you need to help me (again) . As you probably know I'm no longer playing W\* and I'm just sitting there coding stuff and rarely doing some pvp. If you are on Jabbit you can send me (Drutol Windchaser)  some plat so I can buy CREDD  if not , you can donate a few bucks towards my subsription or whatever else springs to your mind.

If you ask for revenue from ads... here it is:
![image](https://cloud.githubusercontent.com/assets/6102530/8143902/08a1a8fa-11c4-11e5-8037-6f3c2f4bce5d.png)

This is the major stuff that I want to do within next 30 days:
- Write in-addon tutorial.
- Release "RaidOps Loot Division" (oh my creativity) - completely new ML addon.
- Revive Network Bidding.
- With some leftovers buy intelligence potions for Chat Bidding.
- Add "assistant" role to the website.

**Comment by Hysteriana** [comment]
platin inc. :)

**Comment by Drutol** [comment]
Thanks! Hmm there's 30 day key available on humble bundle for 1$. What a deal :D 

It's not working ..., maybe something has broken on their end...

**Comment by Drutol** [comment]
Nope , they wrote that they didn't mean that it's sub time. damn

**Comment by Hysteriana** [comment]
yeah that became another shit storm by carbine :D
btw.. check your mail.. there may be some platin waiting for you... :)

**Comment by Drutol** [comment]
Yeah , I got 16 plat from your guild , I'm right now sitting on 20plat , short of 6 to buy credd.

**Comment by Drutol** [comment]
Haha, got 10 more and now I'm waiting for someone to fill buy order. Thanks alot!
![](http://thewritepractice.com/wp-content/uploads/2012/05/Alot-vs-a-lot1-600x450.png)
