### ISSUE TITLE
Bug: v2.17 : Lua Error on Assign Loot

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#237]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1527: attempt to index field 'ItemDatabase' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1527: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1487>
    [C]: in function 'PostOnChannel'
    ui\ChatLog\ChatLog.lua:1970: in function <ui\ChatLog\ChatLog.lua:1969>
    [C]: in function 'Event_FireGenericEvent'
    ...Addons\MasterLootDependency\MasterLootDependency.lua:448: in function <...Addons\MasterLootDependency\MasterLootDependency.lua:447>

**Comment by Drutol** [comment]
It does not appear often , does it?

**Comment by Hysteriana** [comment]
no idea, happened some min ago on the first item i assigned.
then didnt reloaded ui

**Comment by Drutol** [comment]
Added 3rd condition check , I've no idea what's this about. Fixed v2.18
