### ISSUE TITLE
Logs Vanished

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#238]
Version: 2.16 

Weird error this morning. A guildie mentioned that the website was not showing any logs from last night's raid (4 hours, Convergence 1st kill, plus 3 minibosses). Initially I thought this was a problem with the Event handling as we have not killed Convergence or the Malfunctioning Dynamo etc before tonight, but the timed awards were also missing, apart from the last one at 9:56. There had been no crashes or reloadui's. Convergence was killed at 8:30 and the raid started at 6:45 and ended at 10:30. The only log entry was Timed Award at 9:56. There should have been a Malfunctioning Battery award at 10:20ish but that may have been a typo of the boss name - I haven't checked that yet.

Looking in the addon in game, nobody has ANY logs prior to 9:56 yesterday. Everything prior to that (not just last night but ANY logs at all) for all guild members is gone. The website DOES show logs prior to last night, but not the missing ones from yesterday.

Loot logs are fine. I can't tell if the timed awards and convergence kill actually awarded EP as I don't have a record of everyone's EP from prior to the raid to check. 

Not as helpful as being able to paste an error, I'm afraid!

**Comment by Drutol** [comment]
Hmm , something like this happened to @Hysteriana a while back... It's odd one for sure. I'll try to think of the source and report if I happen to find anything...

**Comment by Drutol** [comment]
I've changed the way logs are removed so maybe this will solve the issue.
