### ISSUE TITLE
Bug : v2.18 : Realy strange datasync happening o_O

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#239]
i forgot to activate "send only to raidmember" and something weird happend.
somehow a stranger seemed to have fetched 4 times from me. but he claims that he didnt.
![strange1](https://cloud.githubusercontent.com/assets/11199863/8194917/154fbb9c-147f-11e5-8b21-4d8bdf303620.png)

**Comment by ZoyaYurijan** [comment]
Happened to me aswell. I'm confused.

![image](https://cloud.githubusercontent.com/assets/11950817/8195147/a421b07c-1480-11e5-8310-2e0146e37b37.png)

**Comment by Hysteriana** [comment]
ok lets get it together.. neither zoya nor i know this NaayaRaga..
while those fetching dates we were in DS.
look at the fetching times:

zoya: 8:42:50
43s
Hysti: 8:43:32

zoya to zoya : 27m 9s

zoya: 9:09:59
43s
Hysti: 9:10:42

zoya to zoya : 20m

zoya: 9:29:59
43s
Hysti: 9:30:42

zoya to zoya: 71m 

zoya: 10:40:59
43s
Hysti: 10:41:41

exact every 43 seconds after zoya, he alleged fetched from me

**Comment by Drutol** [comment]
Hmm, channel is global but all messages are sent in 'private' mode , 

```
        if tMsg.type == "SendMeData" then
            self.sChannel:SendPrivateMessage(tMsg.strSender,self:GetEncodedData(tMsg.strSender))
        elseif tMsg.type == "SendMeFullData" then
            tFetchers[tMsg.strSender] = nil
            self.sChannel:SendPrivateMessage(tMsg.strSender,self:GetEncodedData(tMsg.strSender))
```

I've no clue what's going on so I will just change this from global channel to guild one.

**Comment by Drutol** [comment]
@Hysteriana - when you'll be online we will have to test this and Network bidding

**Comment by Hysteriana** [comment]
im having raid now... just tell me when, and i will be there..

**Comment by Drutol** [comment]
https://www.dropbox.com/s/a7sc1a0p9c8ch5o/GuildICCOMM.rar?dl=0

**Comment by Drutol** [comment]
Should not happen as of v2.19
