### ISSUE TITLE
Bug-ish ? : v2.18 : Token and show only usable 

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#241]
not sure if its supposed to be active now, but the "show only usable class" filter still does not applies to tokens.

**Comment by Drutol** [comment]
Have you changed those trues to falses*? BID.lua 2444-2449

**Comment by Hysteriana** [comment]
nope, thought thats be default now.. will do it now

**Comment by Drutol** [comment]
It'll be once It's tested. Random low level mobs don't drop tokens sadly :(

**Comment by Hysteriana** [comment]
its 2438 - 2442 here and they are all 5 on true allready
or is it 2427 - 2432 ? but they were on true too

![bid](https://cloud.githubusercontent.com/assets/11199863/8216783/01a5269e-1539-11e5-8e2a-1e89bd82ac7d.png)

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/8216815/36cd2f38-1539-11e5-9e36-13899b55468e.png)

**Comment by Hysteriana** [comment]
ok set them to false now. next tokens inc :)

**Comment by Hysteriana** [comment]
no difference. token still shown for every one

**Comment by Drutol** [comment]
have you /reloadui ?

**Comment by Hysteriana** [comment]
sure

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/8217477/079af65a-153e-11e5-979a-3360cef17f35.png)
...

**Comment by Hysteriana** [comment]
ok removed the "locals" and did /reloadui.
next token inc :D

**Comment by Hysteriana** [comment]
with filter on, only shown to guildbank only, without filter shown to all

**Comment by Hysteriana** [comment]
resonators are shown to all too, regardless of filter setting

**Comment by Drutol** [comment]
3rd time lucky (added tPrimary in 2 places)

```
                  if string.find(tItem.itemDrop:GetName(),"Imprint") then
                        bWantEsp = false
                        bWantWar = false
                        bWantSpe = false
                        bWantMed = false
                        bWantSta = false
                        bWantEng = false

                        local tDetails = tItem.itemDrop:GetDetailedInfo()
                        if tDetails.tPrimary.arClassRequirement then
                            for k , class in ipairs(tDetails.tPrimary.arClassRequirement.arClasses) do
                                if class == 1 then bWantWar = true
                                elseif class == 2 then bWantEng = true
                                elseif class == 3 then bWantEsp = true
                                elseif class == 4 then bWantMed = true
                                elseif class == 5 then bWantSta = true
                                elseif class == 7 then bWantSpe = true
                                end
                            end
                        end
                    else
```

**Comment by Hysteriana** [comment]
ok i hope i put it in correctly :D 
one more chance of tokens tonight :)

**Comment by Hysteriana** [comment]
its working now. with filter, tokens are shown for the right classes. without for all

**Comment by Drutol** [comment]
yay! Idk what's the deal with resonators yet.
