### ISSUE TITLE
Request: Webpage : setting for shown rows.

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#242]
at the moment its 1-20 / all or all / all
would be nice to be able to set to like 1-40 / all or 1-60 / all and so on.

**Comment by Drutol** [comment]
Do you need this to be modifiable or just set value like 40 per page is sufficient?

**Comment by Hysteriana** [comment]
depends, yesterday we have been 3h in GA and i assigned ca. 50 items.
thats 2.5 pages on the page.
so if not modifiable, then better set it to 60, like 20, 60, all.
or maybe, just to torture you :D , show all of a certain date ^^

**Comment by Drutol** [comment]
Date picker you say?

**Comment by Drutol** [comment]
Added
