### ISSUE TITLE
Chat Bid Error

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#243]
v2.16, but started on an earlier version I believe.

I've been getting weird messages sometimes like this:

Fred Wrong range

Where Fred is a person on my friends list but not in the group.

Or: 

Your pvp Wrong range

This was confusing the hell out of me until I realised that it was only happening when chat bidding was open. I then realised that /rolls are reported as [System] messages. Other system messages include:

[System] Fred has come on line; and
[System] Your pvp flag will be reset in 5 minutes

So it looks like the chat bid filter is picking up a lot of stuff that isnt bids.

(This had me so confused as I had no idea which addon was doing it!)

Larn :)

**Comment by Drutol** [comment]
Fixed v2.19

**Comment by Drutol** [comment]
In English the keyword is 'rolls' , and in German? - @Hysteriana

**Comment by Hysteriana** [comment]
its /würfeln

ofc with umlaut :-D

gesendet vom Handy.
Autolorektur hat Schuld :)

**Comment by Drutol** [comment]
Umm , this word in in the System message?
'Some random würfeln 89 (1-100)'
