### ISSUE TITLE
Bug-ish / request : v2.18 : closing loot popup

### ISSUE THREAD

**Issue by ZoyaYurijan** [Mordonus/RaidOps#245]
Hey there,
we've had quite a bit of trouble yesterday (partly because some of my settings were a bit off, my fault), mostly because I cancelled the loot window for items which were given away randomly. For example, a raidmember got hands with a value of 2065GP random, which means they're free for him. I neither just accepted in the popup, because that would've cost him 2065GP, nor pressed offspec and accepted, because it wasn't for second need. Instead, I just closed the window. Now that's where the odd things happened. After uploading the data to the website, said hands showed up in the item list for 2065GP (nr.7 in the list).
http://www.raidops.net:9292/guilds/13/items_all?grid%5Bpage%5D=2
The GP were NOT added to his account, which caused heavy confusion on my side. @Hysteriana also has tested this after raid was over in Galeras to confirm the behaviour. He assigned items to me and closed the popup.
http://www.raidops.net:9292/guilds/13/items_all?grid%5Bpage%5D=
If you take a look at the first and third item in the list, you'll see that they show up for 307/430 GP. I didn't get any GP.
I'd love to have the close popup button just give away items for free, without any 1st and 2nd need or GP value interaction in general. That the item is logged is great, it just should show up as free in the list.

**Comment by Hysteriana** [comment]
good morning zoya :) but you are too late ^^
https://github.com/Mordonus/RaidOps/issues/244

**Comment by ZoyaYurijan** [comment]
Welp. Thanks a lot @Mordonus .

**Comment by Drutol** [comment]
Now if popup is skipped/closed the value will default to 0. v2.19

**Comment by Drutol** [comment]
For well being of my sanity and mental health I'm going to rewrite whole pop-up window. Update postponed to tommorow.

This code is very ancient , but surprisingly stable and not surprisingly painful to look at.

**Comment by Drutol** [comment]
Rewritten as of 2.19
