### ISSUE TITLE
Bug : v2.18 : Webpage import to addon

### ISSUE THREAD

**Issue by ZoyaYurijan** [Mordonus/RaidOps#246]
The import itself is working for me, but I'm still getting a lua error when importing from the webpage.

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3929: bad argument #1 to 'insert' (table expected, got nil)
stack trace:
    [C]: in function 'insert'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3929: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3851>

**Comment by Drutol** [comment]
Fixed v2.19
