### ISSUE TITLE
Bug-ish: v2.18 : Custom Event Convergence

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#247]
not registered again,
we got sword, hammer, frog and spider

**Comment by Drutol** [comment]
I'll look into it after I'm done with pop-up... where's butcher's knife?

**Comment by Drutol** [comment]
Guess what...

**Comment by Hysteriana** [comment]
https://www.youtube.com/watch?v=NefM2gVo9mw

**Comment by Drutol** [comment]
http://i.imgur.com/4MIyQ2K.gif

My beloved typo...

**Comment by Hysteriana** [comment]
i knew it ! :D
