### ISSUE TITLE
Bug: v2.18 : Custom Event need Raid Member refresh

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#249]
We were 18 in raid, 2 more came in, we did some miniboss in GA, custom event game only the 18 the EP but not the 2 new joined member

**Comment by Drutol** [comment]
But it takes fresh roster every time... 
- They are in main roster right?
- Were they in Raid Queue previously?

**Comment by Hysteriana** [comment]
they are normal guild / raid members
they joint a bit later and were not in queue
casual event gave mini boss ep to 18, but 20 were in raid and part of the killing.

**Comment by Drutol** [comment]
The data is pulled straight from group API , report if reoccurs.
