### ISSUE TITLE
Custom Labels Error 

### ISSUE THREAD

**Issue by killa78** [Mordonus/RaidOps#25]
Pass / Etc change's the label of the "Mainspec" button, rather than pass/offspec.

**Comment by Drutol** [comment]
Hello , can you give me a little more details? Screenshot would be the best :). Welcome aboard!

**Comment by killa78** [comment]
No problem, heh (Tsulong here btw!) ;) 

[Here show's the link between  input and the  label](http://i.imgur.com/MoAORw0.png)
[Here show's them with data being set.](http://i.imgur.com/mL7Penx.png)

**Comment by Drutol** [comment]
Turned out to be a typo. Fixed in rev 132.
