### ISSUE TITLE
Bug: v2.18 : involuntary skipped loot assign popup

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#250]
in the past, sometimes the loot assign popup got skipped for no reason.
today it happened again with a token.
this time i got a little more infos.

i gave zoya the head of ohmna by random assign.
the next item was the token with chatbidding.
it was also zoya who won it with !1.
when i clicked on assign in the chatbidding window,
the popup didnt show.

**Comment by Drutol** [comment]
Pop-Up is currently being rebuilt from scratch so it should be taken care of.

**Comment by Drutol** [comment]
Rewritten , may reoccur or may not.
