### ISSUE TITLE
Bug-ish: v2.18 : Multi Random Assign causes popup

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#251]
tried to assign multiple items for random. i selected the items, clicked random, then assign.
first item went ok, but the next item triggered the assign popup.

btw would it be possible to auto random assign all selected items one by one ? and not to assign all items to the same person ?

**Comment by Drutol** [comment]
There are going to be filters so signs , patterns and other trash will be distributed instantly. Consider it fixed with 2.20*

EDIT : not 2.19 but 2.20 , 2.19 is pretty big already , and I don't want to hold all changes back.

**Comment by Drutol** [comment]
I think I'll have to include 'Random Pool' from new addon to existing implementation.

**Comment by Drutol** [comment]
I somehow always skipped this issue... fixed v2.22
