### ISSUE TITLE
Bug: v2.18 : Webseite Log Upload problem : Missing Log Entries

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#252]
we continued GA today. startet with convergence, 4 miniboss, ohmna, also we got start and break ep
start and break were added manually by me, all 6 bosses by custom event.
it was all logged in recent activity, but none of it is in the personal logs.
then we moves to DS, killed 3 minibosses and raid end.
raid and added manually by me, the 3 mini bosses by custom event.
the complete DS part has been logged to recent activity AND personal logs as supposed to.
now when i uploaded the data to the page, there is also the complete GA part missing by everyone.

in regard to https://github.com/Mordonus/RaidOps/issues/249

those 2 got the missing got the ep by custom event too, but were not part of the recent activity log name list of those 2 events.

**Comment by Drutol** [comment]
I have tweaked log removal mechanism , maybe that was the issue...
