### ISSUE TITLE
Request : v2.18 : more recent activity log entries

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#253]
now with events and loot logged in recent activity, 15 rows is not enough to cover a complete raid day from start to end. makes it difficult for review.

**Comment by Drutol** [comment]
I can increase it to 20 , but no higher because those logs are heavy as they are carrying snapshots of database.

**Comment by Hysteriana** [comment]
could it be split ? activity log / loot log ?
and what about the deleting the log after upload to webpage ? 
this way the log would only be as big as from upload to upload ?
could it not be increased this way ?

**Comment by Drutol** [comment]
Activity logs are in-addon only and they are not exported , Activity Logs = Undo Logs.

Logs , Loot Logs , Activity Logs are all different beings.

One undo log can be very very big , depending on modified entries count.( like 20k or 30k characters for all raid members' modifications).

**Comment by Hysteriana** [comment]
i see. but the upload contains it all for review ?

**Comment by Drutol** [comment]
nope , upload contains raids info (name , length and , finish time) and all players with their properties which include Loot Logs and normal Logs + non website export contains settings

**Comment by Drutol** [comment]
Btw ,  did you know that can you remove and rename raids?

v2.19 is pushed to curse , I expect new flood after this ;d

**Comment by Hysteriana** [comment]
from the attendance ?

**Comment by Drutol** [comment]
Yup

**Comment by Hysteriana** [comment]
you said the page has assistant now ? where can i find it ?

2015-06-19 12:44 GMT+02:00 Mordonus notifications@github.com:

> Yup
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mordonus/RaidOps/issues/253#issuecomment-113469688.

## 

Mit freundlichen Grüßen
Dominik Ohm

**Comment by Drutol** [comment]
There should be button "review assistants" for you , and for other registered members without their own guild button to apply for assistant on main guild's page.

**Comment by Hysteriana** [comment]
maybe im blind, but i dont see it, neither with logout or login

i even made a new account, but cant access any guild with it, if i click on more i get this:

"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."

i could register a new guild, but thats all at this moment.

if i use my main account, i get the same error if i click on other guilds more, can only click my own guild.
but if i am logout i can click the more button of all guilds.

but i dont see the "review assistants" button with neither accounts
