### ISSUE TITLE
Error on startup / reloadUI

### ISSUE THREAD

**Issue by ElmRR** [Mordonus/RaidOps#255]
Hi, since the last update I've been seeing the following error on startup / reloadui:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6482: bad argument #3 to 'JoinChannel' (Game.Guild expected, got nil)
stack trace:
    [C]: in function 'JoinChannel'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6482: in function 'DFJoinSyncChannel'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6347: in function 'DFInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:486: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:320>

I'm not able to access Data Sync or Data Sharing when clicking on them in the options (just get an error in chat advising there's been an error with the Addon). I also tried removing the addon and all saved date then reinstalling but I still get the same error.

Any suggestions / help would be appreciated incase it's me missing something obvious!!!  :)

**Comment by Drutol** [comment]
Hmm , it happened to me once , and it is caused by addon being unable to get guild you are currently in. I'll push hotfix today.

**Comment by Drutol** [comment]
Pushed hotfix to curse.
