### ISSUE TITLE
Webseite : what are the settings ?

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#256]
What do i need to enter for PR precision to get more digits ?

**Comment by Drutol** [comment]
Input 5 , reimport and you will have 5 digits.

**Comment by Hysteriana** [comment]
ah ok thx, what about the assistance settings ? cant find them anywhere

**Comment by Drutol** [comment]
hmm , there's some missing variable ...

**Comment by Drutol** [comment]
Should be visible now
