### ISSUE TITLE
Bug : v2.19 : Lua Error after DC

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#258]
...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:841: attempt to index field 'raidTimer' (a nil value)
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:841: in function 'AttPause'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:629: in function 'AttCheckZone'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:609: in function 'AttInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:500: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:320>

**Comment by Drutol** [comment]
Fixed in 2.19d
