### ISSUE TITLE
Bug: v2.19 : Lua Error on Random Loot Assign

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#259]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1569: attempt to call method 'HubRegisterLoot' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1569: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1513>
    [C]: in function 'PostOnChannel'
    ui\ChatLog\ChatLog.lua:1970: in function <ui\ChatLog\ChatLog.lua:1969>
    [C]: in function 'Event_FireGenericEvent'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2318: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2315>
    (tail call): ?

**Comment by Drutol** [comment]
Fixed in v2.19d
