### ISSUE TITLE
Bug : v2.19 : Lua Error after selecting Offspec when gp was already 0 due chat bidding

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#260]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4240: attempt to index global 'PopUpItemQueue' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4240: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4222>

**Comment by Drutol** [comment]
Typo , fixed in next update.
