### ISSUE TITLE
Webseite : No Items or Attendees on todays DS raid upload

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#261]
see title

just uploaded the short log of out todays 3 miniboss kills.
its listed correct as DS now, but has no items or attendees

**Comment by Hysteriana** [comment]
also no items at all listed for todays date. 
the personal logs are there and have the item listed too

**Comment by Drutol** [comment]
Does everything display correctly in-addon , if not something must have happened in-game.

**Comment by Hysteriana** [comment]
i think so, the recent activity log shows the EP events and listed the correct player too.
also the main spec items with GP are listed too.

**Comment by Drutol** [comment]
And raid summary?

**Comment by Hysteriana** [comment]
it is there, but if i click on member or loot from the summary menu, i get empty windows
all other logs show something

![hysteriana_doomstar 150625 220531](https://cloud.githubusercontent.com/assets/11199863/8364419/724c217e-1b86-11e5-9685-1ba5a430cd4e.png)

**Comment by Drutol** [comment]
So there is something wrong in the addon not in website.
