### ISSUE TITLE
Bug : Webseite : Manual Edit 

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#264]
when an assistant or i did a manual epgp change via webpage, the personal logs from today disappeared. when i clicked on undo, the missing log entry came back.

**Comment by Drutol** [comment]
Only some portion of logs disappeared? Did you import db again in the meantime?

**Comment by Hysteriana** [comment]
all personal entries of that day, like the 24.06 never happened :D

**Comment by Hysteriana** [comment]
you can see for your self, apply as assistant, then make a simple ep or gp edit, then look at this persons log again

**Comment by Drutol** [comment]
Fixed in next update
