### ISSUE TITLE
Upload to Website Problem

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#265]
![bug](https://cloud.githubusercontent.com/assets/12396880/8342422/d721199c-1ac3-11e5-8ff0-ce9d80816092.png)

Uploaded this to the website tonight. The website is showing Marokar and Serri as 2.0, but the rest as 1.0. Is the website rounding stuff incorrectly? Even changing the precision to 4 is still showing 2.0, 1.0 etc.

**Comment by Drutol** [comment]
Strange , on @Hysteriana 's page it works properly. I'm trying to find the reason.

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/8356055/27b6a798-1b53-11e5-954f-1552c62e1fd1.png)

Your data renders properly after import on my local machine. Have you reimported ? (PR values are precalculated during import process)

**Comment by Larnen** [comment]
Yup reimported after reading the post by Hysteriana, It seems that the pr is set at update time, rather than being a display property. Setting the pr and then importing worked fine. Slightly odd behaviour but I'm happy its working in a way its usable (and wont be a problem after 1st import!)
