### ISSUE TITLE
Upload to Website Problem

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#266]
![bug](https://cloud.githubusercontent.com/assets/12396880/8342422/d721199c-1ac3-11e5-8ff0-ce9d80816092.png)

Uploaded this to the website tonight. The website is showing Marokar and Serri as 2.0, but the rest as 1.0. Is the website rounding stuff incorrectly? Even changing the precision to 4 is still showing 2.0, 1.0 etc.

![bug2](https://cloud.githubusercontent.com/assets/12396880/8342552/df3843f2-1ac4-11e5-8dc2-1259198e7272.png)

This is the website that's based on an export from the above.

**Comment by Hysteriana** [comment]
set setting, then upload again, then you get it.
see here:
https://github.com/Mordonus/RaidOps/issues/256

**Comment by Larnen** [comment]
Fixed after reimport. Not sure why there are 2 tickets for this!
