### ISSUE TITLE
Small change of upload habits...

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#267]
I'm coming to the conclusion that I'm pushing things to early , which results in tons of problems and inconveniences. Lesson learned and now I'm going to take more time with next updates and release beta/alpha versions if needed. Before I start adding new stuff I'll go back and repair what needs repairing.
I'm sorry.

**Comment by Renira** [comment]
Beta/alpha versions are probably a good idea for just-in-case "oh shit" moments. You're doing awesome!

**Comment by Drutol** [comment]
Hah , v2.19 was pretty big and later on I was wondering which suffix version letter I'm going to reach. Fortunately there was only 'd' ^^. v2.20 does not bring anything major so I'll just spend more time testing it on my own.
