### ISSUE TITLE
Bug: GP Floor Minimum not being considered in decay

### ISSUE THREAD

**Issue by Renira** [Mordonus/RaidOps#268]
Howdy!  I just wanted to mention that our group currently has a GP floor set to 100 which functions when adding new characters, but unfortunately isn't taken into account when applying decay.  I have to manually add GP to bring people back to 100. :)  Thanks!  (Running v2.19d)

**Comment by Drutol** [comment]
This was actually changed in the past because someone wanted it to be just like it is now. I'll add option for this in v2.20.

**Comment by Drutol** [comment]
Added v2.20

**Comment by Renira** [comment]
Thanks!
