### ISSUE TITLE
Feature Request / sorta.

### ISSUE THREAD

**Issue by killa78** [Mordonus/RaidOps#27]
I was just wondering, we're trying to get this possibly setup for just "Loot Council" use without most of the EGPG/EDKP system setup, Would it be possible for you to implement a sort of "light weight" system, that just allow's Member Module (Existing) and "Loot Council" Module. That way for those of us who'd like to use it for just Lootcouncil. 

You could easily use the same setting's, however just implement it so it is "Choose Style [Loot Council / EDKP / EGPG] etc, at the base of the hub settings or something. 

My only real thing, all the option's need to be stated / setup in the same area, regardless of where they take place, Merge them all into a single config, and set it up so they are configurable there.

**Comment by Drutol** [comment]
I actually wanted to do something like this but now I want to leave "Beta" stage. There were plans to add network bidding to Master Loot addon which is already on curse but also postponed.Ultimately this will come when the foundations are stable :)
