### ISSUE TITLE
Error: Raid Session

### ISSUE THREAD

**Issue by Renira** [Mordonus/RaidOps#270]
Entered DS today with 21 members in the raid group.  I got the popup if I wanted to start a raid session.  (Using version 2.20) When I clicked yes, I received the following:

...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:839: bad argument #1 to 'lower' (string expected, got table)
stack trace:
    [C]: in function 'lower'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:839: in function 'AttStart'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:804: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:798>

**Comment by Renira** [comment]
After reloading ui, I attempted to start the raid session from the session toolbar.  I received the following error:

...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:839: bad argument #1 to 'lower' (string expected, got table)
stack trace:
    [C]: in function 'lower'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:839: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:824>

**Comment by Drutol** [comment]
Ehh , my tests do not simulate things properly , I'll upload hotfix in a few hours.

**Comment by Renira** [comment]
Thanks. :) :+1:

**Comment by Drutol** [comment]
Let's hope that it works this time. fixed v2.21
