### ISSUE TITLE
Bug : v2.21 : Lua Error on Decay attempt

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#272]
...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:487: attempt to index field '?' (a nil value)
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:487: in function <...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:447>

**Comment by Drutol** [comment]
Fixed v2.21a
