### ISSUE TITLE
Bug : v2.22 : No Start Raid Session PopUp on entering DS

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#274]
but on reloadui

**Comment by Drutol** [comment]
> /eval local tMap = GameLib.GetCurrentZoneMap() for k , id in pairs(tMap) do Print(k .. " " .. id) end

**Comment by Drutol** [comment]
Aand? Did you simply miss it or it did not show up?

**Comment by Hysteriana** [comment]
now it showed up on enter... ;/

**Comment by Hysteriana** [comment]
cant manual start raid attendance timer
new DS zone wont be recognized: 

![unbenannt2](https://cloud.githubusercontent.com/assets/11199863/8836096/d87e678e-30be-11e5-87ad-3797857f30be.png)

**Comment by Drutol** [comment]
Yup , zone is missing

**Comment by Drutol** [comment]
I've switched to strFolder in case of DS , it will be safer I suppose.
