### ISSUE TITLE
Error With Time Award

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#278]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1957: attempt to compare nil with number
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1957: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1955>

This is version 2.23 and occured when I turned time awards on. It threw an error roughly every second.

**Comment by Drutol** [comment]
Yeah I'm pushing fix right about now . It decided to work yesterday , but not today ... my luck.
