### ISSUE TITLE
Assigning from Chat Bidding

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#279]
V2.23, but also v2.22 I believe.

When you do chat bidding and someone wins the roll it (95% of the time, but not 100%) no longer allows assign from the Chat Bidding popup. Instead you have to close it and go back to the main master loot window to do the assign. GIven that this isnt sorted that can be a pain!

**Comment by Drutol** [comment]
Do you have 'Select winner automatically'  option enabled?

**Comment by Drutol** [comment]
If the answer is yes, then the possible fix is in v2.23c

**Comment by Larnen** [comment]
Hi,
Yes we do have Select Automatically set on. It seems to have been fixed in the last version as it did not happen last night.

Thanks :)

**Comment by Drutol** [comment]
Closing then. ^^
