### ISSUE TITLE
[Feature Request/Unsure if exists]: Disable "Logging popup" for assistants

### ISSUE THREAD

**Issue by killa78** [Mordonus/RaidOps#28]
After a successful loot out, to a player has completed via network bidding, disable the "Set DKP etc" popup for network assistant's, (Where you record the values set) it's more "spammy" that they do not need to deal with, as the master looter should be the only one who need's to worry about recording that data.

(I'm talking for after a piece of loot has been assigned, it pop's up on the top of the screen centered, for everyone who has the main module installed.

**Comment by Drutol** [comment]
There's a checkbox in settings for this.
