### ISSUE TITLE
Issue with Timed Awards since last update (DKP)

### ISSUE THREAD

**Issue by ElmRR** [Mordonus/RaidOps#280]
I'm seeing the following error since the last update. Seems to happen as soon as I begin the Timed Awards:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1957: attempt to compare nil with number
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1957: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1955>

**Comment by Drutol** [comment]
Fixed in v2.23b
