### ISSUE TITLE
Potential Issue with Masterloot dependancy

### ISSUE THREAD

**Issue by xeroiv** [Mordonus/RaidOps#281]
When I have this part of the addon enabled I am unable to get tooltips when hovering over items in the loot window.

**Comment by Drutol** [comment]
Q:
- Do you have EtoolTip addon?
- Do you have GP on tooltips enabled?

**Comment by xeroiv** [comment]
No to etooltip, and will have to check gp tooltip option.

**Comment by Drutol** [comment]
By loot window you mean the Master Loot window? Tooltips display everywhere else?

**Comment by xeroiv** [comment]
Yes. I can hover over the items on the ground to get them plus it doesn't
seem to effect skill tooltips and such.

**Comment by Drutol** [comment]
I'll try to push a fix for this , once I manage to get some master loot going.

**Comment by xeroiv** [comment]
I just checked the addon settings and gp tooltip was not enabled. It could
have been from the situation although it's the normal setup for our raid. I
was not the masterlooter but was marked as a raid assist. I don't know if
that helps.

**Comment by Drutol** [comment]
So we are talking about small non Master loot window?

If yes , consider it fixed.

**Comment by xeroiv** [comment]
Yes

**Comment by xeroiv** [comment]
It hasn't been a problem until some recent update. The window was titled
undistributed master loot or something to that effect.

**Comment by Drutol** [comment]
Yeah I found a small typo :D , fixed in next update.

**Comment by xeroiv** [comment]
Cool thanks for the help and keep up the great work :-)

**Comment by Drutol** [comment]
Btw , any ideas on what to add? I'm really close to depleting the pool of requests and ideas and I don't like to push such small updates ^^.

**Comment by xeroiv** [comment]
None that I can think of off the top of my head. There are a lot of great
functions built in but I will check with some of the other guild officers
to see if they had any QoL ideas to put in the pool.

**Comment by Drutol** [comment]
Hehe , pretty much only boring stuff remains , but probably project is nearing to the end after 10 months :) I'll wait for response in #279 and push it or I'll push it in a few hours regardless.
