### ISSUE TITLE
Bug : v2.23c : Lua Error on Start

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#282]
...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:770: attempt to index global 'player' (a nil value)
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:770: in function 'AttCheckReset'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:626: in function 'AttInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:526: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:341>

**Comment by Hysteriana** [comment]
had to purge database to fix it.. but after import from webpage, the lua error came again

**Comment by Hysteriana** [comment]
...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:770: attempt to index global 'player' (a nil value)
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:770: in function 'AttCheckReset'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:682: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:680>

**Comment by Hysteriana** [comment]
this and #283 are related.. after figuring this out, i updated again to v2.23c, this time with attendance set to raid sessions and no lua error now.

**Comment by Drutol** [comment]
Fixed v2.24
