### ISSUE TITLE
Bug : v2.23b : Lua Error on Setting Attendance to Days

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#283]
after going back to v2.23b and imported data from page, i was setting up the addon settings :)
when i tried to change the attandance settings from raid sessions to days, this lua error popped up:

...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:770: attempt to index global 'player' (a nil value)
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:770: in function 'AttCheckReset'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:682: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:680>

**Comment by Drutol** [comment]
Fixed v2.24
