### ISSUE TITLE
Feature Request: Multiple Raid Group

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#285]
Hi,
We currently run 2 raid groups. Our main one tracks EPGP, the second one does not. We have seen that the 2nd group gets awards triggered from events, which is fine if there is no cross over of players as we simply don't add them to the system, but increasingly we will have people who appear in both raids (not on the same week obviously), e.g. someone who cannot make the main raids will help on the alt raid.

In addition we will shortly be entering Datascape and we do not want to use the same DKP table for both raids. In effect we want to continue using GA EPGP for GA, and a separate DS tier of EPGP for DS.

Both of these could be fixed by adding a feature to allow raid to be assigned to 'groups'. And each group be maintained differently. For eg:

Group 1: GA. All settings as they are now
Group 2: DS. All settings as they are now, but separate EP and GP data from Group 1
Group 3: Alt raid. No DKP tracking

Practically it may be easier to just have an option to have different EP and GP data, and no option to have different settings as I can see that being a pain. But perhaps in the popup at the start of the raid there could be a 'Track Data' toggle so we can simply tell the addon to not track anything that session. It can be done by going it and toggling things before each raid, but its only a matter of time before something gets forgotten and the main raid misses events etc.

Thanks,
Larnen

**Comment by Drutol** [comment]
Congrats , you got me out of boredom limbo!
Tbh at some point I was working on similar thing allowing create multiple groups of members , but removed this as I could not see this being useful and stuff.

To summarize: 
- Add groups.
- Different data sets for each user.
- Option to restrict data manipulation to certain group.
- And misc QoL stuff.

It's going to be complicated both from UI standpoint and whole back-end infrastructure will require major changes ===> it will take a while. So maybe I'll add 'Anti Raid Queue' - vanish player from raid tables , it may be a temporary solution to the first part your problem.

I already have some nifty ideas for the design of this thing , it's gonna be fun!

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/8760982/64520810-2d31-11e5-90ee-bac6280c77d5.png)

My current progress , core grouping is here but I need to build mechanisms around it now.(different data sets + data manipulation restriction). If somebody wants something else related to grouping write below.

I have touched very sensitive things there so there will be beta/alpha for this.

**Comment by Drutol** [comment]
Added multiple data sets , changing active group and wrote sorting for this new grouping.

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/8772905/d7b39b38-2ec7-11e5-8cc2-831c3c7d0021.png)

Beta probably tomorrow.

**Comment by Drutol** [comment]
So , @Larnen  is that what you wanted?

**Comment by Drutol** [comment]
Added v2.27
