### ISSUE TITLE
My sub #3

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#286]
<-- insert generic 'plat for sub plz cuz i'm not playing' -->

I was going to create a post that I've no ideas / requests and there's no point in you keeping me alive apart from the hot-fixing things. Suddenly @Larnen appeared with his #285 issue and now I've hands full of work. If you want this to be implemented I'll need CREDD as only 7 days of my sub are left.
Address : **Drutol Windchaser** @ Jabbit
Or you can use this magic donate button.
[![](http://www.lagunabeachdogpark.com/images/paypal_donate_button.png)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=TZVVQTZUM6G4Y)

**Comment by Hysteriana** [comment]
whats the status ?

**Comment by Drutol** [comment]
Only got plat from you , 4 days to go.

**Comment by Drutol** [comment]
Placed an order for CREDD. Thanks!
