### ISSUE TITLE
[Feature Request]Automated Cleanup of Item's in Network Bidding UI

### ISSUE THREAD

**Issue by killa78** [Mordonus/RaidOps#29]
Item's in tab's that have been voted on / sent out already via the master looter, should be cleaned up for assistant's after the item has been given out. 

They should stay on the "same page" so to speak, as the main master looter, for example

If item a, b, c, d, e, f drop

[tab Item A], [tab Item B], ... [tab Item F].

Once an item has been "looted" it should be removed as it is no longer needed to vote etc on, The assistant's should not have to individually remove said item by there own will if it is irrelevant to the loot council / network loot. 

If the Master Looter remove's it, it should propagate to the rest of the assistants and be removed for them as-well.

**Comment by Drutol** [comment]
This can be easily done and should be present in next update.

**Comment by Drutol** [comment]
Added in rev 132.
