### ISSUE TITLE
Bug : v2.25 : Lua Error on Raid Session End

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#290]
...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:974: attempt to index field 'raidTimer' (a nil value)
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:974: in function 'AttEndSession'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:857: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:853>

**Comment by Drutol** [comment]
Fixed v2.26
