### ISSUE TITLE
Bug : v2.25 : Lua Error on Gamestart

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#291]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:308: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:308: in function 'BidCompleteInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:143: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:140>

**Comment by Drutol** [comment]
Fixed v2.26
