### ISSUE TITLE
I need some input on button usage.

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#292]
I'm trying to clean-up messy buttons on the bottom of main window. This is my idea for it:
![image](https://cloud.githubusercontent.com/assets/6102530/8742963/87618e22-2c62-11e5-918e-08b83a14e502.png)

(Ignore old buttons)

The problem is that there's not enough space for this to work. I'd like to know which buttons you are using most often and which are just obsolete. Currently there are buttons for:
- Recent Activity.
- Loot Logs.
- Custom Events.
- Raid Session toolbar.
- New grouping window.

**Comment by Renira** [comment]
Currently, I only really use the recent activity and the raid session toolbar, but I'm sort of a minimalist. :)

**Comment by Hysteriana** [comment]
recent activity to check for typos ;)
