### ISSUE TITLE
RaidOps Bug

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#293]
V2.26. Seemed a bit buggy tonight - had a couple of these when chat bidding:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:854: attempt to index field '?' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:854: in function 'BidUpdateBiddersList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:775: in function 'BidProcessMessageRoll'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:667: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:658>

**Comment by Larnen** [comment]
I should say it was on an alt not my main in case its a config setting and you're wondering why its only started today.

**Comment by Drutol** [comment]
Hmm are your members missing their class in the roster?

**Comment by Drutol** [comment]
Nvm , fixed v2.27 Beta
