### ISSUE TITLE
Beta v2.27

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#294]
Due to significant changes in the addon's core methods v2.27 will have it's own beta stage.

I've been clicking different buttons in different configurations quite a bit so maybe it won't be that bad.

Changelog:
- Added grouping mechanism.
- Added different data sets for each group.
- Added restriction to modify only certain data set.
- Added multiple display mechanisms to accomodate grouping.
- Added grouping interface to context menu.
- Added groups GUI to the bottom part of the indow ('+' button).
- Added sorting to Master Loot loot window.
- Added button to assign multiple items at random each to different person.
- Fixed LUA error concerning chat bidding (roll).
- Fixed Bug that prevented to undo guild import.

Beta 1:
Mainly it's the implementation of #285 and partly #289 + bugfix for #293 .
Beta 2:
Added #296  , fixed #295  and #297 .
Beta 3:
Fixed #298 , #301  , #299  , #300 .
Beta 4:
Fixed #303 , #307  , #274 , #304 , #308 , #309 , #305 , #310 , #302.
Added functionality to active group switch on raid enter.
Beta 5:
Added compatibility layer for external bidding calls.
Beta 6:
Added export support for groups.
Beta 6.1:
Resolved some sorting issues.

I'll be pushing bugfix updates ASAP , so check github often. :)

How those groups work:
- Setup
  - Open groups GUI using the '+' button near counter thingy on the bottom of main window.
  - Type desired group name eg. "EPGP - DS" , "EPGP -GA" etc. and press enter
  - Make sure to enable Groups Display (this works as Enable/Disable)
  - Now you should see bar(s) with specified names.
  - If you have selected drag&drop + show ungrouped , simply grab player from the list and drop him on the group's bar.Multiple players can be in multiple groups.
  - Select an active group and you are done.

Each group has its own data set , and only the active one can be modified. If player is not in group he will still get rewards. Each player has 1 EP and 1 GP (1 net and 1 tot) field which are swapped when changing data sets.

Groups are supported by sorting , class grouping etc.

If you have "Display Groups" disabled you shouldn't notice any differences.

Missing things:
- Export :star: Done!
  - Data Sets are not included as I have to figure out how I want this to be done. Currently only active group will be exported.
- Website support of groups :star: Done!
- PopUp when changing zones to switch active groups. :star: Done! (not in form of pop-up but still the same mechanism)

--------------------- Multi random assign ---------------------
![](https://cloud.githubusercontent.com/assets/6102530/8765460/f845739e-2e04-11e5-9e18-624a95d8a391.png)

There's new button in the bottom container of the ML's window (three dices).
It allows to Assign multiple items at once , each item to random recipient.

You have to:
- Enable Multi assign in ML settings.
- Select items by using check-boxes on items' bars.
- Press this new button.

Additionally loot list is now sorted , first by slot and then alphabetically. (or at least it should - need feedback)

I don't know if 'skip random winner pop-up' option will work here well. :star: Works now!

--------------------- Known issues---------------------
- Crash when removing active group. :star: Done

--------------------- Download ---------------------

![image](https://cloud.githubusercontent.com/assets/6102530/8803244/c8accec4-2fbd-11e5-9ebf-77d165227898.png)

Paste the RaidOps folder here

> %appdata%/NCSOFT/Wildstar/addons
> ![image](https://cloud.githubusercontent.com/assets/6102530/8803330/37b63c7e-2fbe-11e5-9d7a-229368e8a5a5.png)

I'll be uploading beta versions to github only, and they will appear instantly in this repository.

**Comment by Hysteriana** [comment]
nice work. exited to give it a test run

**Comment by Drutol** [comment]
Now , while you have things to do I'll make an update to ML addon. ^^

**Comment by Drutol** [comment]
Reqesting some afk assistance @Hysteriana .

**Comment by Hysteriana** [comment]
could come ingame now

**Comment by Drutol** [comment]
come then

**Comment by Hysteriana** [comment]
already waiting for you :)

2015-07-24 18:20 GMT+02:00 Piotr Szymczak notifications@github.com:

> come then
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mordonus/RaidOps/issues/294#issuecomment-124571727.

## 

Mit freundlichen Grüßen
Dominik Ohm

**Comment by Drutol** [comment]
You got dced , in case you don't know

**Comment by Drutol** [comment]
Beta 6 will be the last update with new stuff ( export support for groups) , after this I'll need somebody to say: 

> It is stable.

**Comment by Drutol** [comment]
Latest beta now on curse.

**Comment by Drutol** [comment]
Version v2.27 released on curse ...
