### ISSUE TITLE
Request : v2.26 :  EPGP Setting Profiles based on Raid

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#296]
oddly the datascape epic items have higher item power than the legendary items.
so the epics are more expensive than the legendary..
would be nice to be able to set a different custom modifier for each raid.

**Comment by Drutol** [comment]
How about making it based on item power? Provided that there's difference between power levels in most cases. Making it dependent on zone is doable but more prone to errors...

**Comment by Hysteriana** [comment]
thats how its already is, isnt it ?
(itempower / quality) \* custom \* slot value
quality, custom and slot value is all 1 to us, means GP = Item Power
in GA epic item power is lower than legendary 
but oddly in DS some epic item power is higher than legendary.
so in ds lower quality epic will cost more than higher quality legendary

so basicly, in GA i need to set quality to 1 and in DS i need to set Legendary quality value lower, or epic higher.

**Comment by Drutol** [comment]
Yeah , but make the custom modifier profile based on item's source (Do DS items have always higher power than GA one?). Instead of pulling zone , I want to do this based on item itself.

**Comment by Hysteriana** [comment]
well at least the DS items have higher item level,
but im not sure if ALL DS items have higher item power than all GA items too

**Comment by Hysteriana** [comment]
ohmna legendary items have item level 68, imbuement gloves have ilvl 69
DS should be > ilvl 70

**Comment by Hysteriana** [comment]
not sure about Y-83

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/8824387/184c853c-306d-11e5-85ed-53bd9b39a323.png)

Something like this?

Added in v2.27 Beta 2

**Comment by Hysteriana** [comment]
yeah that could work :) not sure about the item lvl all the time.. is it optional ? can it be changed ?

and it is just "item level" its different than "item power level"

**Comment by Drutol** [comment]
If you set it to 0 then the formula on the left will be always used.

**Comment by Hysteriana** [comment]
good thinking

**Comment by Drutol** [comment]
Added b4
