### ISSUE TITLE
Bug :  v2.27 Beta 2.5 : Mass Edit

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#298]
While in Mass Edit mode, i cant select single player, only unselect after select all

**Comment by Drutol** [comment]
Are groups on? Did you create groups ? Did you set active group?

**Comment by Hysteriana** [comment]
didnt set anything yet, no idea what the default settings are.
just installed while already in raid :)

had to went back to curse version, since im in live raid atm :)

**Comment by Drutol** [comment]
Fixed in next beta build.
