### ISSUE TITLE
"Add to Raid" Button Adds to EP and GP

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#3]
Right now when adding X to raid by clicking the "Add to raid" button, it adds to both EP and GP. While it's true I can add specifically to EP or GP to the entire raid by selecting the raid, and then by inputting a value, checking the appropriate box, then clicking add/subtract, but that's kind of a lot of steps for something that appears to be intended to be built in already.

**Comment by Drutol** [comment]
Changed in rev 129ish
