### ISSUE TITLE
Random Lua Error when clicking an item.

### ISSUE THREAD

**Issue by killa78** [Mordonus/RaidOps#30]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2947: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2947: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2897>
    (tail call): ?
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:3145: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:3112>
    (tail call): ?
    ui\MasterLoot\MasterLoot.lua:193: in function 'OnMasterLootUpdate'
    ui\MasterLoot\MasterLoot.lua:361: in function 'orig'
    ...mpreviewimprovedex\lib\GeminiHook\GeminiHook-1.0.lua:108: in function 'OnItemCheck'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:3105: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:3104>

**Comment by Drutol** [comment]
It's probably because sometimes I cannot get your name, which I took for granted, and everything collapses.

**Comment by Drutol** [comment]
Fixed in rev 132.
