### ISSUE TITLE
Bug : v2.26 : Player Collection doesnt work

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#303]
just noticed, that it is still not working..
guild member changed her name and was not in rooster, had to import from guild first.

**Comment by Drutol** [comment]
Do you have filtering turned on? I just spotted some legacy code.

**Comment by Drutol** [comment]
Fixed b4

**Comment by Hysteriana** [comment]
yes have filtering on since I want guild members only added automatically

**Comment by Drutol** [comment]
Make sure they have their nameplate affiliation set to your guild's name , no workaround here.

**Comment by Hysteriana** [comment]
hmm thats a Problem.. how about a warning on enter raid zone if raid size
is unequal roster size without a potential bench queue ?

**Comment by Drutol** [comment]
Tbh we can skip this auth thingy while in raid I suppose. I'll just add one more check-box to skip auth while in raid.

**Comment by Hysteriana** [comment]
hmm I don't know. I guess there is no harm in adding guest raider to the
database

**Comment by Drutol** [comment]
Or I can just run guild import in the background when entering raid.

**Comment by Drutol** [comment]
Or wait , there may be workaround.
