### ISSUE TITLE
Bug :  v2.27 Beta 3 : Lua Error : Groups Window

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#305]
clicked the x right of EPGP - GA and got this:

...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1179: attempt to index field 'tDataSets' (a nil value)
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1179: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1177>

**Comment by Hysteriana** [comment]
so cant delete groups

**Comment by Drutol** [comment]
I know this , I have even pu this in known issues ^^.

**Comment by Drutol** [comment]
Fixed b4
