### ISSUE TITLE
Bug-ish :  v2.27 Beta 3 : Groups Window

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#306]
adding new group replaced default first group

**Comment by Drutol** [comment]
There's no default group. There was one earlier though.

**Comment by Hysteriana** [comment]
I had the group epgp - ga already the first time I opened the settings

**Comment by Drutol** [comment]
Maybe leftover from previous beta.

**Comment by Drutol** [comment]
I have added some additional checks just in case.
