### ISSUE TITLE
Bug :  v2.27 Beta 3 : Main Window Groups disapear on drag & drop

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#307]
tried to drag&drop an ungrouped player into a group and then the groups disappeared

**Comment by Drutol** [comment]
I'm unable to replicate this one..

**Comment by Hysteriana** [comment]
only happened the first time so far. maybe an onetime bug

**Comment by Drutol** [comment]
If it happens once more open new issue and then we will start worrying xd
