### ISSUE TITLE
Bug :  v2.27 Beta 3 : Switch Grouping Mass Selection

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#308]
while in mass edit mode, you can switch select active groups and select player from both groups
then if you add ep or gp, all selected get them

player in both group get double ep this way.. 
but only in group 2

example: Player A is in Group 1 and Group 2
Player A is selected in both groups
Group 1 is the active one

i give Player A 100 ep.
Player A in Group 1 has 100 ep now
Player A in Group 2 has 200 ep now.

on click on refresh, now Player A in Group 1 has 200 ep
Player A in Group 2 has 0 ep

**Comment by Drutol** [comment]
I knew I missed a spot with Mass Edit clearing... Fixed b4
