### ISSUE TITLE
Bug-ish :  v2.27 Beta 3 : Mouse Pointer changed icon to class icon on click in main roster

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#309]
on purpose ?

**Comment by Drutol** [comment]
Fixed b4

**Comment by Hysteriana** [comment]
jeeez not even 8 am and you are spamming me with fix closed mails😱
you are a machine 😁

**Comment by Drutol** [comment]
I'm doing this while the temperatures are bearable. My productivity takes drastic hit when it's hot. ^^

**Comment by Hysteriana** [comment]
i feel ya..
