### ISSUE TITLE
Maybe that will help :)

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#312]
![azzdcnc](https://cloud.githubusercontent.com/assets/11199863/8839060/419413f0-30d2-11e5-8b57-983a9b7a1654.png)

**Comment by Drutol** [comment]
Heh , tbh I don't drink alcohol at all :)

All I can to say is that it 
![](http://rlv.zcache.com/works_on_my_machine_classic_round_sticker-r56ce1cc314be46efbe749e9c58c761d5_v9waf_8byvr_512.jpg)
(for the most part)
