### ISSUE TITLE
Idea : Small armory on website.

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#317]
What do you think about listing member's current gear/stats etc. on website? 
There was one website for this but data wasn't saved... Any use for such a thing?

This would not require an account for member to use. The data could be even pulled during raids to simplify the process.

**Comment by Drutol** [comment]
I'll post a mockup in a few hours.

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/8933850/228f0092-3545-11e5-85e4-6e1efaf4d534.png)

Data could be collected during raids and included in export string and I'd generate PINs for each user so they could update it on their own if they wish to do so.

Do you fill like I should fit there items names , or tooltips are sufficient?

**Comment by Drutol** [comment]
More finished thing : 
![image](https://cloud.githubusercontent.com/assets/6102530/8940247/1eae2d12-3569-11e5-8ca1-2cae8730ae37.png)

I don't know what to do with this empty space.

**Comment by Drutol** [comment]
v3 
![image](https://cloud.githubusercontent.com/assets/6102530/8953855/cfbdb2a8-35e1-11e5-8c05-2a93d04659fa.png)

Any thoughts?

**Comment by Hysteriana** [comment]
http://pastebin.com/pTLeGNZi
there you go :)

**Comment by Drutol** [comment]
Thanks!

**Comment by Mordonus** [comment]
Requesting afk halp!

**Comment by Drutol** [comment]
Armory is live! Armory codes can be generated by Member Module addon , main addon , and data can be gathered from raid. PINs for manual upload can be obtained from assistants / owner on website.
