### ISSUE TITLE
Bug in Chat Bidding

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#318]
New bug in v2.26

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:854: attempt to index field '?' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:854: in function 'BidUpdateBiddersList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:775: in function 'BidProcessMessageRoll'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:667: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:658>

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:854: attempt to index field '?' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:854: in function 'BidUpdateBiddersList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:775: in function 'BidProcessMessageRoll'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:667: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:658>

Happened pretty much for every item that dropped and was rolled on.

Larnen

**Comment by Drutol** [comment]
I believe that it was fixed in the first beta version. v2.27 will be probably released today.
