### ISSUE TITLE
Website Question : Do you want logs to be removed (from string) after import on website?

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#319]
Title

**Comment by Hysteriana** [comment]
YES !

all i need is the actual data, like actual EP / GP and maybe last item.
and till the next upload the undo history ofc.
but everything else, all that history stuff is nice to have, but thats what the website is for.

keep it small ingame for performance, sharing and faster uploads.

**Comment by Drutol** [comment]
So you want to remove all this stuff on export too.  Next update then.

**Comment by Larnen** [comment]
AGree, website could hold loads of historical data. The addon should really just be a capture/export module not a repository for the historical data. That does mean that the website needs tools to modify it though in the same way as the addon (change assigns, change EP/GP values) etc though

**Comment by Hysteriana** [comment]
@Larnen that would mean you have to import from the page every time to made some changes.

**Comment by Drutol** [comment]
Website is much more tricky than addon as it has an actual sql driven DB , and I don't imply that I cannot do it but I see the site as way for guild members to check their stats , what dropped last raid , and optionally somebody's gear. You can make small alterations to EP/GP/DKP , but importing back to addon is less pleasant. I'm open to ideas but I'd rather make this display platform rather than editor.

Right now I'm thinking of building item icon database as the one I was using is down and I don't know if it'll be up again.

**Comment by Larnen** [comment]
Yeah I agree. Perhaps the right thing to do is keep anything that you can't edit on the website (system logs, raid details etc) but keep anything editable in the addon still (loot assignments, roster) etc.

In other words editable data is held primarily in the addon with the website being only a mirror of it, but as soon as data becomes uneditable the mirror becomes the authoritative source. Perhaps there could be a 'cut off' window (a week say) after which loot is also uneditable and can be handed over to the website as the main source.

**Comment by Drutol** [comment]
I'm a dataminer now and website will be icon database xd. It shouldn't be that easy... where's the catch...

Back to topic: 
I don't really understand what you are trying to convey.
What I want to add:
- Add option to remove all logs.(so you can clean them after export)
- Make the website process this string and remove unnecessary parts so it's easier to import.
- Logs stay on website for 30 days.

**Comment by Drutol** [comment]
Hmm , added option to clear logs in-game after export , v2.33 Beta 2
