### ISSUE TITLE
Raid Summaries: Filter

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#320]
Hi,
When I look at previous raid summaries and click the button to show only the people present, it doesn't work properly.

Until about a week ago it would show SOME of the people (normally 4 or 5, 10 at most). As of this week it now shows a blank roster.

Running v2.27, but the raids would have been while running v2.26. Problem still existed in 2.26 too

**Comment by Drutol** [comment]
I'll look into it.

**Comment by Drutol** [comment]
Added some things here and there... maybe it'll be better now , I'll still play with that code though.
