### ISSUE TITLE
Data Rolled Back

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#322]
V2.27.

Did a raid tonight. Uploaded all the data to the website. 10 minutes later the data in the ADDON was rolled back to this time last night. There had been no relog or reloadui.

Im totally at a loss to work out why this would happen - all data for all members was rolled back. The LOGS are still there are still show the correct totals, but the main page shows wrong EP and GP (and thus Priority) numbers. The only thing I did was delete 3 members who seemed to have been automatically added to the roster by the addon. I assume it adds people it sees now instead of having to add them manually?

Actually weirder than that:

Some users have the logs rolled back too.
Other users have the correct logs, but the totals there now dont match the main page

I'm going to try and restore from the webpage, although the import into the addon is a pain.

**Comment by Larnen** [comment]
Also our raid session from 29/7 is now missing from the website after the last import.

**Comment by Larnen** [comment]
And indeed our one from the 26th. Although there is a 'blank' one for the 25th (when we had no raid)

**Comment by Larnen** [comment]
Rolled back. Went to user 'Diztrixia'. Added a 6000 GP offset. Reloadui.

His GP now shows back at the 1500 it was before the above addition, but the LOGS still correctly show the addition and the new total. Please see attached picture.

![epgp](https://cloud.githubusercontent.com/assets/12396880/8997144/f62d4ed2-3715-11e5-827e-3e1e1e91c0f0.png)

**Comment by Larnen** [comment]
Updated to v2.27a following this, but no change.

**Comment by Drutol** [comment]
Ehh , there goes beta period.

**Comment by Drutol** [comment]
Have you done anything in "Groups" window?

**Comment by Drutol** [comment]
Can you send me raw XML data from ?

> %appdata%/NCSOFT/Wildstar/AddonSaveData/RaidOps_0_Gen.xml

**Comment by Larnen** [comment]
Nothing with groups no. 

Will send the files over. Theres a RaidOps_0_Gen.xml~ file too which is a bit odd

**Comment by Larnen** [comment]
Sent via email.

**Comment by Drutol** [comment]
Turns out that one 'if' was missing ...

**Comment by Drutol** [comment]
What's strange is that ML window pops-up with your xml loaded up.

**Comment by Drutol** [comment]
Fixed that too :)

**Comment by Drutol** [comment]
It's good to check others' xmls. I'll adjust a few minor things now :D

**Comment by Larnen** [comment]
Oh yeah I saw the ML window popup. It always used to pop up and then vanish immediately. Ive had to manually close it since 2.27. Was going to leave that one for now as only minor and ive dropped enough things on you for one day ;)

**Comment by Drutol** [comment]
Such small thing usually require one line to fix. Bugfixes are really relaxing ^^. Provided it's not chain of bugs.
