### ISSUE TITLE
Black Bar on Website

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#323]
There is now a MASSIVE black bar at the top of the website that masks some of the content behind. It's not adblock specific as ive tried with that on and off. Seems to have appeared this morning?

**Comment by Drutol** [comment]
Wut

**Comment by Drutol** [comment]
ohh the thing scales in a wrong way

**Comment by Drutol** [comment]
It'll now start collapsing below 1250px width.

**Comment by Larnen** [comment]
Ta :)

**Comment by Larnen** [comment]
Has that update been pushed? Its still about 20-25% of my screen on my old 1280x1024 monitor?

**Comment by Drutol** [comment]
I couldn't have do anything with margins and stuff so I shamelessly used &nbsp as a solution. Some bootstrap navbars magic. I have removed more of them now :)

**Comment by Larnen** [comment]
Hmm, still looks like this:

![untitled](https://cloud.githubusercontent.com/assets/12396880/9007330/22b7670e-3788-11e5-9c6b-336c4a7e388d.png)

Which is a bit excessive!

**Comment by Drutol** [comment]
Pushed 5 secs ago

**Comment by Drutol** [comment]
Now the threshold value is 1230px of width.

**Comment by Larnen** [comment]
Ok thats fixed it. Still bigger than it could be, but no longer a wall of darkness :)

**Comment by Drutol** [comment]
I need to figure out what to do with those More and Edit buttons

**Comment by Larnen** [comment]
Yeah, it all looks fine on my 2560x1440 display, but all scrunched up on my 1280x1024. Ive attached a pic of it on both:

1280x1024
![1024](https://cloud.githubusercontent.com/assets/12396880/9007406/cd6e3bfa-3788-11e5-9023-cdd025165e59.png)

2560x1440
![1440](https://cloud.githubusercontent.com/assets/12396880/9007408/d627c7b6-3788-11e5-90fc-62aec646f97a.png)

**Comment by Drutol** [comment]
That's a big display you have there. ^^
I'm off now to deal with missing data , it's far more crucial.

**Comment by Drutol** [comment]
At least this adblock notice helped , views are now equal to the ones from from the whole previous day.
