### ISSUE TITLE
Vacation!

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#324]
I'm leaving on 8th of August for my Vacation! Idk whether I'll be able to do anything from there , probably some minor stuff.

That being said my sub ends around 21st... only 2 more months to F2P though ^^ 

I've somehow dropped http://www.jabbithole.com/items/dominion-red-dye-29007 from blue dye daily reward container ,so maybe somebody would like to buy it so I can buy CREDD , there would be 18 (I currently have 1 plat ;d) plat missing considering current prices.

**Comment by Hysteriana** [comment]
do you have a credd left to be able to reactivate your account after your vacation?

**Comment by Drutol** [comment]
Nope , waiting for f2p / beta.

**Comment by Drutol** [comment]
I'll be pushing bug fixes like yesterday's ones.  If some disaster happens I always have 10 days of trial.

Btw can you check whether mass edit works now with github update?
