### ISSUE TITLE
GP Base Value

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#326]
In the EPGP settings there are values for Min EP and Base GP. Both of these act as default values for new people, and a value to which EP and GP cannot decay below.

When we raid we award EP in 3 ways:

1) A "signed and on time" bonus of 100-150
2) 100 EP per hour of raiding
3) A set amount per boss kill ranging from 25 for minibosses up to 500 for Ohmna

When we started out, we set a base GP value of 1500 to avoid that problem whereby a new person has low EP but near zero GP and thus a priority that is crazy high. For eg 200 EP from a raid and a base GP of 1 would be priority 200, whereas most people settle to a value around 1.0 over time. When we started we were earning around 500 EP a raid, so the initial priority was (500 base + 500 raid) / 1500 = 0.66.

We've just added our 1st new joiner to our core raid team for a while, and we are now earning around 4000 a raid due to doing a near full clear. This has meant that after one raid, this new person was a priority of (500 base + 4000 raid) / 1500 = 3.0. Straight to the top of the priority table.

Of course we can fix this by adding a 'new joiner GP value' so that they're starting at about the same 0.66. Of course this means that new joiners are being charged for something that existing players weren't which is perhaps a bit unfair. However I wonder if a better solution is a change to how the GP offset works.

At present if you change the GP offset it has no effect on existing players and only sets a default level for new players. It's also not clear if the base level for each player is the base value NOW or the base value when they joined.

What I'd like to see is a slight change to how this works. Instead of a default value for new joiners, could we change it to a straight offset. So that it has no direct effect on peoples REAL (actually spent) GP. What I mean is this:

GP = Real GP + Offset (base GP)

We already decay Real Gp separately from the displayed GP so there is a concept of this separation already and may make this rather easier. What this would mean though is that we could tweak this value and it would apply to everyone equally. Everyone has the same offset irrespective of how much raiding they've done, although obviously the impact of that is higher on new folk with not as much EP. As EP inflation goes up due to faster clears this value could be tweaked up to keep the same ratio constant (manually, not suggestion that this is auto) without getting discrepancies between people before and after that tweak.

Any thoughts? As mentioned we can just add offsets to each new joiner based on EP averages at the point they join, but having  the Base GP (and possibly the Base EP) being offsets from the raw values  may be simpler, more intuitive and help reduce manual edits for new folk.

Larnen

**Comment by Drutol** [comment]
So , all I have to do is to add / subtract difference between new BaseGP and old BaseGP to the  players 'GP fields when it changes... right?

**Comment by Larnen** [comment]
Its more that the player doesnt really HAVE a 'GP' field. They have a Real GP one (the sum of the GP awards). And there is a system/group/raid tier wide Base GP value which already exists.

Anywhere that it asks for GP is then a display of Real Gp + Base Gp.

**Comment by Drutol** [comment]
That's gonna take a while...

**Comment by Drutol** [comment]
Wait... found some lua magic spells , gonna make this in no time...

**Comment by Drutol** [comment]
You will have to test it yourself and tell me if everything's okay with new system.

**Comment by Drutol** [comment]
Sorry that it took me so long :( , I'll push test version tommorow

**Comment by Drutol** [comment]
Damn , some complications have appeared...

**Comment by Drutol** [comment]
Done
