### ISSUE TITLE
First Kill Bonus

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#327]
Could we possibly have an option to award a bonus EP for the first time an event is triggered?

An optional tickbox and if selected a multiplier is applied to an event the first time it is seen.

For eg:

Event "Kill Prototypes" may award 400 EP.
First Kill bonus = 3.0

So the 1st time Prototypes are killed it awards 1200 EP and then 400 EP thereafter.

The event window already shows the number of times each event has been triggered so the data should already be there.

Thanks!

**Comment by Larnen** [comment]
One could argue this is a bit unfair on the people who did the 3 nights previous and then missed the kill. But changing that would be a headache. You'd need to record raids which wiped on a boss that hasn't yet been killed. And then when a bonus is applied do some kind of pro-rata amongst all the people who contributed in the past.

Eg:

Night 1: Bob, Sue and Joe spend 3 hours on new boss
Night 2: Bob, Sue and Gary spend 3 hours on new boss
Night 3: Bob, Sue and Jo spend 2 hours on boss and kill it

The 'bonus' award is 3.0, so thats 1200 in the above example. 400 is the normal kill, so the 'bonus' is 800EP.

8 hours were spent on the boss in total, so:

Bob gets 8/8 \* 800 = 800
Sue gets 8/8 \* 800 = 800
Joe gets 6/8 \* 800 = 600
Gary gets 5/8 \* 800 = 500

That said this is probably more complex than is needed :) Also can one even record time spent on a boss in any sensible way? Perhaps a 'learning boss mode' popup or something. But would mean I dont have to keep manually assigning "Ohmna learning bonuses" :) 

However putting aside this rather complex addition the concept of a bonus as per the 1st post would be really useful

**Comment by Drutol** [comment]
Hmm , 1st kill rewards are easy to do , for the second request though...

How about preset modifications? You could have a set of buttons that have certain mechanics behind them , like award raid members with this amount of EP adding this comment?

**Comment by Drutol** [comment]
Added 1st part of request in v2.28

**Comment by Hysteriana** [comment]
is this really necessary ? what if you need to reinstall oder setup again ? you would need to set the first kill too.
and the mass edit is just 2 mouse clicks away to add some optional ep in case of a bonus or stuff..

"Let us redefine progress to mean that just because we can do a thing, it does not necessarily mean we must do that thing." Federation President, Star Trek VI  :D

**Comment by Hysteriana** [comment]
"How about preset modifications? You could have a set of buttons that have certain mechanics behind them , like award raid members with this amount of EP adding this comment?"

i like that one, always doing this same stuff in raid.. grant start, break, end ep, start and end timer award

**Comment by Drutol** [comment]
I've just started adding this

**Comment by Drutol** [comment]
Codename : Action Toolbar !

It'll be more tricky than first kill though.

**Comment by Larnen** [comment]
For the first kill bonus - its a feature ive used in previous EPGP addons in wow and was a useful feature. There are a number of things that dont technically NEED to exist, but the more you can take mundane admin tasks away from the raid leaders the better. Timed awards for example - we could just remember to stop every hour and do 2 mouse clicks - its exactly the same principle.

**Comment by Hysteriana** [comment]
well imho first kill bonus is a one time operation, isnt it ? and i imagine
on a first kill you will happy to grant the bonus ep by your self :)
i know i am ^^

2015-08-03 0:17 GMT+02:00 Larnen notifications@github.com:

> For the first kill bonus - its a feature ive used in previous EPGP addons
> in wow and was a useful feature. There are a number of things that dont
> technically NEED to exist, but the more you can take mundane admin tasks
> away from the raid leaders the better. Timed awards for example - we could
> just remember to stop every hour and do 2 mouse clicks - its exactly the
> same principle.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mordonus/RaidOps/issues/327#issuecomment-127076805.

## 

Mit freundlichen Grüßen
Dominik Ohm

**Comment by Drutol** [comment]
Added v2.27d
