### ISSUE TITLE
Suggestion: chat commands for macro button use

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#328]
in regard to this https://github.com/Mordonus/RaidOps/issues/327#issuecomment-127052411

how about some chat commands which could be used with macro icons ?
this way you wont need to add extra buttons to the addon and blow up the interface or add another extra bar.

what comes to mind is something like this:

/epgp add/del/set ep/gp Name/Raid #value comment

/epgp raidsession start/stop/pause

/epgp timeaward start/stop

and maybe: 

/epgp undo (like click on undo last action button)

with this you could create your own buttons and as much of them as you need.

**Comment by Hysteriana** [comment]
*macro buttons

**Comment by Drutol** [comment]
Added v2.28

**Comment by Hysteriana** [comment]
maybe add then to the ingame addon slash command list ?

nevermind, just found the /rops help :)
