### ISSUE TITLE
Activity Log details

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#33]
Presently, the activity log just says things like, "added 103 EP/GP to 1 members". If it's just 1 member, it should tell me who that member is. Additionally, when it's something like "Add 120 EP/GP to 18 members." I would still be okay with seeing everyone who had epgp added to them, just make the activity log window scaleable. OR, while making edits/overhaul to the summary, having a logs button that shows in detail the EPGP fluctations, with a toggle for timed gains, for each member effected,  would be super sweet. Thinking about it, I actually prefer the latter.

**Comment by Drutol** [comment]
I have to admit that the current implementation is fairly simplistic and there's a lot of place for improvement in terms of UI. Today I won't be able to do anything but if everything goes well you can expect overhaul on Wednesday/Thursday. Btw , is the thing with Real GP ok now?

**Comment by Aeotoc** [comment]
Yes, it works. I just decayed earlier, and saw the "Decay Real GP" check box. Thanks for that!

**Comment by Drutol** [comment]
Changed/Added/Fixed etc. in rev 133.
