### ISSUE TITLE
Logs/Loot Logs with Groups

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#330]
Hiya,
Now im playing with groups, a couple of things that maybe should be added:

1) When looking at loot logs or logs for a raiders, show only the ones relevant to the active group. At the mo the EP and GP running totals in the logs are great, but this will get confusing with multiple groups. Or maybe add a field saying which group this log entry was relevant for, and allow a filter?

2) The Base EP and Base GP figures. Can they be varied per group in the same way the item costs are?

3) If not group is active when starting a raid, prompt for one (or none)

Larn

**Comment by Drutol** [comment]
- Logs, there should be no problem with that.
- BaseEP/GP, that would introduce some major problems in current state , I'll wait with this untill I have #326 done.
- Prompt , No problem

**Comment by Drutol** [comment]
2 :  Nvm , I have to rewrite it or it won't work anyway

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/9698851/5e109b60-53c9-11e5-98bf-9675cade72ae.png)
![image](https://cloud.githubusercontent.com/assets/6102530/9698852/6be01c0c-53c9-11e5-9b15-181e2eb4688d.png)

It'll open with filter for group in current context by default.

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/9698866/4aebd71a-53ca-11e5-90b3-d5d53772cf9b.png)

Base GP in action

**Comment by Drutol** [comment]
Done
