### ISSUE TITLE
Website Upload With Groups

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#331]
Some website upload errors with groups:

1) The precision setting is ignored. It's set to 2 but is showing 9

2) The default sort (priority) is no longer set

3) Despite the fact that the addon correctly shows the 2 groups with different EP/GP totals (I reset all the values for the new DS group). The website still shows the same for both.

On the plus side the armory import works great :)

Larn

**Comment by Drutol** [comment]
1. Fixed
2. Fixed
3. Hmm data displays itself correctly so something must be happening in addon.Can you send me your xml?

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/9043506/4277d2be-3a16-11e5-8cab-64a49704f2bd.png)

It has imported ok for me. Sorting on the other hand ... I don't know how to do this thing , the plugin used for those grids makes this hard.

**Comment by Larnen** [comment]
Just reimported the same data. Now worked fine (apart from the sorting).

Not sure what happened before. Any fixes in the last version, as that was 2 things that weren't working and suddenly started again.

**Comment by Drutol** [comment]
I've only changed precision thing.

**Comment by Larnen** [comment]
Gremlins. Will keep an eye open in case it happens again.

**Comment by Drutol** [comment]
Yeah , everything needs to be at least stable when I'm away for 2 weeks ;d

**Comment by Larnen** [comment]
I picked a good time to start playing with groups :) But assuming the missing DS loot and that odd import given identical values was a one-off, should hopefully be fine!

**Comment by Drutol** [comment]
Groups are messing things up , whatevs. Now when you'll make armory scan individual runes will be appended.

**Comment by Drutol** [comment]
I'm leaving at night from 6th to 7th of August , till then I'm able to fix stuff. Anything happens later equals doom for 2 weeks.
