### ISSUE TITLE
RaidOps LUA Error (important)

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#332]
...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1543: attempt to index local 'newDataSet' (a nil value)
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1543: in function 'ActiveGroupSwitch'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:664: in function 'AttCheckZone'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:652: in function 'AttInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:507: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:322>

This happened when doing a reloadui. 

It then shows no data at all, just 2 empty groups. Taken a copy of the RaidOps_Gen save file in case it overwrites on next logout!

**Comment by Drutol** [comment]
Mhm , disable group switch on zone change for now , I'll push update later today when I'm home.

**Comment by Drutol** [comment]
Fixed (?) v2.27e
