### ISSUE TITLE
When Exporting Importable DB is becoming too large

### ISSUE THREAD

**Issue by mpangelu** [Mordonus/RaidOps#333]
We maintain a history of our logs and it is saying that there is an error exporting larger then 50,000. But we don't have as many characters now as we originally had, so I don't know why this is an issue.

**Comment by Drutol** [comment]
Hello , I don't recall putting 50k threshold anywhere. Where has this message appared?
Can you send me your raw .xml file ? You can find it here:

> %appdata%/NCSOFT/Wildstar/AddonSaveData/RaidOps_0_Gen.xml
