### ISSUE TITLE
RaidOps Bug v2.27e

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#334]
...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1424: attempt to compare number with table
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1424: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1421>

Popped up after closing main page

**Comment by Drutol** [comment]
Got it!
