### ISSUE TITLE
Error when attempting to Add / Subtract Points in Mass Edit Mode

### ISSUE THREAD

**Issue by ElmRR** [Mordonus/RaidOps#337]
I'm seeing the below error whenever I attempt to either add or subtract points in Mass Edit mode.  Adding or subtracting points individually appears to be ok:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1389: attempt to perform arithmetic on local 'value' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1389: in function 'AddDKP'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2377: in function 'MassEditModify'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1359: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1357>

A ReloadUI doesn't seem to help at all and I've not attempted to uninstall, remove the saved data and reinstall at all yet.

**Comment by Drutol** [comment]
Damn , forgot to check that. You can use command to modify entries (/rops help) , I'll try to fix this as soon as I find computer.

**Comment by Drutol** [comment]
I've pushed update to github but I'm unable to test it (vacation and stuff) . Report whether it fixes this bug and I'll push it to curse.

**Comment by Hysteriana** [comment]
didnt have time to test it before, using 2.28b from curse now and no problems with mass add / sub.

**Comment by Drutol** [comment]
That's great , thanks.
