### ISSUE TITLE
Bug When Zoning

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#338]
Really unhelpfully I can't remember exactly what caused this. Hopefully the trace will reveal all! I THINK we may have all zoned out of GA to our houses while a stalker stealthed forwards.

...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:589: attempt to index local 'tMap' (a nil value)
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:589: in function 'RSIsRaidZone'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1048: in function 'AttRestore'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:648: in function 'AttInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:508: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:322>

Just updated to the latest version 2.28, this was prior to that so probably 2.27e?

**Comment by Drutol** [comment]
I'll (try) repair this without access to Wildstar (#337 too). I'd be grateful if you could confirm that it works :)

**Comment by Drutol** [comment]
Probably fixed in v2.28b
