### ISSUE TITLE
Removing Member Destroys Groups

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#339]
Hiya,
Had this problem with 2 separate people now so can confirm its consistent.

If you remove a player from the roster, all the groups you have created get destroyed, and if you have different dkp in each (which you almost certainly will), then one set gets lost.

We have 2 members we are trying to remove:

1) Lola Mara who has had an ingame rename to Mina, but as she joined raid while the guild roster hadnt updated she now has 2 entries. If i try and remove Lola the problem above occurs.

2) Déxee Kariya. For some reason Raidops started showing his name as "DÃƒÂ©xee Kariya" which meant he was no longer getting DKP/events. Ive created a new entry spelt correctly which is getting the right awards, but ofc cannot remove the old one. Rename also did not work for him.

**Comment by Drutol** [comment]
Nothing I can do for next 2 weeks :( . Provided that there will be f2p beta.

**Comment by Larnen** [comment]
Yeah don't worry :) I'm accumulating things for you when you're back ;) For now Im working around it :)

**Comment by Drutol** [comment]
Fixed v2.31
