### ISSUE TITLE
Bug-ish: v2.28 : Loot Assign seem laggy also still skipped epgp popup

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#342]
sometimes i need to click the assign button several times before the selected player will get the item.
doesn't matter if from inside the lootmaster or the chatbidding window.
also still got some missing popup windows when assigning for 2nd or 3rd.
i still thing it depends on that player got some random assigned items earlier.

**Comment by Drutol** [comment]
I'll be overhauling ML integration once I'm back. If you press button multiple times and nothing happens , this person will be injected to exceptions table multiple times, I don't check for uniqueness. Fix once I'm back.

**Comment by Larnen** [comment]
Ive seen the same issue especially in chatbid. Sometimes it won't assign at all and I have to do it from ML window (which normally seems to work). Obviously range would prevent it, but even in range and not in combat sometimes it just doesn't do anything.

**Comment by Hysteriana** [comment]
im kinda sure the new "assign multiple items random at once" is the cause.
i assign the random stuff on the fly, mostly before the real items.
and then i get a lot of skipped popups. and every skipped popup is a missing item in the loot log too

**Comment by Drutol** [comment]
Doing some plumbing now. There's small leakage...

**Comment by Drutol** [comment]
Report if v 2.31 will be any better
