### ISSUE TITLE
Website Group Display

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#343]
With no groups selected, the top of our dkp table looks like this:

Adeptus Mechanicus  24087   13095   1.84  
General Dude                    14391   8994    1.6 
Ashuan Eruai                    22892   15100   1.52  
Larnen Skyfire                  28341   18819   1.51    

If I select the GA tab we now get this:

Adeptus Mechanicus  22087.25    13095.16    1.69  
Ashuan Eruai                    22892.53    15100.86    1.52  
General Dude                    13641.53    8994.19 1.52  
Larnen Skyfire                  26141.88    18819.79    1.39

Not only is there a difference in precision for EP and GP, but the 2 figures don't match. The 'no groups' bit also is not the sum of our 2 groups (GA and DS) which was my 1st thought.

However the 1st entry (no group selected) is the one that matches the in game add for the GA group. The 2nd entry doesn't tally to anything I can see.

Larnen

**Comment by Drutol** [comment]
I cannot check what is wrong but it did work properly last time I tried.

How it works: (or is supposed to)
Each player has EP , GP field. These values are used for calculation by whole addon. There's external dictionary for each group where group specific EP , GP is stored.

When you change active group current values get stored in invisible group and swapped with new group.

The no group page displays those EP GP values of active group and all ungrouped ppl.And group tabs show this dictionary.

Have you manipulated data both in group mode and standard mode , this is where differences may have appeared.
