### ISSUE TITLE
In-game bug tracker.

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#344]
Once I'm back I'll build in-game bug tracker. It'll auto automatically collect LUA errors and apologize ^^. Each error will be neatly packaged and sent to me. At least on Jabbit server... Is there anyone on Entity who would like to relay in-game reports to github?

 There would be option just to send feedback , not only errors.

**Comment by Hysteriana** [comment]
be careful.. next step: sending him 1 platin every time you are nearby a mailbox :D

**Comment by Drutol** [comment]
Set priority flags for $$$ , pay 2 win (chat bidding) , EP boosting for raid members. It's all coming along nicely. :D
