### ISSUE TITLE
Bug : v2.28 : Lua Error on Database import

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#347]
error by import via lua file

...aming\NCSOFT\WildStar\Addons\RaidOps\libs/Base64.lua:9: attempt to perform arithmetic on local 'value' (a nil value)
stack trace:
    ...aming\NCSOFT\WildStar\Addons\RaidOps\libs/Base64.lua:9: in function 'lsh'
    ...aming\NCSOFT\WildStar\Addons\RaidOps\libs/Base64.lua:54: in function 'Decode'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4238: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4133>

error by manual import per 30k chunks

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5209: bad argument #1 to 'lower' (string expected, got table)
stack trace:
    [C]: in function 'lower'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5209: in function 'AltsBuildDictionary'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4223: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4133>

**Comment by Drutol** [comment]
File : Is there stray space in the beginning of string?

> [==[ something something ]==]
> Right after [==[

If so you should remove it and you'll get the same error as in chunk import.

Import error: I'll look into it tomorrow.

**Comment by Drutol** [comment]
I'm unable to fix this remotely , fix next week :(

**Comment by Hysteriana** [comment]
could be closed, maybe make sure about that spacething. remove them from the lua file..
maybe write it like: [==[Put Your Database Here]==]

**Comment by Drutol** [comment]
I was going to do this tommorow :)
