### ISSUE TITLE
Bug : v2.28 : Lua Error on Raid Selection for MassEdit

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#348]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2717: bad argument #1 to 'lower' (string expected, got table)
stack trace:
    [C]: in function 'lower'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2717: in function 'UpdateItem'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2618: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2517>

**Comment by Drutol** [comment]
Fix in v2.28d , report if it works.

**Comment by Hysteriana** [comment]
now i get this lua error right at start or reloadui

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5210: bad argument #1 to 'lower' (string expected, got table)
stack trace:
    [C]: in function 'lower'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5210: in function 'AltsBuildDictionary'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5249: in function 'AltsInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:488: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:323>

**Comment by Drutol** [comment]
Try v2.28e

**Comment by Hysteriana** [comment]
its kinda strange.. i installed 2.28e and the start error and massedit raid selection error were gone..
then i tried to import database by lua file (and made sure aboute the stray space) and now i get this lua error again at start/reload ui:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5213: bad argument #1 to 'lower' (string expected, got table)
stack trace:
    [C]: in function 'lower'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5213: in function 'AltsBuildDictionary'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5252: in function 'AltsInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:488: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:323>

i undid the lua import file. but still got that error, even after reinstalling 2.28e ingame..
i quite wildstar, installed 2.28e again, but still get the same lua error on start

**Comment by Hysteriana** [comment]
did a database purge..
then at first i tried to import by lua file and got this:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5213: bad argument #1 to 'lower' (string expected, got table)
stack trace:
    [C]: in function 'lower'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5213: in function 'AltsBuildDictionary'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4223: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4133>

now every reloadui gets me this

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5213: bad argument #1 to 'lower' (string expected, got table)
stack trace:
    [C]: in function 'lower'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5213: in function 'AltsBuildDictionary'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5252: in function 'AltsInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:488: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:323>

**Comment by Hysteriana** [comment]
did another purge..
now tried to import database in 30k chunks

got also this: ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5213: bad argument #1 to 'lower' (string expected, got table)
stack trace:
    [C]: in function 'lower'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5213: in function 'AltsBuildDictionary'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4223: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4133>

and after reloadui this

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5213: bad argument #1 to 'lower' (string expected, got table)
stack trace:
    [C]: in function 'lower'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5213: in function 'AltsBuildDictionary'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5252: in function 'AltsInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:488: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:323>

**Comment by Hysteriana** [comment]
on the bright side... settings import worked :D

**Comment by Drutol** [comment]
Remote fixes! Yay!

**Comment by Hysteriana** [comment]
before i start typing in the ep/gp manually, do you think there will be a fix till sunday ?

**Comment by Drutol** [comment]
I'll just skip the error without fixing this bug. Check if alts will display correctly after next update.

**Comment by Drutol** [comment]
Try v2.28f

**Comment by Hysteriana** [comment]
import by lua file and mass edit select in raid works with v2.28f
what should i check about alts ? dont have any in raid atm

**Comment by Drutol** [comment]
Go to any alts window and press the button top left. Check if all entries are correct.

**Comment by Hysteriana** [comment]
seems so
![unbenannt](https://cloud.githubusercontent.com/assets/11199863/9417783/70d94498-484f-11e5-83d1-25c565ae6295.png)

**Comment by Drutol** [comment]
Ok then
