### ISSUE TITLE
Bug ? : r132 : Hub > Loot List is doesnt show anything

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#35]
see title. no items listed in the Loot List

**Comment by Hysteriana** [comment]
![lootlost](https://cloud.githubusercontent.com/assets/11199863/6471847/9ebbe948-c1ee-11e4-8c4d-8e98a4e234e8.png)

**Comment by Drutol** [comment]
Can you send me your .xml file from addon save data? This will be heavily modified with new raid summaries.

**Comment by Hysteriana** [comment]
as requested: http://pastebin.com/3u46yVSd

that is the latest one from after the raid yesterday

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/6486074/a7f729ba-c288-11e4-9eee-c4bf81423da9.png)

This is from your file , check filters in hub settings.
