### ISSUE TITLE
Add in-game bug tracker

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#355]
I still don't know how to organize this , so it'll have lower priority for now.

**Comment by Drutol** [comment]
I've come to conclusion that adding such thing is pointless...

**Comment by Hysteriana** [comment]
but whyyyyyyy :( i love to spamm you with all the bugs i find.. it gives my life purpose :D

**Comment by Drutol** [comment]
Sending bug reports concerning bug reporting seems appealing to you , doesn't it?

**Comment by Hysteriana** [comment]
:+1:
