### ISSUE TITLE
Bug : r132 : Hub > Raid Summaries > Loot > No cost for tokens

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#36]
see title: Item Token cost is shown as " xxx "

**Comment by Hysteriana** [comment]
![loot](https://cloud.githubusercontent.com/assets/11199863/6471789/48a27860-c1ee-11e4-96c0-b9007856d5cb.png)

**Comment by Drutol** [comment]
Raid summaries are being rewritten right now , the current implementation is wonky and is going to be deleted and replaced by entirely new system.
