### ISSUE TITLE
Version v3.0

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#360]
This flood of issues is a TODO list. Each issue has been assigned to the milestone which shows you the percentage of its completion.You can create your own issues that will be added to this milestone.

We gotta make a good impression on f2p crowd!

Updates will be pushed to github at first and then I'll shift to curse.

**Does anyone have spare EU f2p beta key?**

**Comment by Hysteriana** [comment]
TODO: to thin out addon database :) upload processing takes up to 15 sec already :)

**Comment by Drutol** [comment]
v2.34 will be more or less v3.0 in disguise , actual 3.0 will be available on the day of F2P release with all API changes.
