### ISSUE TITLE
Bug : r132 : Hub > Raid Summaries > Member

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#37]
Member listed with Umlauts and dont have any earned ep listed.

**Comment by Hysteriana** [comment]
![umlaut](https://cloud.githubusercontent.com/assets/11199863/6471818/6b8bb6ac-c1ee-11e4-87ff-bbff40d6de8c.png)

**Comment by Drutol** [comment]
Raid summaries are being rewritten right now , the current implementation is wonky and is going to be deleted and replaced by entirely new system.
