### ISSUE TITLE
Raidops import/export importable database failing

### ISSUE THREAD

**Issue by Shadowfax31** [Mordonus/RaidOps#371]
The addon will not allow me to create an importable database so that I can update the website with the appropriate epgp information. Or to create a backup database for my fellow guild leaders to pull from in case that I, me being the primary epgp operator, am not there. Generally when attempting to create an importable database the string is considered to long and says copy to clipboard, when copied to clipboard and applied elsewhere, say the raid ops website, it is read as invalid data. Please, I no you are busy and probably hear many complaints, I wish you could find time to fix this issue or to tell me how to get my information posted into the website for my fellow officers. Please and thank you.

**Comment by Drutol** [comment]
First of all , I'm happy to respond to all of the issues/questions so ask them without hesitation!

Back to issue , importable database can be only imported in-game in addon export window , website uses data in JSON format which can be exported using the same window but with "Website Export" radio button checked. I'm aware that it's a bit counter intuitive and I'll be redesigning this window soon.

**Comment by Shadowfax31** [comment]
Thank you I was encountering several problems when getting the information
onto the website thank you for the speedy reply and I apologize for any
inconvenience.
Sincerely

**Comment by Drutol** [comment]
Glad to help!
