### ISSUE TITLE
Undefined Error if loot was distributed from another player

### ISSUE THREAD

**Issue by Eikju** [Mordonus/RaidOps#373]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1661: bad argument #1 to 'sub' (string expected, got nil)
stack trace:
    [C]: in function 'sub'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1661: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1582>
    [C]: in function 'PostOnChannel'
    ui\ChatLog\ChatLog.lua:1970: in function <ui\ChatLog\ChatLog.lua:1969>
    [C]: in function 'Event_FireGenericEvent'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2440: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2437>
    (tail call): ?

Maybe any idea? :D

**Comment by Drutol** [comment]
Hmm it's something in German localisation.

**Comment by Drutol** [comment]
Guess what... our good old friend typo decided to show up!
Expect update on curse in a few minutes.

**Comment by Drutol** [comment]
Try v2.28g

**Comment by Hysteriana** [comment]
eikju said works :)

**Comment by Hysteriana** [comment]
btw.. the custom event list has the boss names predefined, but in english only.
shall i provide you with the german names ?

**Comment by Drutol** [comment]
There's a lot of missing localisation but I simply don't have time to do it. It's trivial to do but just time consuming.

**Comment by Hysteriana** [comment]
if its simple.. maybe tell me how to and i will comb over the code ?

**Comment by Eikju** [comment]
Yeah. I can help you, too. No problem. Just give us some strings which should be translated into German :) .

**Comment by Drutol** [comment]
Small tut:
- Open Houston
  - It's in your Wildstar installation folder.
- Open addon using houston
  ![image](https://cloud.githubusercontent.com/assets/6102530/9551154/ad672000-4daf-11e5-9952-f640093fe637.png)
- Let's find an example control
  ![image](https://cloud.githubusercontent.com/assets/6102530/9551232/21b1c244-4db0-11e5-9276-0e1f90941a11.png)
- And now , you have to create key in enUS.lua.
  I'm trying to follow this naming scheme: "#wnd[Window Name]:[ControlTextShort]"

When you create this key copy what's currently in selected control's text field and paste it like this:
L["#wnd[Window Name]:[ControlTextShort]"] = "[OriginalText]"

Now copy the key and paste it in the text field of said control but with 3x '_' before and after the key.
![image](https://cloud.githubusercontent.com/assets/6102530/9551297/8c9edd6c-4db0-11e5-8752-b89bc6522534.png)
- Go to deDE.lua and copy/paste the line from enUS.lua and translate the text
  ![image](https://cloud.githubusercontent.com/assets/6102530/9551493/d26eb23a-4db1-11e5-8ffb-b07b6bed9674.png)

We are nearly done:

Now we have to tell the addon to translate this window:
- Go to DKP.lua
  - line +/- 480
- This is what you should see:
  - 
    ![image](https://cloud.githubusercontent.com/assets/6102530/9551567/469b79d6-4db2-11e5-8f91-f7785488e816.png)

Addon is built on those modules which are initializing one after another , in this case we were changing Custom Events (CE) so we will go to function called CEInit().

As of now it's in line 5532.

You will have to add this line:

```
self.GeminiLocale:TranslateWindow(self.Locale, self.wndCE)
```

![image](https://cloud.githubusercontent.com/assets/6102530/9551729/191be4b8-4db3-11e5-9ee2-6b055067d786.png)

Done!

Once you reload this control will have translated text.

**Comment by Drutol** [comment]
Let me know if you understand.

**Comment by Eikju** [comment]
Uff... xDDD

I personally stuck at "And now , you have to create key in enUS.lua. I'm trying to follow this naming scheme: "#wnd[Window Name]:[ControlTextShort]""

**Comment by Drutol** [comment]
L[key] = string 
Key is universal and it's just a description , you can type there "pancakes" and in the text field "**_pancakes**_". This will result in changing "**_pancakes**_" to the string provided after '=' .

To keep this organized and avoid random pancakes I name them after window and control affected. Each window is called "wnd[CapitalLetters]" in most cases. By making key "#wndCE:NotifyDur" I'm stating that this is used in Custom Events + string is related to "notification duration".

**Comment by Drutol** [comment]
Damn markdown formatting , bold pancakes have 3x '_' before and after them... bold pancakes...
