### ISSUE TITLE
Bug :  v2.28f : GP Calculation is broken

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#375]
looks like something broken with the GP formula settings..

for once, left and right is switched. its supposed to be   BIGGER THAN > VALUE > SMALLER THAN
but its the other way around atm. should be " smaller or equal than < Value < bigger than "
also the value for orange quality on the left side cant be changed somehow.
its stuck with the same value you will see after a reloadui.

see picture

![1](https://cloud.githubusercontent.com/assets/11199863/9430114/8c43d78a-49e8-11e5-9c7f-c999f04c5c45.png)

**Comment by Hysteriana** [comment]
i kinda fixed it by using the 0.67 on the right side now.. and set the custom modifier on the left side to 0.67 too. the problem seen to exist for a while.. had to fix entry from 21.07

**Comment by Drutol** [comment]
I'll try to push fix for this today with new export window.

**Comment by Drutol** [comment]
Check v2.29

**Comment by Hysteriana** [comment]
v2.29 already ? what happened to h-z ? :D

2015-08-24 20:19 GMT+02:00 Piotr Szymczak notifications@github.com:

> Check v2.29
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mordonus/RaidOps/issues/375#issuecomment-134324655.

## 

Mit freundlichen Grüßen
Dominik Ohm

**Comment by Drutol** [comment]
Bigger things bigger numbers! 
If everything works on your part could you update thread on forums as sub is needed in order to post -.- ?

Thread : https://forums.wildstar-online.com/forums/index.php?/topic/124767-raidops-epgp-master-looter-enhancements-loot-distribution/page-2

Text (fill in the links):

> ---RaidOps version 2.29---
> {24/08/2015}
> Redesigned export window.
> Fixed some GP formula bugs.
> 
> Now available on [curse](http://www.curse.com/ws-addons/wildstar/224405-raidops-epgp-dkp-raid-utilities-armory-loot).
> Any kind of feedback is welcome [here](https://github.com/Mordonus/RaidOps/issues).

**Comment by Hysteriana** [comment]
im banned from that forum since beta :D but i will pass it along gladly :)

2015-08-24 20:49 GMT+02:00 Piotr Szymczak notifications@github.com:

> Bigger things bigger numbers!
> If everything works on your part could you update thread on forums as sub
> is needed in order to post -.- ?
> 
> Thread :
> https://forums.wildstar-online.com/forums/index.php?/topic/124767-raidops-epgp-master-looter-enhancements-loot-distribution/page-2
> 
> Text:
> 
> ---RaidOps version 2.29---
> {24/08/2015}
> Redesigned export window.
> Fixed some GP formula bugs.
> 
> Now available on curse.
> Any kind of feedback is welcome here.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mordonus/RaidOps/issues/375#issuecomment-134335644.

## 

Mit freundlichen Grüßen
Dominik Ohm

**Comment by Drutol** [comment]
Wut , heavy moderation?

**Comment by Hysteriana** [comment]
yeah the mods tended to suppress negative feedback. deleted post and
stuff.. i made screenshots and posted the links to deleted stuff. so they
banned me too

2015-08-24 20:53 GMT+02:00 Piotr Szymczak notifications@github.com:

> Wut , heavy moderation?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mordonus/RaidOps/issues/375#issuecomment-134337548.

## 

Mit freundlichen Grüßen
Dominik Ohm

**Comment by Drutol** [comment]
Heh , it probably will get stricter with f2p :(.

Fixed v2.29

**Comment by Hysteriana** [comment]
looks good.. just a little thing.. you can set the Quality value to zero :) which makes the result #inf :D
