### ISSUE TITLE
Bug : v2.29 : Export personal settings : Lua Error

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#379]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4413: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4413: in function 'ExportShowPreloadedText'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3731: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3730>

**Comment by Drutol** [comment]
Fixed v2.30
