### ISSUE TITLE
Request : v2.29 : Make 1st Kill award depending on Custom Event entry

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#380]
the 1st kill option has only the bosses of GA and DS, and they are hardcoded and in english.
what about optional 1st kill bonus for miniboss or other stuff ?
maybe that list should depend on what bosses and minibosses you added to the custom list ?
this way bosses could be added as units with their german names too.

**Comment by Drutol** [comment]
Actually they are half harcoded , it's all the matter of translating the window :)

Bosses will have 1st kills as they are now + German support. Events for units will have additional field for multiplier based on trigger count.

**Comment by Drutol** [comment]
Added v2.30
