### ISSUE TITLE
Bug : RaidOps Webpage : Download failed

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#382]
cant download the the database, get error: download failed
and it takes for ever to get an response

**Comment by Drutol** [comment]
It's all on separate ftp server... maybe it's something on that end. We will see tommorow.

**Comment by Hysteriana** [comment]
is that necessary ? wouldn't it be better to keep it on the same server as the webpage ?
for performance and stuff ?

**Comment by Drutol** [comment]
No it's not , but if I ever had to move to other hosting there would be no problem with this as you cannot just create random files there(in some cases at least).

I'll work on website tommorow , today addon,

**Comment by Drutol** [comment]
PTR servers are down .... let's do the website then

**Comment by Hysteriana** [comment]
great hack worked.... :D 

btw you got a ptr key then ?

**Comment by Drutol** [comment]
yup

**Comment by Hysteriana** [comment]
great

**Comment by Drutol** [comment]
So they have changed something in ftp access , and now I cannot access it.

Fixed

**Comment by Hysteriana** [comment]
Looks like this problem is back again...
