### ISSUE TITLE
Bug : v2.29 - No GP-Value for distributed item

### ISSUE THREAD

**Issue by Eikju** [Mordonus/RaidOps#383]
Heyho :).

We had today a raid. So a Item droped and I wanted to distributed it to a member. I do so but the GP-value wouldn't be show up.

So it seems that in the German version there is still a bug.

**Comment by Drutol** [comment]
It'll be hard for me to debug German vesrion...
Maybe you changed something in settings?
Is it single occurrence or you don't get pup-up window at all?

**Comment by Hysteriana** [comment]
the popup does come, but it doesnt contain the GP values... field is empty, not even a zero
we guess addon is looking for the "power level" value to calculate the GP
and german client item info / tooltip may have another trigger word or so

**Comment by Drutol** [comment]
Is there everything except GP value?>

**Comment by Hysteriana** [comment]
i think so, you can see for your self here: http://www.twitch.tv/dereikju/v/12748008
its yesterday stream from eikju, using german client and addon for lootmaster

**Comment by Drutol** [comment]
Very odd...

**Comment by Drutol** [comment]
Ok , found it. I'll push update with new logs , alts and this tomorrow as PTR is down again.

**Comment by Drutol** [comment]
Btw , can you translate a few things?

```
function DKP:EPGPGetTokenItemID(strToken)
    if string.find(strToken,"Calculated") or string.find(strToken,"Algebraic") or string.find(strToken,"Logarithmic") then --DS
        if string.find(strToken,"Chestplate") then return DataScapeTokenIds["Chest"] 
        elseif string.find(strToken,"Greaves") then return DataScapeTokenIds["Legs"] 
        elseif string.find(strToken,"Helm") then return DataScapeTokenIds["Head"] 
        elseif string.find(strToken,"Pauldron") then return DataScapeTokenIds["Shoulders"] 
        elseif string.find(strToken,"Glove") then return DataScapeTokenIds["Hands"] 
        elseif string.find(strToken,"Boot") then return DataScapeTokenIds["Feet"] 
        end
...
```

I need German names for everything in string.find(). That is "Calculated" , "Boot" etc. I'd use google translate but I don't know whether it's the same in W*.
And translation for "Imprint".

**Comment by Hysteriana** [comment]
Calculated = Berechnet
Chestplate (Chest) = Brust
Greaves (Legs) = Beine
Helm (Head) = Kopf
Pauldron (Shoulder) = Schulter
Glove (Hands) = Hände
Boot (Feet) = Füße

Imprint as in Tokens ?

In your string up there its "Shouldersssss" but ingame its just "Shoulder"

**Comment by Drutol** [comment]
Yup , in tokens.

I'm using different names than the game itself , don't ask me why.

Oh , I forgot about the strings for GA tokens... I don't remember them so I'll post them tommorow.
There are 2 missing strings: 
- Algebraic
- Logarithmic

**Comment by Hysteriana** [comment]
```
Algebraic = algebraisch
Logarithmic = logarithmisch
```

Imprint = Prägung

**Comment by Drutol** [comment]
- Xenological
- Xenobiotic
- Xenogenetic

**Comment by Drutol** [comment]
While we are at it , let's translate boses' names.

```
    ["Experiment X-89"] = {bKilled = false,nMultiplier =1},
    ["Kuralak the Defiler"] = {bKilled = false,nMultiplier =1},
    ["Phage Maw"] = {bKilled = false,nMultiplier =1},
    ["Phageborn Convergence"] = {bKilled = false,nMultiplier =1},
    ["Phagetech Prototypes"] = {bKilled = false,nMultiplier =1},
    ["Dreadphage Ohmna"] = {bKilled = false,nMultiplier =1},

    ["System Daemons"] = {bKilled = false,nMultiplier =1},
    ["Gloomclaw"] = {bKilled = false,nMultiplier =1},
    ["Maelstorm Authority"] = {bKilled = false,nMultiplier =1},
    ["Avatus"] = {bKilled = false,nMultiplier =1},

    if name == "Phagetech Commander" then tKilledBossesInSession.tech1 = true end
    if name == "Phagetech Augmentor" then tKilledBossesInSession.tech2 = true end
    if name == "Phagetech Protector" then tKilledBossesInSession.tech3 = true end
    if name == "Phagetech Fabricator" then tKilledBossesInSession.tech4 = true end

    if name == "Ersoth Curseform" then tKilledBossesInSession.born1 = true end
    if name == "Fleshmonger Vratorg" then tKilledBossesInSession.born2 = true end
    if name == "Terex Blightweaver" then tKilledBossesInSession.born3 = true end
    if name == "Golgox the Lifecrusher" then tKilledBossesInSession.born4 = true  end
    if name == "Noxmind the Insidious" then tKilledBossesInSession.born5 = true end

    if name == "Binary System Daemon" then tKilledBossesInSession.daem1 = true end
    if name == "Null System Daemon" then tKilledBossesInSession.daem2 = true end
```

(Ignore the right side)

**Comment by Drutol** [comment]
Update is more or less completed , I'm only waiting for translation.

**Comment by Eikju** [comment]
Experiment X-89 = Experiment X-89
Kuralak the Defiler = Kuralak die Schänderin
Phage Maw = Phagenschlund
Phageborn Convergence = Konvergenz der Phagengeborenen
Phagetech Prototypes = Phagentech Prototypen
Dreadphage Ohmna = Schreckensphage Ohmna
System Daemons = System-Dämonen
Gloomclaw = Düsterklaue
Maelstrom Authority = Mahlstromgewalt
Avatus = Avatus
Phagetech Commander = Phagentech-Kommandant
Phagetech Augmentor = Phagentech-Augmentor
Phagetech Protector = Phagentech-Protektor
Phagetech Fabricator = Phagentech-Fabrikant
Ersoth Curseform = Ersoth Fluchform
Fleshmonger Vratorg = Fleischhändler Vratorg
Terex Blightweaver = Terax Faulflechter
Golgox the Lifecrusher = Golgox der Lebenszermalmer
Noxmind the Insidious = Noxgeist der Hinterlistige
Binary System Daemon = Binärsystem-Dämon
Null System Daemon = Nullsystem-Dämon

**Comment by Drutol** [comment]
Big thanks! I'll push update tommorow :)

**Comment by Eikju** [comment]
You are welcome :)

**Comment by Drutol** [comment]
- Terex Blightweaver = Terax Faulflechter

Are you sure that it isn't Terex?

**Comment by Drutol** [comment]
I've pushed this update. I cannot debug German localisation , so I may have missed something ;d.
Report should anything happens.

**Comment by Eikju** [comment]
Jep, the NPC is called Terax Faulflechter  with "e" and "a" :)

**Comment by Drutol** [comment]
I got the typo there previously so it's better to make sure :)
