### ISSUE TITLE
RaidOpsUploader

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#385]
![image](https://cloud.githubusercontent.com/assets/6102530/9607004/e95d5844-50c6-11e5-8fb4-59bb7d6c8a5e.png)

How about export to website via such thing?
It would require to:
- press button in-game 
- /reloadui
- input API key (one-time)
- press upload in app

Is anyone interested in import from website in a similar fashion?

(I have spent like 2h on this so it's pretty incomplete just yet)

**Comment by Hysteriana** [comment]
i like that idea. so basically like wildstarlogger ?
doesnt even need /reloadui, it grabs it right from the clipboard.

![unbenannt](https://cloud.githubusercontent.com/assets/11199863/9607716/fb19b09c-50ca-11e5-9346-98aa71567659.png)

**Comment by Drutol** [comment]
Can do

**Comment by Drutol** [comment]
I should have something like Beta tommorow.

**Comment by Drutol** [comment]
Works... :)

**Comment by Drutol** [comment]
Things got tricky and I won't push beta today but I'm well on my way :)

**Comment by Hysteriana** [comment]
pretty sure its just a typo :D

**Comment by Drutol** [comment]
Nope , after trying tons of stuff it turned out that HTTP headers were the problem. It's the first time I'm doing such thing. ^^

**Comment by Drutol** [comment]
The thing should be up today , I have to figure out how to edit XML file + play with progress spinner :D

**Comment by Drutol** [comment]
# New version : http://www.raidops.net:9292/index/uploader

How does it work:
1. Go to your guild's page on website
2. Go to API keys section
![image](https://cloud.githubusercontent.com/assets/6102530/9664921/166a2fea-526d-11e5-90b4-0031acbdf30b.png)
3. Create new key - each key has trigger count and cooldown (60 secs for both upload and download).
![image](https://cloud.githubusercontent.com/assets/6102530/9664958/51fa559e-526d-11e5-939d-d329792801db.png)
4. Download uploader from here: https://github.com/Mordonus/RaidOpsUploader/releases (it will be there today)
5.Copy your key into the uploader
![image](https://cloud.githubusercontent.com/assets/6102530/9665000/a0fdd36e-526d-11e5-8040-7fb9fb7d25c9.png)
6. Uploading:
You can upload data either from clipboard or from addon's xml file. If you want to use xml file there will be new button near "Website Export" button in Export window. Once clicked it'll reload your your UI , and reveal this data to uploader.(next /reloadui will wipe this data). Uploader will search for data in clipboard first.
7. Downloading. RaidOps v2.32 required
**You have to log out from Wildstar , to character selection at least**. Go to uploader , press download button and wait for confirmation. Once you log in again this window will show up:
![image](https://cloud.githubusercontent.com/assets/6102530/9664896/ece10d92-526c-11e5-9cda-a99066f1b1e6.png)

This app may crash or behave oddly , report should anything happens.

**Comment by Hysteriana** [comment]
sounds promising, cant wait to test it :) and flood you with bug issues ofc :D

**Comment by Drutol** [comment]
Final testing right now

**Comment by Drutol** [comment]
Uploader is out , website is out , addon is now pushed to curse

**Comment by Drutol** [comment]
And addon is up on curse... now I'm going to close my eyes and walk away...

**Comment by Hysteriana** [comment]
dreaming of all the bugs im going to find? 😁

**Comment by Drutol** [comment]
It all seems too quiet...

**Comment by Hysteriana** [comment]
calm b4 the storm. ready 4 f2p @ 29.9?

**Comment by Drutol** [comment]
Umm , somewhat I guess? There's a lot of things to do but it seem to be stable enough. The only thing that bothers me is Master Loot and I cannot test it because they don't let me boost to 50 on PTR...

**Comment by Drutol** [comment]
And wiki...

**Comment by Hysteriana** [comment]
why need lvl 50 for ml ? Hill is lower

**Comment by Drutol** [comment]
I can kill mobs instantly + I can alt-tab myself knowing that nothing will kill me. Asking sb to kill the same mobs for a few hours seems unreasonable to me. Leveling to 13-15 lvl takes some time too.

**Comment by Drutol** [comment]
I'm thinking about changing spot to some lower level area but I'd have to convince myself to start leveling nevertheless. ;d
