### ISSUE TITLE
Bug: v2.32 : Import/Export Tool :D (you knew it would happen, didnt ya ?)

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#387]
I changed the EP of some member directly on the webpage.
just added him 100 ep.
then i logged of to char selection and clicked on download at the tool.
that worked, i logged in and got the import or wipe window.
did the import and got the reloadui, no errors so far.
but the change i made on the page, didnt show. he still got the same old ep without the extra 100 ep.

**Comment by Drutol** [comment]
Did you commit the change?

**Comment by Hysteriana** [comment]
nope, since it was my own change...

alright, problem solved then :)

**Comment by Drutol** [comment]
^^
