### ISSUE TITLE
v2.33 Beta - BaseGP overhaul

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#388]
As it was requested I finally got around to complete this thing. In theory everything should nicely convert from old format to new without changing **ANY** values.

Backup recommended.
### What I want to check : everything that affects GP value (custom events, timed awards etc.)

From Changelog:

---RaidOps version 2.33 Beta ---
{06/09/2015}
Overhaul of BaseGP system:
From now on every player has dynamic GP offset (BaseGP) and GP from awards ; GP value is the sum of these two.
Savefile format is changed and therefore you cannot downgrade versions.(Website export/import is the solution if you want to go back and you dindn't make backup).
BaseGP value in EPGP settings serves now as default BaseGP value.
Each player can have different BaseGP value in different context (group).

As this change affects very core of the addon , there will be beta period to check if things work.
Back to changelog:

Added nBaseGP , nAwardedGP field to player entry , removed GP field.
Added support for multiple BaseGP values accross groups.
Added button to set BaseGP value in Mass Edit toolbar.
Added strGroup field to logs , in order to differentiate which log applies to what.
Added filtering by logs group of origin to logs window.
Added BaseGP label.

**Comment by Hysteriana** [comment]
v2.33 is listed in curse changelog but not available for install

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/9705673/d5529ef4-54cc-11e5-9d88-ea12457d8e8c.png)

I've downloaded it without any problem

**Comment by Hysteriana** [comment]
yeah manual. its not the latest version, so it gets skipped,  thats what i ment.

**Comment by Drutol** [comment]
Oh , I had to push small hotfix.
