### ISSUE TITLE
Concept : Light Master Loot

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#389]
![mllight](https://cloud.githubusercontent.com/assets/6102530/9705944/c4be156a-54d5-11e5-8c68-b1ba5b597dca.gif)

There's always concern about the size of ML window, so how about this ultra small thing?
Each item entry has button to randomly assign it.
Clicking on it will open looters window who will be sorted appropriately.

**Comment by Hysteriana** [comment]
looks nice.. would have to see how practicable it is in raid.

**Comment by Drutol** [comment]
Idk , I'm trying different things. You are here to tell me whether it's worthy to continue as ML :)

I'll do some more of it.

**Comment by Hysteriana** [comment]
maybe with a compact ml, it could be combined with chat bidding

using ml for random items, chatbid for Main items, ml again in case
something went wrong.

one Windows less

**Comment by Hysteriana** [comment]
btw what happend to the auto distribute stuff ? it got kinda canceled by the ingame lootmaster options,
but there are still at least 10-20 items every raid i had to distribute randomly.. 
like receipts, elemental signs, and other stuff that arent wearable.

**Comment by Drutol** [comment]
Ctrl + A Ctrl + Del

Idk whether copy is lying around somewhere.

**Comment by Drutol** [comment]
Good thing is : once you put something on github it doesn't go off that easily.

https://www.dropbox.com/s/51gbojg6742ol3t/RaidOpsLootHex.rar?dl=0

If it works (it should) I can put this on curse ;d.

/ropshex to show window - I have to do some renaming

**Comment by Drutol** [comment]
The plan is : 
- Delay refactoring
- Upgrade visuals (reskin)
- Add light mode
- Add bidding queue
- I'll give you package to test
  - It'll be mainly light mode + random buttons on item bars , I won't change the current code because it would be too painful for you :D.
- After F2P releases I'll refactor this + add "Don't show in combat" etc.

This is is more or less said reskin:
![image](https://cloud.githubusercontent.com/assets/6102530/9711769/7fe3b1ea-5546-11e5-88eb-235b25e3d0fe.png)

**Comment by Drutol** [comment]
Bidding Queue : 
http://i.imgur.com/HfZTaL9.gifv

**Comment by Drutol** [comment]
Very first version for testing : https://github.com/Mordonus/RaidOps/tree/Version-3.0-Api11

It did not have anything to do with real ML , I've only created small test environment.

Sorting of players and items in Light mode is not there yet.

You can switch to light mode by pressing "feather" button in the top left corner of ML window.

**Comment by Hysteriana** [comment]
that Bidding Queue sounds nice, but i doubt it will ever work.. cause there are human involved.. stupid annoying human :D 
- 3..2..1..End... Oh i didnt see that item... i want it too
- 3..2..1.. End... Winner is X ... X: oh shit wrong item, i ment the other boots
- 3..2..1.. End... Winner is X... X: wait give it to Y, his item is worse the mine...
- 3..2..1.. End... Winner is X with Bid... X: noo i wanted it for off....

and that list goes on and on and on and on and .....

**Comment by Drutol** [comment]
I tried ^^

**Comment by Hysteriana** [comment]
i know... (pat on shoulder)... i know...(lower my head and shake it slowly in resignation)

**Comment by Drutol** [comment]
Is there any order in which you distribute items?

(sorting)
- Is Equippable
  - iLvl
    - Slot
      - Name

**Comment by Hysteriana** [comment]
all the random stuff first at once.. sign of x - eldan and stuff
then the legendary stuff if available, tokens first.
then whats left. 

one problem here.. ppl without addon see the stuff like they droped in there masterloot window.
so if they count on that "their" item will be, for example, the 3rd item, and cause the sorting its not, they sometimes misplaced a bet or missed their item

**Comment by Drutol** [comment]
Aside from adding the same sorting in member module , I don't see anything I can do anything here. Ppl are just ppl.

**Comment by Hysteriana** [comment]
custom sort order ? or like in char overview ? Helmet, shoulder, ... ?

**Comment by Drutol** [comment]
- random junk
- tokens
- Weapon , Shield etc (like in char wnd). grouped by quality

**Comment by Drutol** [comment]
What about item below purple? junk?

**Comment by Drutol** [comment]
New update with items and recipients sorting is up.(some other stuff too)

https://github.com/Mordonus/RaidOps/archive/Version-3.0-Api11.zip

Folders RaidOps and Master loot dependency go to

> %appdata%/NCSOFT/Wildstar/addons

At this point I'm waiting for somebody to say whether it works or not.

 Things to test:
- In general just check if you can assign stuff without problems.
- Random assign buttons on item bars.
- New visuals bugging out?
- Light mode switch (on/off)
  - Loot listing (sorting)
  - Recipients listing (sorting)
  - Random assign

**Comment by Hysteriana** [comment]
> What about item below purple? junk?

that wont stick due lootmaster settings. the item threshold is purple, everything below goes to round robin. (remember? thats why you discontinued the lootmaster hex)

**Comment by Drutol** [comment]
Oh right

**Comment by Hysteriana** [comment]
well thats just us.. no idea how other guilds handle loot distribution..
but our loot filtering addon settings are set to purple and above too, just in case.

**Comment by Drutol** [comment]
Umm do you have PTR installed?

**Comment by Hysteriana** [comment]
nope, but i could if necessary, ptr live in 2 weeks anyway :)

**Comment by Drutol** [comment]
Yeah but I want to have ML stuff done before F2P

**Comment by Hysteriana** [comment]
so you want me to install ptr ? then just say so :)

ok ptr installation is running

**Comment by Drutol** [comment]
Yup , install it ^^

**Comment by Hysteriana** [comment]
ok, im on ptr now with new lvl 50 char

**Comment by Hysteriana** [comment]
locked out on hill

**Comment by Drutol** [comment]
It won't be hill , head go northern wasted ;d

**Comment by Hysteriana** [comment]
cant you just make a veteran char? right where you land is a npc that
teleported me to thyad. and there was another npc that bumped me to lvl 50
and sold me DS gear.

**Comment by Drutol** [comment]
I don't have sub so he is invisible for me.

**Comment by Hysteriana** [comment]
i see

**Comment by Drutol** [comment]
Are you online?

**Comment by Hysteriana** [comment]
yes and just landed in northern wilds

Hysteri Doomstar

**Comment by Drutol** [comment]
How went GA raid?

**Comment by Hysteriana** [comment]
well could be better. we didnt used addon for GA loot, its need vs greed
now..
only DS loot will be assigned for gp in the future.
