### ISSUE TITLE
Bug : r132 : Hub > Raid Summaries > right side Overview

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#39]
Loot is shown as 0, even if the Players and Loot Tab shows loot

**Comment by Hysteriana** [comment]
![loot](https://cloud.githubusercontent.com/assets/11199863/6471806/5d7452cc-c1ee-11e4-9162-862e5dd15a28.png)

**Comment by Drutol** [comment]
Raid summaries are being rewritten right now , the current implementation is wonky and is going to be deleted and replaced by entirely new system.
