### ISSUE TITLE
Armor compare... useful?

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#390]
![image](https://cloud.githubusercontent.com/assets/6102530/9740804/e95eacea-5656-11e5-9ff4-d6dc3300da3c.png)

Would such a thing be useful?

**Comment by Hysteriana** [comment]
yeah i think so.. i guess Raidleaders would love that stuff and those ppl who update their own armory too.

**Comment by Drutol** [comment]
good , once F2P rolls out I'll add here assault/support rating :)

**Comment by Drutol** [comment]
It's live
