### ISSUE TITLE
Bug : v2.33 Beta : Light Master Loot Window pops up on start and reloadui

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#391]
see title...

**Comment by Drutol** [comment]
Umm which version you are using? I've pushed commit that disabled it right after the previous one.

**Comment by Hysteriana** [comment]
how do i know.. all it says it v2.33 beta, its what you linked here 5h ago:

https://github.com/Mordonus/RaidOps/issues/389
https://github.com/Mordonus/RaidOps/archive/Version-3.0-Api11.zip

**Comment by Drutol** [comment]
Yeah there should be no pop-ups if you download it now. I;ll switch OSes and check again.

**Comment by Drutol** [comment]
Ah yes it pops up... it shouldn't break anything though.Fixed in next update

**Comment by Hysteriana** [comment]
awww those mistrust among the nonbelievers.... :D

**Comment by Drutol** [comment]
(There was more popping stuff)
