### ISSUE TITLE
Bug : Sync Tool : Downloading gets outdated data

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#393]
Eikju just used a new api key to download / import the data.
download and import worked but he got old data from before my last update this morning.
the same with my api key.

**Comment by Hysteriana** [comment]
Update: he just tried to import manual by lua file, same result, got outdated data.

**Comment by Drutol** [comment]
Got it!

**Comment by Drutol** [comment]
Try it now (you have to reimport it)

**Comment by Hysteriana** [comment]
nope still old data

**Comment by Drutol** [comment]
Now it works

**Comment by Hysteriana** [comment]
hmmmm.. you sound skeptical :D  i will test it right away....

**Comment by Hysteriana** [comment]
i knew it.. just did the import... and the ingame addon data are not the same like on the raidops page

**Comment by Hysteriana** [comment]
![1](https://cloud.githubusercontent.com/assets/11199863/9756647/19cd01c6-56dc-11e5-9056-0e4d0c050303.png)

**Comment by Hysteriana** [comment]
some how on the page are 2x decay and one entry is labeld DS (guess leftover from the beta)

![2](https://cloud.githubusercontent.com/assets/11199863/9756825/266086fa-56dd-11e5-9a84-48eb28b59d17.png)

**Comment by Hysteriana** [comment]
i did a fresh upload. for now the data are in sync
did a import right after, epgp still in sync

i guess i was lucky, that the first import didnt work :/

**Comment by Drutol** [comment]
Yeah logs are removed if they are older than 14 days.

Sooo it works? I mean it worked for me ^^

**Comment by Hysteriana** [comment]
for now it does.. will ask Eikju to test it too, will let you know this evening.

> Yeah logs are removed if they are older than 14 days. 

not sure what has been removed since it was all at the same day.

**Comment by Drutol** [comment]
The problem was that data wasn't uploaded to ftp via API import. Now everything should be ok.
