### ISSUE TITLE
Bug : v2.33 : Lua Error on lootmaster

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#394]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2850: attempt to call method 'BidMLSearch' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2850: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2566>
    (tail call): ?
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2925: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2892>
    (tail call): ?
    ...Addons\MasterLootDependency\MasterLootDependency.lua:210: in function 'OnMasterLootUpdate'
    ...Addons\MasterLootDependency\MasterLootDependency.lua:378: in function 'orig'
    ...Addons\MailHelper\libs/GeminiHook/GeminiHook-1.0.lua:108: in function 'OnItemCheck'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2875: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2874>

**Comment by Drutol** [comment]
Typo like

**Comment by Drutol** [comment]
Fixed v2.34 Beta 1
