### ISSUE TITLE
Bug : v2.33 : Custom Event not triggerd on System Deamons in DS

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#395]
see title

**Comment by Drutol** [comment]
Was it working before?

**Comment by Hysteriana** [comment]
i dont think so.. oddly it works on eikju german client..

2015-09-09 8:57 GMT+02:00 Piotr Szymczak notifications@github.com:

> Was it working before?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mordonus/RaidOps/issues/395#issuecomment-138807516.

## 

Mit freundlichen Grüßen
Dominik Ohm

**Comment by Drutol** [comment]
Hmm , I must have made some typographical mistake in translations.

**Comment by Hysteriana** [comment]
Volatility Lattice is also missing from the boss list, i will try to get you boss kill emotes tonight.

**Comment by Drutol** [comment]
No need for them I just need its name in German.

**Comment by Hysteriana** [comment]
Volatility Lattice = Explosionsraster

**Comment by Drutol** [comment]
Fixed and added v2.34

**Comment by Drutol** [comment]
What about these?

![image](https://cloud.githubusercontent.com/assets/6102530/9791199/274fdc52-57da-11e5-9536-5d9f45296ebe.png)

**Comment by Hysteriana** [comment]
will let you know when we finaly killed them ...

**Comment by Drutol** [comment]
I mean , are they bosses to include there?

**Comment by Hysteriana** [comment]
yes they are.. DS has a lot of event rooms that count as bosses, means there will be boos loot like tokens and stuff
