### ISSUE TITLE
Bug: v2.32a : Lua Error on Undo 

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#396]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2852: bad argument #2 to 'format' (number expected, got nil)
stack trace:
    [C]: in function 'format'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2852: in function 'UpdateItem'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2608: in function 'RefreshMainItemList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:780: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:740>

**Comment by Drutol** [comment]
Do you remember what undo type it was?

**Comment by Hysteriana** [comment]
i think it was a overlapping with the decay undoing
cause the lua error with v2.33 beta i went back to v2.32a.
then got lua error on start cause the savefile change i guess.. did a import with sync tool to fix it..
was fixed, but i got the outdated data from before the decay..
but in my recent activity there was still the decay
so i did 6 or 7 undo to undo everthing from today to get in sync with the raidops page
i guess the lua error came when i hit the decay undo, but not 100% sure
or maybe a item loot undo

**Comment by Drutol** [comment]
That's why we have beta... I think I know what went wrong. Was ML usable with this search bug?

**Comment by Hysteriana** [comment]
search bug?

**Comment by Drutol** [comment]
#394

**Comment by Hysteriana** [comment]
umm that was no "search" bug, all i did was to select the first item "ds token" and that lua error happened.. and then all names of the raid player were merged to one line.

i then started chatbidding from the light window, but couldnt assign to the winner.

thats why i went back to v2.23a

**Comment by Drutol** [comment]
I mean it was search error because it tried to search in old way that is removed now :)

Uff there'll be a lot of work to get ML working this way ;d

Thanks

**Comment by Drutol** [comment]
Fixed v2.34 Beta 2
