### ISSUE TITLE
Bug : v2.34 Beta 1 on PTR : Lua Error on Login

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#397]
...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:333: attempt to call method 'OnMasterLootUpdate' (a nil value)
stack trace:
    ...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:333: in function 'BidCompleteInit'
    ...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:143: in function <...ta\Roaming\NCSOFT\WildStarPTR\Addons\RaidOps\BID.lua:140>

**Comment by Drutol** [comment]
Is it persistent?

**Comment by Hysteriana** [comment]
yes, every relogui

2015-09-09 12:14 GMT+02:00 Piotr Szymczak notifications@github.com:

> Is it persistent?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mordonus/RaidOps/issues/397#issuecomment-138864947.

## 

Mit freundlichen Grüßen
Dominik Ohm

**Comment by Drutol** [comment]
Oww I have moved some stuff here and there and integration with loot hex is causing this error , disable it ;d
