### ISSUE TITLE
Bug-ish : v2.34 Beta 2 : Alts and Main togehter in Raid equals double EP

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#398]
we had following situation:

Player X was playing active on his main X.
He was also in raid with his Alt Y, cause his twink is stalker to port us to the boss, 
then he relog and his main X gets ported too.

but since X and Y are both in raid, even if one of them is online and the other one is offline, both get the EP, and since Y is added as alt to X, X gets double ep

**Comment by Drutol** [comment]
Umm alt doesn't imply that only either main or alt is online?

**Comment by Drutol** [comment]
This is pretty rare occurrence isn't It? ( Implementing checks for it right now would be troublesome to say the least.)

**Comment by Hysteriana** [comment]
true, thats why "bug-ish".

just in case you get bored :D

**Comment by Drutol** [comment]
No more duplicates.
