### ISSUE TITLE
Bug ? : RaidOps Uploader stops at Status 70/76

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#399]
see title.. looks like it got uploaded but im not sure if complete.

**Comment by Hysteriana** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/11199863/9774285/c809ff8a-5747-11e5-88de-d26883be4ed7.png)

**Comment by Drutol** [comment]
If import takes longer than 20 secs it'll timeout , notice the spinner bar is just spinning freely. I forgot to change status after that happens.

**Comment by Hysteriana** [comment]
so if it timeout ? what then ? retry ? or is the log to large ?

**Comment by Drutol** [comment]
It just stops fetching results , import happens regardless.

**Comment by Drutol** [comment]
I'll push fix to this once I add "new version" notice.

**Comment by Drutol** [comment]
Fixed v1.1
