### ISSUE TITLE
Decaying EPGP

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#4]
I brought this up before, I just don't remember if you said you fixed it or not. Regardless, here's what happened. After decaying EPGP for the week, the decayed GP values seem to still be taking the base GP into account. For example, raider's effective GP was 913.054. Her real GP is 813.054 + Base. The addon decayed the effective GP when it needs to decay the real GP.

**Comment by Drutol** [comment]
Yup I know that's an issue but I can't get myself to do it ^^.I promise that this will come this weekend.

**Comment by Drutol** [comment]
Scheduled for rev 131 i.e Saturady/Sunday.

**Comment by Drutol** [comment]
Added/Fixed in rev 131.
