### ISSUE TITLE
Bug : r132 : Bidding Chat doesnt seem to work.

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#40]
right click on network bidding to start chat bidding does nothing, no chat message or anything.

**Comment by Drutol** [comment]
Hmm we will have to go on a hill and check this xd.

**Comment by Hysteriana** [comment]
will do. Mail me when Ur Ingame

**Comment by Drutol** [comment]
Fixed rev 133. Hill will be required this weekend though.
