### ISSUE TITLE
Bug: RaidOps error on load / reloadui - Epgp Management only shows a single raider in list. 

### ISSUE THREAD

**Issue by coden1ke** [Mordonus/RaidOps#401]
This started occurring last week, just got around to posting the Error log.

When I look in /epgp (in game) it shows only a single  raider in the list without any GP or PR values - EP is listed correctly. I am also unable to distribute loot and need to fall back on the Carbine master loot addon. That being said the rest of the addon looks to be functional. 

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:405: attempt to perform arithmetic on field 'nAwardedGP' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:405: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:403>
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:670: in function 'EPGPGetPRByName'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2921: in function 'UpdateItem'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2673: in function 'RefreshMainItemList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3213: in function 'LabelUpdateList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:582: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:349>

**Comment by Drutol** [comment]
Which beta version are you running?

Previous betas had some serious issues... and the buggy one was released exactly week ago.

**Comment by coden1ke** [comment]
It said I was running Beta 2.27 (I didnt see a letter after the version number). Now that im looking at the verson logs on the curse website I am not sure why it didn't keep me updated with the latest release or betas at that. 

I just downloaded 2.32a as it looks to be the latest release version and the issue is persisting. 
Ill paste in the error once more in case it differs. 

...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:677: attempt to perform arithmetic on field 'GP' (a nil value)
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:677: in function 'EPGPGetPRByName'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2854: in function 'UpdateItem'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2608: in function 'RefreshMainItemList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3146: in function 'LabelUpdateList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:536: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:317>

**Comment by Drutol** [comment]
Once you go for version greater than 2.32 you cannot go back to previous ones. That's why you are getting this error now.

Try using v2.34 Beta 2 as there was quite a lot bug fixing there.

If there are still errors with v2.34 B2 send me your XML file from AddonSaveData and I'll fix it for you. Importing data from website export should also fix this issue.

**Comment by Hysteriana** [comment]
the Problem with curse is, that if you use file import export, its listed
at modified and you wont See updates

**Comment by Drutol** [comment]
That's true , I want Steam Workshop! ;d

**Comment by Drutol** [comment]
I've managed to rescue some data : http://pastebin.com/rec1WSBz
There are 14 players who lost their GP values but you have to verify things by yourself.
Import it with v2.34 Beta 2

Your xml has been corrupted to the point where whole addon has bugged out and I just don't know why...
Beta is beta and wild things can happen , make backups before using test versions :)

I'm pretty busy irl so v2.34 B2 will be around for a while.

**Comment by coden1ke** [comment]
No problem at all, thanks a bunch for your help!
