### ISSUE TITLE
Can't Merge Alts

### ISSUE THREAD

**Issue by GinJeanie** [Mordonus/RaidOps#402]
I used the live version and got this error, then downloaded the beta and I'm still getting it. Basically, if I have the alt of someone listed and their main, I can't go to the main's name-> add alt-> type name-> merge anymore, without getting the following error:

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5281: bad argument #3 to 'format' (string expected, got nil)
stack trace:
    [C]: in function 'format'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5281: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5278>

**Comment by Drutol** [comment]
Thanks for report!
Matter of moving one thing a few lines up :) 
I currently have addon in development state and it'll take a few days to wrap things up...
Fixed v2.34
