### ISSUE TITLE
Bug: No Decay in German version (2.34 Beta 2)

### ISSUE THREAD

**Issue by Eikju** [Mordonus/RaidOps#403]
Hey there.

I can not make a decay in German version.

...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:453: attempt to index field '?' (a nil value)
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:453: in function 'EPGPCheckTresholds'
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:530: in function <...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:489>

**Comment by Hysteriana** [comment]
same in english

...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:453: attempt to index field '?' (a nil value)
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:453: in function 'EPGPCheckTresholds'
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:530: in function <...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:489>

**Comment by Drutol** [comment]
https://www.dropbox.com/s/5tjkknwnws8dbfs/addons.rar?dl=0
