### ISSUE TITLE
Throw error messages straight in my face!

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#404]
@Hysteriana showed me very interesting thing called [telegram](https://telegram.org/)

If you want to tell me something just write there , you can find me there under this nickname:

> @Drutol

It will pop-up on my phone or in win10 notifications so you should get reply quickly :)

**Comment by Hysteriana** [comment]
yeah and dont forget to install it on linux too for while you are coding :D

**Comment by Drutol** [comment]
mercy.. please..!

**Comment by Hysteriana** [comment]
hehe i just saw it :D  #404 bug not found :D
