### ISSUE TITLE
Bug : v2.34 Beta 2 : GP / Decay Calculation is buggy..

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#405]
our default base GP is 1000, and we have option enabled to dont allow to drop below it.
today i made a 20% decay with the fix you provided it #403 .
but now all ppl who are supposed to have 1000 gp have suddenly 2000 gp for no reason 
the log even shows the decay -200 with after 800 gp
no idea where the extra 1000 or 1200 gp came from. there is nothing in the logs about it.

![1](https://cloud.githubusercontent.com/assets/11199863/9890759/55f50182-5c02-11e5-97fa-8ef6477c086c.png)

**Comment by Drutol** [comment]
On it

**Comment by Drutol** [comment]
Done , I'll send you fix via telegram
