### ISSUE TITLE
Bug : v2.34 Beta 2 : Lua Error un Raid Session start

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#406]
seemed to be a one time happening 

...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:916: bad argument #1 to 'lower' (string expected, got table)
stack trace:
    [C]: in function 'lower'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:916: in function 'AttStart'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:880: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:874>

**Comment by Drutol** [comment]
Fixed v2.34
