### ISSUE TITLE
Bug : v2.34 : Server crash + relog = Lua Error :D

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#408]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2498: bad argument #1 to 'ipairs' (table expected, got nil)
stack trace:
    [C]: in function 'ipairs'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2498: in function 'GetOnlinePlayers'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1051: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1048>

**Comment by Drutol** [comment]
Fixed
