### ISSUE TITLE
When trying to change group for new player

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#409]
...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1377: attempt to index field 'setti.ngs' (a nil value)
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1377: in function 'GroupDialogPopulate'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1368: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:1358>

**Comment by Drutol** [comment]
That dot seems very suspicious... (setti.ngs)

**Comment by Larnen** [comment]
:)

**Comment by Hysteriana** [comment]
im gonna guess.... typo ?  😁

**Comment by Drutol** [comment]
It can't be that... consider it fixed :)
