### ISSUE TITLE
Bug : v2.34 : Lua Error : Chatbidding on Assign Randomly without to Stop bidding first

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#410]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2445: attempt to index field 'tMasterLootSelectedItem' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2445: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2427>
    (tail call): ?
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1124: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:987>

**Comment by Drutol** [comment]
Is it persistent?

**Comment by Hysteriana** [comment]
i can try and force it next time i have some junk to assign. doenst happen that often that i have to assign by chatbidding without a winner. but next time would be the 29.09. after ftp launch.

btw whats up with your telegram ? there is still a message from me pending that hasnt reached you yet.

**Comment by Hysteriana** [comment]
why is this still open ?

**Comment by Drutol** [comment]
Idk , is it fixed?

**Comment by Drutol** [comment]
Fixed v3.08j
