### ISSUE TITLE
Bug When Sorting by Pr

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#413]
...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:680: attempt to perform arithmetic on local 'nGP' (a nil value)
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:680: in function 'EPGPGetPRByValues'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3314: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3242>
    [C]: in function 'sort'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2624: in function 'RefreshMainItemList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3523: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3510>

**Comment by Drutol** [comment]
Fixed v2.34b
