### ISSUE TITLE
Sort by PR on Website with Groups

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#414]
When you have groups on the website and click on a group you still can't sort by PR.

Also I'm still unsure what is being displayed when you have groups on the website and don't select one. The values that are listed by default (no groups selected) don't seem to correspond to anything in the addon. Perhaps if you have groups it should default to the 1st one?

**Comment by Drutol** [comment]
Without any group selected it should display the values for active group at the time of export.

Send me your xml and I'll figure what's going on :)

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/10095885/5b7699b4-636d-11e5-8f4c-7d80126f4dd7.png)

![image](https://cloud.githubusercontent.com/assets/6102530/10095903/7e2a8434-636d-11e5-9673-7a2a478413ed.png)

![image](https://cloud.githubusercontent.com/assets/6102530/10095913/98ee81ee-636d-11e5-80f5-d4e26187daa2.png)

Everything seems to be correct...

Btw fixed bug that prevented groups from being imported...

**Comment by Drutol** [comment]
I'll try to get this sorting done somehow , I've tried to do this a couple of times failing each attempt

**Comment by Larnen** [comment]
Hmm, still not sure its working. When I look at it - lets use Dresdon as an example:

Default: EP: 2868, GP: 1500, PR: 1.91
GA: EP: 32796.49, GP: 28777.29, PR: 1.14  (why the decimals by the way?)
DS: EP: 2718.0, GP: 1500.0, PR: 1.81

So the 'default' doesn't tally with either GA or DS. Moreover the decimals are different for each despite the fact its a single setting and ive uploaded both DS and GA updates on a near daily basis for weeks.

Ta!

**Comment by Larnen** [comment]
Xml sent via email

**Comment by Drutol** [comment]
Fixed 2 more bugs with your xml ;d (v2.34c)
Now I'll be checking the numbers

**Comment by Drutol** [comment]
So the active group is Datascape.

Default page without selecting group displays PR 1.91 which is the same for addon's DS group. :ok: 
Page with selected GA displays PR 1.14 which is the same for addon's GA group. :ok:
Page with selected DS displays PR 1.81 which is **not** the same for addon's DS group. :x:

**Comment by Drutol** [comment]
From export string:

```
"tDataSets":[{"tData":{"GP":28777.288725403,"EP":32796.485656202,"PR":"1.14","net":500,"tot":500},"strGroup":"Genetic Archives"},{"tData":{"GP":1500,"EP":2868,"PR":"1.91","net":500,"tot":500},"strGroup":"Datascape"}
```

Data is :ok:.

Which means that import mechanism does something.

**Comment by Drutol** [comment]
Found one more bug + fixed this import issue.
http://www.raidops.net:9292/guilds/31

Now I'll do something with decimals.

Hmm the progress bar now works... strange...

**Comment by Drutol** [comment]
Try uploading now with v2.34d

**Comment by Larnen** [comment]
Still not working.

In addon:
Dresdon: GA = 1.32, DS = 1.87

On website, No selection = 1.32, GA = 1.2, DS = 1.87

GA was the active group, but selecting GA still breaks.

Also any chance of revisiting the sort by pr thing on the website? It makes using the website to scan down for who is top of priority basically unusable :(

**Comment by Drutol** [comment]
My next guess its that this 1.2 for GA on website is just value for ungroupped mode as values are swapped around. I'll just add rule to export to make this value the same as in active group.

**Comment by Drutol** [comment]
Dissected export string , should finally work with v3.06.

![image](https://cloud.githubusercontent.com/assets/6102530/10540783/7a5894b4-740b-11e5-842e-b2ccd91bc5c6.png)

**Comment by Drutol** [comment]
As far as sorting is concerned , I'd need some help with SQL as I cannot figure what should I call in order to access right priority values. Maybe you have experience with SQL by any chance? :D

**Comment by Drutol** [comment]
As soon as I start whining...
![image](https://cloud.githubusercontent.com/assets/6102530/10542956/fe6d6c6a-741b-11e5-9242-234c9781d2b7.png)

**Comment by Drutol** [comment]
I'll leave it for now like this I don't dare inventing SQL statements for it to be fully functional ;d.
I hope this will suffice...

**Comment by Larnen** [comment]
I know a _bit_ of SQL (enough to install SQL based apps and tweak permissions, groups etc), but not enough to be useful I suspect :)

If its auto sorting by PR that'd be fine, even if we don't know why :) Could it be based on the sort order in the application when it was exported?

**Comment by Drutol** [comment]
Nah , the reason is that each member has many different "data sets" each data set contains info about pr,ep,gp etc. + name of group it corresponds to. When I'm trying to sort it in this "grid" fashion values from data sets corresponding to different groups are being used. One thing gets displayed different thing gets sorted.

I've managed to make workaround for this and now I'm supplying the data I want in the order I want but I don't know how to make the "grid" plugin play with it well (I can bruteforce it and probably will though ^^).

Seems to be working ok for now :)
