### ISSUE TITLE
Bug : v2.34 : F2P live - first lua error :D

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#415]
...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:733: attempt to index global 'aAddon' (a nil value)
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:733: in function 'HookToTooltip'
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:748: in function 'func'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:678: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:674>

**Comment by Drutol** [comment]
Don't tell me they changed something right in release build...

**Comment by Drutol** [comment]
It's probably a race condition that happened to show itself right now

**Comment by Drutol** [comment]
Hook occured 3 secs after UI has been initialized , now addon will attempt to do so 10 times in 1 secs intervals. This should solve this.
