### ISSUE TITLE
Bug when inviting (F2P!)

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#417]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2263: attempt to index field '?' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2263: in function 'MassEditInviteContinue'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6411: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6394>

**Comment by Drutol** [comment]
Fixed some quirky things but I didn't notice any obvious reason :(
Let's see how it performs in v3.01

**Comment by Larnen** [comment]
It didn't recur today on 3.01 :)
