### ISSUE TITLE
Bug on....err....crafting :)

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#418]
...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:653: attempt to compare nil with number
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:653: in function 'EPGPGetItemCostByID'
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:795: in function <...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:788>
    (tail call): ?
    ui\Crafting\Crafting.lua:1079: in function 'HelperBuildTooltip'
    ui\Crafting\Crafting.lua:870: in function 'UpdatePreview'
    ui\Crafting\Crafting.lua:822: in function 'UpdateStats'
    ui\Crafting\Crafting.lua:779: in function 'SetProperty'
    ui\Crafting\Crafting.lua:479: in function 'InitCraftAttempt'
    ui\Crafting\Crafting.lua:158: in function <ui\Crafting\Crafting.lua:114>
    [C]: in function 'Event_FireGenericEvent'
    ui\MasterCraftsman\MasterCraftsman.lua:97: in function <ui\MasterCraftsman\MasterCraftsman.lua:95>

Version 3.01

**Comment by Hysteriana** [comment]
I knew drotol is aiming for word domination. his add-on attacks crafting already. next is ah and wallstreet  :fu:  :grinning:

**Comment by Drutol** [comment]
Fixed v3.02
