### ISSUE TITLE
Bug : v3.01 : at Login

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#419]
...FT\WildStar\Addons\RaidOpsMemberModule\RaidOpsMM.lua:516: attempt to index a nil value
stack trace:
    ...FT\WildStar\Addons\RaidOpsMemberModule\RaidOpsMM.lua:516: in function 'Bid2PackAndSend'
    ...FT\WildStar\Addons\RaidOpsMemberModule\RaidOpsMM.lua:223: in function <...FT\WildStar\Addons\RaidOpsMemberModule\RaidOpsMM.lua:220>

**Comment by Drutol** [comment]
Fixed
