### ISSUE TITLE
Armory - Gear & New Rune System Update

### ISSUE THREAD

**Issue by GinJeanie** [Mordonus/RaidOps#420]
I get "tooltip unable to load" on checking member's gear and runes since Drop 6. I deleted and remade my guild's page since some errors just persisted in making overall edits.
http://www.raidops.net:9292/guilds/42

**Comment by Drutol** [comment]
Tooltips / item data is provided by jabbithole.com and as I'm not going to create my own database from scratch we have to wait for jabbithole to update.

Umm what errors?

I'll update armory to track new stats and rune sets once I find time for it. I have just began my freshman year in uni of science so I have little free time for now :(

**Comment by Hysteriana** [comment]
ohoh drutol is about to become a mad scientist who is going for world
domination with the devastating power of typos 😁

**Comment by Drutol** [comment]
Runes have been somewhat updated , I'll have to tweak them a bit. Jabbithole should work somewhen in November (according to blog post) as soon as it happens everything should work well.

**Comment by Drutol** [comment]
Fix with rune sets will be up today , just need to verify it now :)

**Comment by Drutol** [comment]
Now we are only waiting for JH update. Fixed v3.08g
