### ISSUE TITLE
Bug: v3.02 : LUA Error at Item Assign after Chatbidding

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#421]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1004: attempt to index global 'selectedItem' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1004: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:987>

**Comment by Drutol** [comment]
If it did not hook this isn't surprising.

**Comment by Hysteriana** [comment]
maybe also loothex mixup
