### ISSUE TITLE
Bug: v3.02 : RaidOps doesnt hook into Masterloot anymore

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#422]
see title

![unbenannt](https://cloud.githubusercontent.com/assets/11199863/10351302/1b836c70-6d49-11e5-9b6d-d797bb749fbd.png)

**Comment by Drutol** [comment]
Oddity odd...

**Comment by Drutol** [comment]
v3.02
![image](https://cloud.githubusercontent.com/assets/6102530/10369767/3a55f0da-6ddc-11e5-97c9-26323c14eca6.png)

Are you sure that you don't have multiple folders with the same addons?

Is anyone else experiencing this?

**Comment by Hysteriana** [comment]
my bad, mix up with LootHex
