### ISSUE TITLE
Request: v3.04 : Save actual Raid Roster

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#425]
sometimes we switch player during raid, some from queue come in, while other leave and join queue.
the player to leave are no longer marked in anyway to still get EP like the ones previous marked for queue. 

so it would be nice to convert or add complete roster to the queue or save them in some other way.

**Comment by Hysteriana** [comment]
it doesnt workt to set the actual roster to quere, since ppl who raid with alt will get double ep

**Comment by Hysteriana** [comment]
problem is, if someone played with alt, and went back to main, he seems to get all ep double

**Comment by Drutol** [comment]
Okay okay, I'm coming home early today so I'll do something about this. + I feel like adding more item filters to website ;d

**Comment by Drutol** [comment]
So basically #398

**Comment by Drutol** [comment]
Duplicates now should be removed.
