### ISSUE TITLE
BIG Problem : v3.04 : GP Calculation broken

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#426]
just notices, that items dont have any item power anymore.. they are classified by item level only.
also there are no epics anymore in raids, only legendary and artefacts.

so we need to find a new calculation formula 
i suggest to switch item power with item level

**Comment by Drutol** [comment]
Artifacts are now a thing?

**Comment by Hysteriana** [comment]
item level 130

**Comment by Drutol** [comment]
Turned out not to be broken , added pink quality modifier + option to use item level for GP calculation formula.
