### ISSUE TITLE
Bug : v3.06 : Lua Error on Personal Log Export

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#428]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4495: bad argument #2 to 'SetActionData' (can not copy an empty string)
stack trace:
    [C]: in function 'SetActionData'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4495: in function 'ExportShowPreloadedText'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5418: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:5413>

**Comment by Drutol** [comment]
Fixed v3.07

**Comment by Hysteriana** [comment]
hmm I know its back to the future day.. but why did you fixed it with an
older version from the past ? 😁😁😁
Am 28.10.2015 15:18 schrieb "Piotr Szymczak" notifications@github.com:
