### ISSUE TITLE
Bug : v3.06 : Sometimes Player are doubles listed in recent activty ...

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#431]
.. cause the got the same amount twice.

![unbenannt](https://cloud.githubusercontent.com/assets/11199863/10777241/820ad926-7d19-11e5-9f04-cb3115460614.png)

**Comment by Drutol** [comment]
Before IDs table goes further , duplicates will be removed. v3.07

**Comment by Hysteriana** [comment]
doubles still exist in v3.07b.. happens when ppl switch between main / alt without leaving the raid first..
happens a lot lately since for some single events we need another char and they just switch so they dont need to get re-invited and can stay offline in raid instance.
