### ISSUE TITLE
Bug when finishing the tutorial

### ISSUE THREAD

**Issue by banpower1** [Mordonus/RaidOps#432]
During the tutorial regarding Custom Events ("Some settings to check out" -> hitting the next arrow -> error)

...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\TUT.lua:512: attempt to index local 'wnd' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\TUT.lua:512: in function 'GetAbsolutePos'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\TUT.lua:555: in function 'TutStart'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\TUT.lua:496: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\TUT.lua:489>

**Comment by Drutol** [comment]
Thanks , got this one :) fixed v3.07c

**Comment by Hysteriana** [comment]
wow... someone really did the tutorial 😁
