### ISSUE TITLE
Bug : v3.08 : Lua Error : Tried to add manual EP

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#435]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:764: bad argument #1 to 'gfind' (string expected, got table)
stack trace:
    [C]: in function 'gfind'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:764: in function 'GetPlayerByIDByName'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:783: in function 'RemoveDuplicateValues'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2395: in function 'MassEditModify'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1408: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1406>

**Comment by Hysteriana** [comment]
also custon event trigger affected 0

**Comment by Drutol** [comment]
Fixed v3.08a
