### ISSUE TITLE
On mouseover trash items in the world

### ISSUE THREAD

**Issue by banpower1** [Mordonus/RaidOps#436]
Enabled the new "Calculate GP for unequippable items" and the "show GP on tooltips", mouseover trash in world:

...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:788: attempt to perform arithmetic on field '?' (a nil value)
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:788: in function 'EPGPGetItemCostByID'
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:925: in function <...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:918>
    (tail call): ?
    ui\ToolTips\ToolTips.lua:763: in function 'UnitTooltipGen'
    ui\ToolTips\ToolTips.lua:2705: in function <ui\ToolTips\ToolTips.lua:2704>

**Comment by Drutol** [comment]
Fixed v3.08b
