### ISSUE TITLE
Error on mouseover trash in inventory

### ISSUE THREAD

**Issue by banpower1** [Mordonus/RaidOps#437]
Enabled the new "track GP on unequippable items" and "show GP on item tooltips", mouseover trash item in inventory produces same error with differen stacktrace.

...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:788: attempt to perform arithmetic on field '?' (a nil value)
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:788: in function 'EPGPGetItemCostByID'
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:925: in function <...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:918>
    (tail call): ?
    ...ing\NCSOFT\WildStar\Addons\KuronaBags\KuronaBags.lua:2822: in function <...ing\NCSOFT\WildStar\Addons\KuronaBags\KuronaBags.lua:2817>

**Comment by Drutol** [comment]
Fixed v3.08b
