### ISSUE TITLE
Bug on opening account inventory - collapses all items, making account inventory break

### ISSUE THREAD

**Issue by banpower1** [Mordonus/RaidOps#438]
...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:774: attempt to perform arithmetic on field '?' (a nil value)
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:774: in function 'EPGPGetItemCostByID'
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:925: in function <...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:918>
    (tail call): ?
    ui\AccountInventory\AccountInventory.lua:383: in function 'HelperAddPendingSingleToContainer'
    ui\AccountInventory\AccountInventory.lua:539: in function 'RefreshInventory'
    ui\AccountInventory\AccountInventory.lua:311: in function 'SetupMainWindow'
    ui\AccountInventory\AccountInventory.lua:202: in function <ui\AccountInventory\AccountInventory.lua:200>
    [C]: in function 'Event_FireGenericEvent'
    ui\InterfaceMenuList\InterfaceMenuList.lua:505: in function <ui\InterfaceMenuList\InterfaceMenuList.lua:499>

**Comment by banpower1** [comment]
Break = actually ruin it, making account inventory window un-usable*

**Comment by Hysteriana** [comment]
yeah looks like some pretty nasty hooks you made there drutol :D 

...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:770: attempt to perform arithmetic on field '?' (a nil value)
stack trace:
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:770: in function 'EPGPGetItemCostByID'
    ...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:925: in function <...Data\Roaming\NCSOFT\WildStar\Addons\RaidOps\EPGP.lua:918>
    (tail call): ?
    ui\AccountInventory\AccountInventory.lua:383: in function 'HelperAddPendingSingleToContainer'
    ui\AccountInventory\AccountInventory.lua:539: in function 'RefreshInventory'
    ui\AccountInventory\AccountInventory.lua:311: in function 'SetupMainWindow'
    ui\AccountInventory\AccountInventory.lua:193: in function <ui\AccountInventory\AccountInventory.lua:191>
    [C]: in function 'Event_FireGenericEvent'
    ui\LoginIncentives\LoginIncentives.lua:321: in function <ui\LoginIncentives\LoginIncentives.lua:320>

**Comment by Drutol** [comment]
Both trash items and account inventory is working fine for me as of v3.08b

**Comment by banpower1** [comment]
Confirmed v3.08b is working fine
