### ISSUE TITLE
Bug : v3.08b : Lua Error : Tab sort asc/desc

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#440]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3348: attempt to compare two nil values
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3348: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3277>
    [C]: in function 'sort'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3500: in function 'RefreshMainItemListAndGroupByClass'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3570: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3559>

**Comment by Hysteriana** [comment]
only when "Group by Class" is active *

**Comment by Drutol** [comment]
Fixed v3.08c
