### ISSUE TITLE
Bug : v3.08b : Lua Error : Direct assign of 2nd item while chatbidding still active on 1st item

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#441]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4810: bad argument #1 to 'SetText' (string expected, got nil)
stack trace:
    [C]: in function 'SetText'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4810: in function 'PopUpPopulate'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4797: in function 'PopUpCheckUpdate'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:4789: in function 'PopUpWindowOpen'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1695: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:1637>
    [C]: in function 'PostOnChannel'
    ui\ChatLog\ChatLog.lua:2043: in function <ui\ChatLog\ChatLog.lua:2042>
    [C]: in function 'Event_FireGenericEvent'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2462: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:2459>
    (tail call): ?

**Comment by Drutol** [comment]
Fixed (?) v3.08c
