### ISSUE TITLE
Bug :  Webpage import to addon is not in sync

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#445]
on webpage we have 42 member.. import by tool gives me old data with 57 member.

**Comment by Drutol** [comment]
Sometimes some odd random problem may appear , try to import via webpage and check whether it says that backup was successful.

**Comment by Drutol** [comment]
Is it gone?

**Comment by Hysteriana** [comment]
think so, did another tool download today, it it was in sync

2015-11-11 13:32 GMT+01:00 Piotr Szymczak notifications@github.com:

> Is it gone?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mordonus/RaidOps/issues/445#issuecomment-155765090.

## 

Mit freundlichen Grüßen
Dominik Ohm
