### ISSUE TITLE
Bug on Invite v3.08

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#446]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2278: attempt to index field '?' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2278: in function 'MassEditInviteContinue'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6456: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:6439>

**Comment by Drutol** [comment]
Got it!

hmm , bugfix in 3 mins :D
w8 for curse to "approve" it
