### ISSUE TITLE
Request : v3.08 : more  Player log entries

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#447]
since ingame addon sync is nearly obsolete and we have the option to purge the logs with upload, maybe the player log entries could get more lines. today the player logs miss the first hour cause of the number of entries. makes review difficult.

**Comment by Hysteriana** [comment]
or make it even optional how many log entries someone wants ? bitches love options :D

**Comment by Drutol** [comment]
One more slider cannot possibly hurt...

**Comment by Drutol** [comment]
Added v3.08e
