### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by Larnen** [Mordonus/RaidOps#448]
In 3.08e, trying to upload either via traditional method or uploader gives the same error:

undefined method `[]' for nil:NilClass

**Comment by Hysteriana** [comment]
cant confirm, just tried upload to webpage by uploader tool, no problems

**Comment by Drutol** [comment]
Send me your export string

**Comment by Drutol** [comment]
Without it I cannot even guess where something went wrong. (there's quite a lot of arrays)

**Comment by Renira** [comment]
I'm having the same issue. (Also sorry I haven't been around at allll lately.) What's the best way to send the import string?

**Comment by Renira** [comment]
Getting the same issue by uploader tool and upload via website as well.

**Comment by Renira** [comment]
[nil error.txt](https://github.com/Mordonus/RaidOps/files/36265/nil.error.txt)

**Comment by Drutol** [comment]
I'll try to sort it out today

**Comment by Drutol** [comment]
Fixed

**Comment by Renira** [comment]
You are freaking awesome. Thanks!

**Comment by Larnen** [comment]
Thanks Mordonus - wasnt online so couldn't send log straight away. I now have the other issue mentioned on uploads so will comment on that thread too
