### ISSUE TITLE
Can not upload anything (unknown attribute 'strType' for Log.)

### ISSUE THREAD

**Issue by Eikju** [Mordonus/RaidOps#451]
Hey guys :)

I can not upload anything to the EPGP-Website - not with manual mode and not with the RaidOpsUploader.

The Error is still the same:

unknown attribute 'strType' for Log.

Can you help me?

My addon version: v3.08e

**Comment by Hysteriana** [comment]
his export

[EPGP.txt](https://github.com/Mordonus/RaidOps/files/37278/EPGP.txt)

**Comment by Hysteriana** [comment]
upload somehow worked anyway, at least partial.
page shows the same data like i got when i imported his export.
but the "last update" tab isnt right.. per example : Solari Tigris was updated today and not 5 days ago.
also would be nice to have that tab sort able asc or desc.

tried it too with uploader: got also this at 10/78
![unbenannt](https://cloud.githubusercontent.com/assets/11199863/11226863/f7822ff0-8d82-11e5-8f54-7ceaae8de554.png)

**Comment by Larnen** [comment]
Getting the same error both by website and uploader

**Comment by Drutol** [comment]
I'll fix it right away , I must have skipped it while renamimg stuff.

**Comment by Drutol** [comment]
Should be working now.

As far as last update is concerned:
It says 5 days and it's 5 days.
![image](https://cloud.githubusercontent.com/assets/6102530/11233275/1a4c77be-8dbc-11e5-9922-aa78ff04ee29.png)

**Comment by Drutol** [comment]
Btw , is there an update on when jabbithole is going to be functional again?

**Comment by Hysteriana** [comment]
works, can be closed, sort by time stamp in the overview would be nice though.

**Comment by Drutol** [comment]
Hah , just like with groups and sorting this requires sql magic , I did not unlock this ability yet xd
