### ISSUE TITLE
Bug : Webpage : Cant commit

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#452]
when i try to commit all modifies at once or each separate i get an error page:

http://www.raidops.net:9292/guilds/13/commit_all
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

http://www.raidops.net:9292/guilds/13/guild_members/8500/commit
The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.
If you are the application owner check the logs for more information.

**Comment by Drutol** [comment]
If it was working before , it should work now.

**Comment by Drutol** [comment]
Are commits okay now?

**Comment by Hysteriana** [comment]
nope still same error message

**Comment by Drutol** [comment]
Fixed this error , but the cause still remains somewhere
