### ISSUE TITLE
Raid Ops Master Loot Show on Demand Error

### ISSUE THREAD

**Issue by Renira** [Mordonus/RaidOps#453]
I decided to update my Master Loot Settings and wanted to try the "Appear only on demand" option. After enabling it, I couldn't find the hex anywhere to unhide the master loot so I wanted to disable it. Unfortunately, it appears the disable function is broken. After disabling the addon so I could deal with loot for the rest of the night, I took a look and found an error in the bid.lua for the DKP:MLSetDemandAppearDisable() function. It was missing the colon after DKP and was set to Enable instead of Disable. After correcting it, I can now disable just fine. ;)  Any idea why the on demand icon couldn't be found?  Thanks!!

**Comment by Hysteriana** [comment]
"Any idea why the on demand icon couldn't be found? Thanks!!"

top left corner of your raid frame is a blue square icon.

**Comment by Renira** [comment]
Ah, that might be why then. I don't run the base raid frames. Looked all over, but saw no blue icon. Thanks for letting me know what to look for though. :) I'll take another look tomorrow to make sure I'm not blind.

**Comment by Hysteriana** [comment]
its also at betterraidframe and vinceraidframe

**Comment by Drutol** [comment]
Ahh the beauty of copy/paste... I don't know how did I manage to screw this up. Fixed v3.08f
