### ISSUE TITLE
Bug : v3.08e : Lua Error : After Teleport out of Dungeon

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#454]
...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:692: attempt to index a nil value
stack trace:
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:692: in function 'AttUpdatePlayers'
    ...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:963: in function <...ata\Roaming\NCSOFT\WildStar\Addons\RaidOps\RAID2.lua:962>

**Comment by Drutol** [comment]
Ahh , this ... Fixed v3.08f
