### ISSUE TITLE
Bug : v3.08f : Lua Error : after DC while entering dc

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#456]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1734: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1734: in function 'Bid2GetTargetsTable'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:2657: in function 'RefreshMainItemList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3248: in function 'LabelUpdateList'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:3186: in function 'LabelInit'
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:551: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\DKP.lua:347>

**Comment by Drutol** [comment]
Hah , I knew what was it as soon as I read the title xd. Most common race condition xd Fixed v3.08h
