### ISSUE TITLE
Nevermind. Found the option.

### ISSUE THREAD

**Issue by tstolswo** [Mordonus/RaidOps#457]
I found the option for this. Nevermind!

**Comment by Hysteriana** [comment]
im curious.. what for are you using that add-on if not for epgp or dkp ?

**Comment by tstolswo** [comment]
The loot distribution features are far superior to the inbuilt master loot
from Carbine. We have a loot council type system so there isn't much
benefit in EGPG or DKP just yet, and we put a lot of work into a
sophisticated google spreadsheet for the armory.

On Sun, Nov 29, 2015 at 10:08 PM, Hysteriana notifications@github.com
wrote:

> im curious.. what for are you using that add-on if not for epgp or dkp ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Mordonus/RaidOps/issues/457#issuecomment-160511763.

## 

_A N T H O N Y stolsworth_
I.T. Professional
anthony.stolsworth@gmail.com

**Comment by Drutol** [comment]
Glad that the problem resolved itself ^^ I'm closing then. Oh and hello @manualmedia :)
