### ISSUE TITLE
Bug : v3.08k : Lua Error : on /ropsml

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#460]
...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1281: attempt to index field 'wndMLSettings' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1281: in function <...pData\Roaming\NCSOFT\WildStar\Addons\RaidOps\BID.lua:1280>
    [C]: in function 'Command'
    ui\ChatLog\ChatLog.lua:1548: in function <ui\ChatLog\ChatLog.lua:1524>

**Comment by Renira** [comment]
Likewise. On start/reloadui, debug reports: RaidOps - Could not find Dependency Master Loot Addon - All Bidding/ML Functionalities are now suspended.

**Comment by Drutol** [comment]
Omg , forgot to put ML addon in zip file.

New package is up on curse. Sorry for that :(

**Comment by Hysteriana** [comment]
too much eggnog for Christmas ? 😂

**Comment by Renira** [comment]
Definitely had to be the eggnog. ;D Thanks!
