### ISSUE TITLE
Which MasterLoot Addon should we be using?

### ISSUE THREAD

**Issue by jonathanpmast** [Mordonus/RaidOps#461]
My raid generally does a modified loot council to distribute loot, which makes the RaidOps master loot functionality really useful and helpful for us.  However, I'm having a difficult time figuring out which loot addon specifically to use.  We have certain gear (such as Class/Set Major Focus) that just get master looted and sorted at the end of the night; then we have other gear that needs to be rolled on and distributed, and then there's the additional drops that just get shipped out randomly for whatever reason.

My goal is to get as much of the loot distributed as possible without having to reloadui over and over again throughout the night.  Originally I was using the "light mode" addon because that seemed to make everything pretty straight forward.  I could easily just assign certain items to myself (masterlooter) or random them out if they didn't require chat bidding.  Chat bidding also was a click of a button away, nice.  However I've run into quite a few bugs with the addon's interface as people are moving in and out of range of me, to the point where just about every time loot drops I am required to reloadui.

So I switched to the standard masterloot addon that allows gear to be submitted for chat bidding and assigned.  This addon seems to be much more stable and reliable, but there is no option to just assign gear to the master looter.  Maybe I'm missing something?

Then there's the LootHex addon which is quite usable from a UI perspective, but I couldn't get chat bidding working alongside the rest of our configuration :(

TIA

**Comment by Drutol** [comment]
Hello :)

There are 2 ML addons:
- MasterLoot Dependency shipped with main addon with 2 modes:
  - Light mode
  - Standard mode
- LootHex

I've never had a chance to use those in real raid setting... could you elaborate on how people moving in and out of range are messing things up?

To sum up:
- **Light mode** interface is buggy because of people moving in and out of range.
- In **Standard mode** you cannot find yourself on looter list? Or you just want "assign this thingy to masterlooter" button?
- **LootHex** has chatbidding button broken.

**Comment by jonathanpmast** [comment]
Hey Mordonus,

I'm not sure if the light mode really has defects related to folks moving in and out of range or not.  It just seems like sometimes when I select one item there are people missing from the list of folks to assign... or sometimes the list scrolls beyond the frame and I can't select anyone.  I haven't been able to recreate this with any consistency.

I think having multiple loot addons is pretty confusing.  Personally I think the LootHex addon's interface is the most attractive with it's drag and drop functionality.  The standard mode is also pretty nice, except for every item (I believe) has to be rolled out as you say.  Would be nice to be able to just drag and drop to assign loot that doesn't need to go through the bidding process.  Like I said this may be functionality that I is available and I am missing.

**Comment by Drutol** [comment]
I'll play with light mode and loot hex then.

In standard mode you can select multiple items and assign them all at random or to certain looter at once. I'm not going to add drag&drop to standard addon as it's quite a lot of hassle and I believe that multiple selection does the trick here.

Edit : Yup , light mode has quite severe bug somewhere , something more interesting than typo this time ^^.
Edit2: I'm so utterly stupid , ahh...
Edit3: Happy new year , btw :D.

**Comment by jonathanpmast** [comment]
Happy New Year :)

How do you go about assigning multiple items to a certain looter?  I don't believe I could ever figure this one out... probably I'm being dense somewhere.

And for what it's worth if you have any guidance I'd be happy to fork/contribute to this project.  LUA isn't really my strength but it's a simple language.  Honestly the entire iterative debug process of addon development just kinda pains me.

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/12070693/4b815e9e-b085-11e5-886b-eef9c8672a08.png)

Once you enable this option , additional checkboxes will appear on on available items , you can select desired items and choose looter from the list on the right or press dice button in the top right corner to assign each item at random.

You are more than welcome to introduce your own changes , ML part (especially item assign) of this addon is quite messy though. I wrote it when I was still figuring how things work... "Broken code gets fixed , bad code stays bad forever". I'm just an amateur ^^.
If you wish to play with the code I'd start from DKP.lua where all "inits" are called. It begins like this : 

```
        self:TimeAwardRestore()
        self:GroupInit()
        self:COInit()
        self:EPGPInit()
        self:ConInit()
        self:AltsInit()
        self:LogsInit()
        self:GIInit()
        self:InvitesInit()
        self:LLInit()
        self:DFInit()
        self:CloseBigPOPUP()
        self:FLInit()
        self:UndoInit()
        self:CEInit()
        self:FQInit()
        self:RIInit()
        self:MAInit()
```

around line 514.
Each init equals one module (more or less) eg.

```
-----------------------------------------------------------------------------------------------
-- Logs
-----------------------------------------------------------------------------------------------

function DKP:LogsInit()
    self.wndLogs = Apollo.LoadForm(self.xmlDoc,"Logs",nil,self)
    self.wndLogs:Show(false,true)
    self.wndLogs:SetSizingMinimum(751,332)
    self.wndLogs:SetSizingMaximum(751,435)

    self.wndSettings:FindChild("YouSure?"):SetRotation(180)
    self.wndSettings:FindChild("YouSure?:Title"):SetRotation(180)

    self.wndLogs:FindChild("FilterGrid"):AddEventHandler("GridSelChange","LogsChangeFilter",self)
end
```

Debugging is quite boring , and testing things like MasterLoot may prove troublesome with limited test scenarios. I'm happy that I can just do "/reloadui" instead of launching W\* again.

**Comment by jonathanpmast** [comment]
So once I mutli-select items on the looter list, I don't see an assign button anywhere?  How do I actually distribute the loot to the selected person?

**Comment by Drutol** [comment]
You just have to use the default one in the right bottom corner.

**Comment by jonathanpmast** [comment]
I must be doing something wrong because the only buttons I found down there were Network and Chat bidding...

**Comment by Drutol** [comment]
Did you select one item from the list aside from enabling checkboxes? You have to select one item , optionally check checkboxes , select looter , press assign. I'm pretty sure it was working last time I checked.

**Comment by Hysteriana** [comment]
maybe master loot dependency ?

**Comment by jonathanpmast** [comment]
Should I not have master loot dependency enabled?  What does that addon do?

Edit:

This is the loot window that I see: 
![masterlootwindow](https://cloud.githubusercontent.com/assets/2549383/12192718/2323c386-b5af-11e5-8fe4-c6b00d891908.png)

**Comment by Drutol** [comment]
Strange... Let me check this

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/12203548/d0a90ed2-b62f-11e5-9232-a6ac26f6cd07.png)

This is how it looks for me and it looks like scaling issue to me , you should have been unable to resize this window that much horizontally. Did you play with the code anywhere maybe?

**Comment by jonathanpmast** [comment]
It looks like yours says PR above name and mine says DKP.  Could this be related to a setting I have incorrect?

Edit: also, no edits to the code at all.  Is it possibly a setting?  Because I'm pretty sure the other raid lead in my guild sees this exact same

**Comment by Drutol** [comment]
No there's no such setting, minimum size is there for a reason. Try resizing the window and it should do the trick , I'll check whether dkp has something to do with it later today.

**Comment by jonathanpmast** [comment]
i don't have a draggable resize handle on the window is there something in the addon itself that I need to configure the size?

**Comment by Drutol** [comment]
You **can** resize this window , handle is in bottom right corner. You just have to find it , there's not much I can do about it as this is purely framework thing (this point)

**Comment by jonathanpmast** [comment]
I wasn't able to ever grab the resize handle, however I got the assign button to show up by switching some configuration settings in the ropsml config.  I'm not sure what specifically... it hink maybe I flipped it from bars to tiles.  As far as I can tell it has/had nothing really to do with how things render it just shows the available loot in the top half of the window and the available raiders in the bottom (rather than the left and the right)

**Comment by Drutol** [comment]
![bqfd](https://cloud.githubusercontent.com/assets/6102530/12267828/4307f35e-b94a-11e5-90b7-d691e9a99218.gif)

If you cannot find this handle , it's beyond my knowledge why.

**Comment by jonathanpmast** [comment]
FWIW I think maybe the sizing got fixed or set up somehow from a previous version.  I deleted the addon save data for masterlootdependency and downloaded the source for the addon specifically from github, and I was able to get it all going.

Thanks for all your help @Mordonus
