### ISSUE TITLE
Website Signup

### ISSUE THREAD

**Issue by zombietop** [Mordonus/RaidOps#463]
I am trying to sign up on the site to export data, but it won't let me create a user account. 

The error after trying to register as a new user is,
 "We're sorry, but something went wrong." 
"If you are the application owner check the logs for more information"

**Comment by Drutol** [comment]
I'll check this as soon as I get home.

**Comment by Drutol** [comment]
It looks like mailing service is down this is the least what I can tell from my phone.

**Comment by Drutol** [comment]
Your account should be active now , I'm still investigating what happened.

**Comment by zombietop** [comment]
Just tried to log in. No go. Will try to register again and see what happens.

**Comment by zombietop** [comment]
No go on the re-register. Same error. Also tried logging in with my email and the PW I tried signing up with. No go there.  

Hey great addon by the way. I used the wow epgp addon for ever and was surprised at how much more your wildstar version has to offer.

**Comment by Drutol** [comment]
Hah , thanks :) 
Sorry for this mess , there may be some smtp ports blocked on the server and I'm waiting for admin to show up xd

**Comment by Drutol** [comment]
Ahh I know why it didn't activate ;d gimme a sec

**Comment by Drutol** [comment]
Okay activation is now disabled. Enjoy :)

**Comment by zombietop** [comment]
I'm in, thx!  =)

**Comment by Drutol** [comment]
And mailing is fixed now.
