### ISSUE TITLE
Download Data not working from website

### ISSUE THREAD

**Issue by mpangelu** [Mordonus/RaidOps#464]
Hi, my guild is Cold fusion, when I try to click download data from 2 different computers it says Download Failed and that is it.

**Comment by Drutol** [comment]
Oh sorry , this is very minor bug from complexity standpoint but I don't have electricity today and I cannot really do much ... and god only knows when is it going to be back again. As soon as it comes back I'll fix it. If this data is very much needed now tell me and I'll arrange something via my phone ;d . Sorry for inconvenience.

**Comment by Drutol** [comment]
It's fixed now.

**Comment by mpangelu** [comment]
If it isn't too much trouble I'd appreciate the data. If it is going to be
available before sunday that is fine as well. I hate to bother you, just I
wasn't able to get it before our raid last night and I'm already looking at
a lot of manual corrections I have to do.

Thanks for your time.

Derek

**Comment by mpangelu** [comment]
It is working!!!

**Comment by Drutol** [comment]
:)

**Comment by mpangelu** [comment]
Sorry I read your replies in the wrong order, looked like it was saying it
was fixed and then that it wasn't.
