### ISSUE TITLE
Bug : v3.08k : DS Token does not trigger popup

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#465]
did lootmaster yesterday. has been a while cause someone else is doing it now.
when i assigned a DS item token, the popup didnt show.

**Comment by Hysteriana** [comment]
guess i found the error, token ilvl is only 50, my limit was set to ilvl 100.
maybe thats why tokens are not listed on the page as item ?

**Comment by Drutol** [comment]
If they are not white listed and below ilvl threshold they are not going to be acknowledged by addon.
