### ISSUE TITLE
Web page not letting you register.

### ISSUE THREAD

**Issue by joeldgoodman** [Mordonus/RaidOps#467]
Your webpage www.raidops.net doesn't let you register which keeps you from registering you guild, getting an api, using the downloader/uploader and etc. Please fix.

Joel Goodman

**Comment by Drutol** [comment]
Oh, seems like email service has gone and died, I'll disable activation then :)

**Comment by joeldgoodman** [comment]
Describe what you mean by disable. I'm still getting an error trying to use
downloader/uploader because of no api key because I can't register.

Joel Goodman

**Comment by Drutol** [comment]
You can't probably register because email service is down, once I disable it you should be able to register.

**Comment by Drutol** [comment]
Okay, you should be able to register just fine now. Project is now stalled so I don't monitor things anymore, thanks for heads up!
