### ISSUE TITLE
Bug : r132 : Invited Selected doesnt work cause group is full

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#47]
to use this feature a raid has to open first. otherwise a lot of invites will be declined cause group is full.

**Comment by Drutol** [comment]
I'll try to find some workaround,I don't know what the API provides here.

**Comment by Hysteriana** [comment]
maybe invite the first 2-4 player, then wait for open group, if group found convert to raid, then continue inviting.

**Comment by Drutol** [comment]
That's one option , but maybe there's something hidden in API.

**Comment by Drutol** [comment]
Unfortunatelly there was nothing to discover so I'm just waiting for first player to accept and then convert to raid. Changed in rev 133.
