### ISSUE TITLE
Bug : r132 : Export / Import Bug again

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#48]
fresh installed the export / import was no problem
now after the first raid i cant import again and get the same lua error.

...ming\NCSOFT\WildStar\Addons\EasyDKP\libs/Serpent.lua:133: attempt to call a nil value
stack trace:
    ...ming\NCSOFT\WildStar\Addons\EasyDKP\libs/Serpent.lua:133: in function 'load'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3134: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3090>

export is here: 

http://pastebin.com/hmUgDMnp

**Comment by Drutol** [comment]
Heh so that's the reason. That's why they(raid summaries) need to be rewritten , unstable and buggy.

**Comment by Drutol** [comment]
Aaand they are not the reason. The export string was just too big and now I'll just skip log saving so we save space. Fixed in rev 133.
