### ISSUE TITLE
Request : r132 : Lootmaster : Filter shown class

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#52]
would be nice to be able to filter out the right armor class.
like with heavy armor only shows warrior and engineers
medium only should show medic and stalker
and light armor only spellslinger and esper.

**Comment by Drutol** [comment]
Adding this would require literally 10 lines of code :). Expect it tommorow.

**Comment by Drutol** [comment]
Postponed to rev 134.

**Comment by Drutol** [comment]
Added in rev 134.
