### ISSUE TITLE
Sorting by PR

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#53]
I brought this up earlier about the loot window not sorting by PR, and you attested that it did. What I didn't notice was that it sorted in an Ascending manner, with the highest PR last. Any chance of making it descending, with the highest PR first? Or adding a toggle for it? 

Additionally, is it possible to screen certain armor classes out of being able to see loot? Like maybe run a class check on the member module's user. If I throw a piece of Heavy armor up for bid, then stalkers, medics, espers, and spellslingers don't see it? Or auto-pass?

**Comment by Hysteriana** [comment]
if you talk about the Masterloot window, it is sorted by the PR if you disable "sort by group" at the settings. also there are 2 little arrows at the top right corner next to the settings button, that will sort ascending or descending if you activate that little sort option button next to it.

i also requested sort by name too here: https://github.com/Mordonus/RaidOps/issues/51

the armor issue has some kind been posted here: https://github.com/Mordonus/RaidOps/issues/52 . maybe your suggestion may additional to that ?

**Comment by Drutol** [comment]
Network Bidding : My bad I have put the wrong character in sorting function ">" instead of "<".
Giving option to skip auctions with wrong armor types is not a big deal , just give me a little bit of time to catch up with everything(but keep them issues comming). ^^

**Comment by Drutol** [comment]
Now I'm going wrap things up with rev 133 (undo overhaul + invite fixes + misc stuff).And then move forward with pressent issues.

**Comment by Drutol** [comment]
Things are now sorting properly (hopefully) in rev 133. The rest is scheduled for rev 134.

**Comment by Drutol** [comment]
Added/Changed in rev 134. Changes for member module need to be tested first so they will come as soon as I manage to do so.
