### ISSUE TITLE
Bug / Request : r132 : Lootmaster window assign and bidding bar

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#54]
the bars are to close imho. while im still over the assign bar with the mouse, and that bar is still highlighted, often it starts the network bidding.
maybe 2 square buttons instead of the 2 parallel lines ?

**Comment by Drutol** [comment]
I remember trying to do so back in December without succes , maybe this time :) . Scheduled for rev 134

**Comment by Drutol** [comment]
Changed in rev 134.
