### ISSUE TITLE
Scaleable Windows

### ISSUE THREAD

**Issue by Aeotoc** [Mordonus/RaidOps#55]
So, is it possible to make all the windows scaleable? In particular I'm interested in the log windows being scaled up and down a bit.

**Comment by Drutol** [comment]
I'll se what I can do , scaling is sometimes a breeze and sometimes is tricky as hell :)

**Comment by Drutol** [comment]
Logs are now scaleable (rev 134) . Don't even think of me making the main window with roster scaleable xd.(too much hustle with customizable labels). Just write which windows you want to be able to resize (except the main one) beacuse "all" is little bit non precise. ^^
