### ISSUE TITLE
Request : r133 : Background Sync

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#56]
Main concern of the raidlead about using this addon is the worst case of data lost by dc while in raid and not been saved by /reloadui.

is there any way to choose one or more in raid as backup sync ? like send them every active or passive changes on the data ? so every time the EP or GP changes in anyway, they get the action send?

or maybe as alternative have them using a kind of backup addon like the member module but with a scheduled data pull request every x minutes ?

but the direct backup would be more accurate, cause a lot may happen between the data pulls :D

**Comment by Drutol** [comment]
WildStar only allows to save data on /reloadui. Sending db to other let's say assistants may lead to throttling.And even then they need to /reloadui in order to save.But when you get dc'ed addons save their data normally , don't they?

**Comment by Drutol** [comment]
If only I could sync data with outside world this would already be a thing.

**Comment by Hysteriana** [comment]
not sure about the addon save data in case of a dc, but there could also be other problems, like a BSoD or a blackout.

about the outside world sync.. well you can, sort of, the http://www.wildstarlogs.com addon does it, since it is able to make a live upload / update. it send the comback log live to the website while still ingame.

and im not suggesting a complete live database sync, only the updates like adding ep, gp, loot. 
the backup player will get a complete update once or if necessary by fetch data and then only the updates while in raid by push data from the lootmaster.

**Comment by Drutol** [comment]
I didn't know that w\* logs do this. Addon is called Wildstar logger?

**Comment by Hysteriana** [comment]
yes i think so:

http://www.wildstarlogs.com/de/reports/upload/

"The WildStar game does not support combat logging to an external file, so this means we have to do it ourselves. This is accomplished by using both the application and the add-on that you just downloaded. The add-on, when logging is enabled, will begin sending events to the system clipboard. The client uploader application can then be set to watch the clipboard and store the results in a WildStarCombatLog.txt file."

**Comment by Drutol** [comment]
Oh that may be a solution, creating such an app shouldn't be much of a problem but it'd be time consuming for sure and there's a lot of work to be done with the addon itself. So in the future that's an option.

**Comment by Drutol** [comment]
Or you can try the one from w\* logs , it may work.
