### ISSUE TITLE
Bug : r133 : While in Mass Edit Mode problem with damage dealer role fist icon

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#58]
While in mass edit mode, the fist symbol for damage dealers dims on mouser over and disappeared completely when a damage dealer is selected.

tanks and healer role icons are not effected.

**Comment by Drutol** [comment]
Odd , will investigate.

**Comment by Drutol** [comment]
I'm unable to replicate this , maybe it's a one-time odd bug.

**Comment by Hysteriana** [comment]
yeah i cant replicate it my self neither. odd, if it happens again i will open a new issue

**Comment by Hysteriana** [comment]
DA FUK ? now its the healer icons that fade and disappear ..
i recorded it: http://youtu.be/Gt8OOG1ywSo
happens only in mass edit mode

**Comment by Drutol** [comment]
Hmm , I'll check the control that is responsible for this.

**Comment by Drutol** [comment]
I have copy/pasted the control from single selection bars , maybe this will be a solution to this odd problem.
