### ISSUE TITLE
Sharing Channel does not appear to be working

### ISSUE THREAD

**Issue by xeroiv** [Mordonus/RaidOps#61]
Was unsuccessful in setting up data sharing between the EZ DKP module and the ROPS Member Module.  I had a guildee install the ROPSMM and try to fetch from the channel I entered and never recieved his request.  I have also tried a fetch from myself by name or channel name unsuccessfully.  Is there a how to that could be made on setup of this feature, or is it possible that the feature isnt working as intended at the moment.

**Comment by Drutol** [comment]
It was definitely working when I last checked. Could you see this player on channel(blue scanbot icon in Data Sharing window) ? You won't be able to fetch data from yourself having both addons installed , this is prevented by the API.

**Comment by xeroiv** [comment]
I was the one with the master database so I couldn't verify what he saw. I
will check with him tomorrow to see.

**Comment by Drutol** [comment]
That's not what I mean. You can verify who is on your channel by pressing this scanbot button , that way we can say that you both had set up the channel properly and you were "seeing" each other. It's case sensitive btw. I'll check this by myself today to make sure.

**Comment by Aeotoc** [comment]
The channel name is case sensitive, too. I found that out through trial and error. People using the RopsMM addon need to have the channel name typed EXACTLY as you do.

**Comment by Aeotoc** [comment]
Also, they can't fetch the data from the channel anme, only from your name. The channel name is there to facilitate network bidding.

**Comment by xeroiv** [comment]
That could have been the problem. I'll check later with some guildees to
see if I can get it working. Is this a topic that you're setup video could
cover?

**Comment by xeroiv** [comment]
I was able to get Sharing on the member module working.  It was a matter of the case sensitive channel.  Closing this issue...
