### ISSUE TITLE
Request : r134 : Auto Handle Window bigger and less transparent

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#63]
since you cant move that window, the color class icons are kinda annoying here.
and maybe a big bigger window to be able to see more than just 3 triggered events. 

![unbenannt](https://cloud.githubusercontent.com/assets/11199863/6544357/70d7c324-c54c-11e4-9465-329191a9ba1a.png)

**Comment by Aeotoc** [comment]
This, i think, could be fixed with moveable and scaleable windows for all functions inside the EPGP screen, if it's possible.

**Comment by Drutol** [comment]
Okay , I'm going to detach this thing and make this a separate window. The timed awards and customizable labels' windows are not that bad though ... Am I wrong?

**Comment by Drutol** [comment]
As of rev 135 Custom events window proclaims independence!

**Comment by Aeotoc** [comment]
LOL no, they're fine. I would kind of like to see some different sprites for the pop-out window buttons, but that's somethign that can be done way later.
