### ISSUE TITLE
Bug : r134 : Lua Error after killing Worldboss 

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#65]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:4571: attempt to index field 'unitTarget' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:4571: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:4561>

**Comment by Drutol** [comment]
This happened only on worldboss death?

**Comment by Hysteriana** [comment]
dont know, was the first raid-ish with the rev 134 and we killed a worldboss for key attunement
right at the kill that lua error popped up.
next regular raid in will be tuesday in GA

**Comment by Drutol** [comment]
Maybe it couldn't fetch the killed unit data , this happens occasionaly. I'll add a check there for such an exception.

**Comment by Drutol** [comment]
Fixed rev 135.
