### ISSUE TITLE
Bug : r134 : Lua Error at Database import

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#66]
...aming\NCSOFT\WildStar\Addons\EasyDKP\libs/Base64.lua:9: attempt to perform arithmetic on local 'value' (a nil value)
stack trace:
    ...aming\NCSOFT\WildStar\Addons\EasyDKP\libs/Base64.lua:9: in function 'lsh'
    ...aming\NCSOFT\WildStar\Addons\EasyDKP\libs/Base64.lua:54: in function 'Decode'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3298: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3243>

happens when you save the export to a web page or so and try to import that copy.
maybe you need to filter out the EoL (line breaks) somehow to prevent that error.

**Comment by Drutol** [comment]
Possible fix in rev 135.
