### ISSUE TITLE
Bug : r134 : Lag at Bosskill with Lua Error

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#68]
Lua event handler has exceeded 2501 ms.
stack trace:
    ...aming\NCSOFT\WildStar\Addons\EasyDKP\libs/Base64.lua:37: in function 'Encode'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:372: in function 'UndoAddActivity'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:4424: in function 'CETriggerEvent'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:4597: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:4561>

**Comment by Hysteriana** [comment]
nope happened again without notnowlootmaster. (see #72)

happened 3 times now with both guardians minibosses and phagemaw,
auto handler didnt give xp for them too. maybe the auto handle is buggy with them ?

**Comment by Drutol** [comment]
I'll try to adress all of those new issues today , I've been busy lately and wanted to take a little bit of break from this ^^. Holiday ended. I found the source of this bug and it'll be fixed today for sure.

**Comment by Hysteriana** [comment]
hey dont sweat it :) reallife comes first, always :)
just doing my job bugging you with bugs :D

**Comment by Drutol** [comment]
Fixed rev 135.
