### ISSUE TITLE
Bug : Prototype Kille was not recognized by the auto ep handler

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#7]
we killed prototypes, but somehow it was assumed as wipe so no ep was assigned

**Comment by Aeotoc** [comment]
In the case of prototypes, you could make a short work around to check if "Phagetech Commander" has been killed since they all have a shared health pool.

**Comment by Drutol** [comment]
They don't die one by one?...

**Comment by Aeotoc** [comment]
Missed this reply. So, no, with prototypes, they have a shared health pool, so once one dies they all die.

**Comment by Drutol** [comment]
Oh so in this case I can just check for any phagetech unit death and we are golden.

**Comment by Drutol** [comment]
Possible fix in rev 133.
