### ISSUE TITLE
Bug : r134 : Lootmaster - Show applicable classes

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#70]
doesnt work, activated or deactivated doesnt make any differences
ans sometimes its just odd like here: why is this weapon attachment for esper and spellslinger only ?

![unbenannt](https://cloud.githubusercontent.com/assets/11199863/6586971/cc7db77c-c77e-11e4-8f87-3d5a4db818b9.png)

**Comment by Drutol** [comment]
Are going to be online today , we will need to test this and everything else?

**Comment by Hysteriana** [comment]
send me a pm via curse when you go ingame. if i catch the mail in time i will come ingame to assist you.

**Comment by Drutol** [comment]
Fixed rev 135.
