### ISSUE TITLE
Request : r134 : Lootmaster - Guildbank

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#71]
it is possible to aways show guildbank at first entry at top ? disregardless or sort ?
also sometimes the guldbank doesnt show at all, like if the guildbank is a engineer and the item is light or medium or so, the guildbank entry is missing.

**Comment by Drutol** [comment]
Oh , okay gonna fix this quite easily I suppose.

**Comment by Drutol** [comment]
Fixed rev 135.
