### ISSUE TITLE
Conflict - r134 : NotNowLootMaster addon

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#72]
with the notnowlootmaster addon, the easydkp lootmaster window pops up everytime i log in or did a relaoadui. even if there is no loot to assign or if i am solo without raid.

without the easydkp lootmaster window pops up every time some loot drops, which is quite annoying.
also bot addons together cause some lag, maybe even the reason for: https://github.com/Mordonus/RaidOps/issues/68

would be nice if the easydkp lootmaster only opens on request

**Comment by Drutol** [comment]
Hmm , that's because I'm calling for refresh on startup , gonna make a checkbox for this .

**Comment by Hysteriana** [comment]
hmm then the popup at login/reload is intended ? than the notnowlootmaster addon is preventing that first popup somehow
