### ISSUE TITLE
Bug : r134 : Chatbid

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#73]
tried the chatbid with some epic element stuff, the start stop button were gray, couldn't start any chat auction

**Comment by Drutol** [comment]
I presume that you have set all 3 values (BidMin etc.) ?. I know that it shouldn't be the case for EPGP and I need to give some love to chat bidding ;d.

**Comment by Hysteriana** [comment]
you presumed wrong... :D oc i didnt enter any values ... :( ^^
will give it a new try tonight

**Comment by Drutol** [comment]
Will be given some love in rev 136 ;d
