### ISSUE TITLE
Bug : r134 : Recent Activity Log

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#74]
the log entries are odd.
as far as i can tell, everyone got the 600 ep once and every new entry got one more name
it stopped with 15 but none of them actually got this 600 ep in their personal logs, i had to mass add them 
maybe this could be a reason for the lags and timeout for #68 ?
see pictures:

![3](https://cloud.githubusercontent.com/assets/11199863/6589808/d26e192e-c7a6-11e4-913b-4cd941bb4e9b.png)
![1](https://cloud.githubusercontent.com/assets/11199863/6589806/d26d1682-c7a6-11e4-8c31-4ae3aea0ead6.png)
![2](https://cloud.githubusercontent.com/assets/11199863/6589807/d26d4ff8-c7a6-11e4-8473-1a56a5362f23.png)

**Comment by Drutol** [comment]
Yup this is because of that and my ultra "typomaker" skills -.- .

**Comment by Drutol** [comment]
Fixed rev in 135.
