### ISSUE TITLE
Bug : r134 : Personal Log sorting

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#75]
if i click the tabs to sort it asc or dsc it gets all messed up
type is the only tab that works

![time](https://cloud.githubusercontent.com/assets/11199863/6589885/38e02c96-c7a8-11e4-84f6-8b839e1bf5ad.png)

![comment](https://cloud.githubusercontent.com/assets/11199863/6589887/3d760d2a-c7a8-11e4-911d-c3cc9cc31f36.png)

![value](https://cloud.githubusercontent.com/assets/11199863/6589889/416ced40-c7a8-11e4-9500-15ada56ce940.png)

**Comment by Drutol** [comment]
Hmm , this sorting is handled by default "Grid" control , I'm not sure where I have messed up.
