### ISSUE TITLE
Request : r135a : Auto Fetch every x min. while out of combat and in raid

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#77]
would be nice, if the Fetch Option could get a timer option.
like fetch data all x minutes. x should be a imput field. 
and the auto fetch need a check if in raid with the guy you like to fetch from. 
also need a check to make sure it will only fetch if the fetcher is not in combat.

imho this would be much better and more flexible auto sync option.

**Comment by Drutol** [comment]
Can be done!

**Comment by Hysteriana** [comment]
then do it do it do it :D

**Comment by Drutol** [comment]
Weekend! Now I can do it :D

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/6640885/90db808c-c99a-11e4-9b4f-0aae9f95a0b6.png)
How about this?

**Comment by Hysteriana** [comment]
woot woot looks very nice.

**Comment by Drutol** [comment]
Already coded in waiting for testing.

**Comment by Hysteriana** [comment]
ok let me test :) bugs will find me anyway :D

**Comment by Drutol** [comment]
Added rev 136
