### ISSUE TITLE
Time left : 3 weeks.

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#78]
With my credds being gone , the addon development will have to be suspended. Create issues so we can finally get rid of this beta mark , not much time left!

**Comment by Hysteriana** [comment]
play more and earn platin :)

**Comment by Drutol** [comment]
Back in the day , ppl were collecting ore from my 3 housing plugs... then I used this galactium to craft Lopp Hookahs(idk the spelling) , and I were golden. But now? How can I earn munies?

**Comment by Aeotoc** [comment]
shiphands

**Comment by Hysteriana** [comment]
i would like to support the addon development with platin donation for your credd.
lets say 5 platin for start. maybe some other will chip in to support your nice work and fast respond time.
just let me know to which char you would like me to send the platin to.

**Comment by Drutol** [comment]
That's very generous of you. Maybe with those shiphands and donations I'll make it to 23 plat ;d. If you want to send plat send it to Drutol Windchaser@Jabbit.

**Comment by Hysteriana** [comment]
10p sent.

**Comment by Drutol** [comment]
Thanks!

**Comment by Eikju** [comment]
some of our German guild called "VII" will support you with plat. So you can focus more on the addon. Sounds good? :D

**Comment by Drutol** [comment]
Wow , I wasn't expecting this , thanks a lot! :D

**Comment by Aeotoc** [comment]
You're EU so I can't donate plat =/ but I do want to support you. Also, Drop 5 updates the API, so you may have to make a lot of changes, just an FYI.

**Comment by xeroiv** [comment]
You can't send plat from US to EU? lame...

**Comment by Aeotoc** [comment]
wait can we? I just assumed we couldn't.

**Comment by xeroiv** [comment]
I don't know, I was just basing my knowledge off of yours.  So apparently we are the blind leading the blind here.

**Comment by Hysteriana** [comment]
Check out if free realm transfer includes US to Europe. This could be a way

**Comment by Aeotoc** [comment]
Entity to Warhound =/

**Comment by Drutol** [comment]
Thanks for the heads-up with API , anything cross region is impossible sadly. But hey , I received 16 plat that I know of right now and managed to buy CREDD yesterday so we are in good shape :+1: . Big **thank you** for your support. :D

**Comment by Aeotoc** [comment]
Put up a patreon and I'll donate a couple bucks toward's next month's credd.

**Comment by Drutol** [comment]
I don't see me buying sub with real money any time soon , but if you insist you can donate something to this e-mail : dogier140@poczta.fm via paypal. Setting up patreon is pretty much pointless in my opinion , unless there's something that I don't have the knowledge of.

**Comment by Aeotoc** [comment]
patreon was just the first word that came to mind. idk, I can't gift you credd or plat because location-lock.

**Comment by Drutol** [comment]
Sooo , having a sub for next month I guess I'm going to close this thing. Then again , thanks for help big time !
