### ISSUE TITLE
Bug / Request : r136 : German Language Support

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#79]
Some stuff doesnt work with german client.
1. LootMaster doesnt show Raidmember until you deleted the "search" top left and it will get replaced by "suchen" (edit: my bad, it was the other way around actually)
2. EPGP PopUp, after loot assign, doesnt show up with german client.

**Comment by Drutol** [comment]
Can you give me exact string that appears in chat window ? "The loot master...blah...blah" in German.

**Comment by Drutol** [comment]
I don't get the 1st issue though , can you elaborate or give me ss?

**Comment by Hysteriana** [comment]
1.) no member as long as that field contains "suchen"
manual delete that entry, and it will auto replaced with "search" and the member will show up

![old](https://cloud.githubusercontent.com/assets/11199863/6662110/9f1b112a-cbb7-11e4-95b6-a2730a3ba312.png)
![new](https://cloud.githubusercontent.com/assets/11199863/6662111/a3c4ff10-cbb7-11e4-8d3a-9d93c7867678.png)

2.) (be aware of the umlauts :D )

![loot](https://cloud.githubusercontent.com/assets/11199863/6662114/ab9b28ea-cbb7-11e4-960f-3ab7430d2cf9.png)

**Comment by Drutol** [comment]
1 ) Do you want to tell me that it automatically changes search to suchen?

**Comment by Hysteriana** [comment]
yes. but the other way around.. at first open of lootmaster window, that field´s value is "suchen" and no member show up.
when i click into that field and delete the "suchen" it will be auto replaced with search (even im running german client) and the raidmember show up instantly

**Comment by Drutol** [comment]
Okay , I'm now starting to write localization settings . Gradually we will translate the whole thing :)

Oh boy , so much strings...

**Comment by Drutol** [comment]
Fixed in rev 137.
