### ISSUE TITLE
Lootmaster Window PopUp - Request

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#8]
Is it possible to disable the auto popup of the lootmaster window ?
especially while infight

**Comment by Drutol** [comment]
![image](https://cloud.githubusercontent.com/assets/6102530/6386857/f3336fea-bd80-11e4-8b41-e7c567dbc2a8.png)

**Comment by Hysteriana** [comment]
doest work. that option only stop the little assign ep gp window from popping up when loot has been assigned.. but not that fat masterloot window where all the loot is shown and that pops up everytime some epic drops
