### ISSUE TITLE
Translation!

### ISSUE THREAD

**Issue by Drutol** [Mordonus/RaidOps#80]
With revision 137 locale files will appear , there's a TON of text to translate but we are starting small and now I have localised only main window +/-. With every update I'll add more windows and strings ,the foundation is here more or less. If you translate stuff post it here or clone the repo and request merge.

Try to avoid spacing problems , if impossible leave a comment with key (text of what) and the value (translation) and I'll fix this.

If you are French please give me the string that shows up in chat window on loot channel : "The masterlooter assigned ...blah ...blah" in French with maybe explanation because I have never encoutered this language before ^^.

**Comment by Hysteriana** [comment]
what about umlauts ? should we avoid them ?

**Comment by Drutol** [comment]
No , umlauts are ok in this case. Everything translates ok? Any spacing problems?

**Comment by Eikju** [comment]
Is there any chance that you use "locals"? That would be easyer because with locals you just must assign one argument and you have a seperated file with all the text from German, English and France.

Just an idea :)

**Comment by Hysteriana** [comment]
"With revision 137 locale files will appear "

he already did that eikju and german translation is already in progress, feel free to chip in :)

https://github.com/Mordonus/RaidOps/tree/master/EasyDKP/locale
