### ISSUE TITLE
Members unable to view epgp history

### ISSUE THREAD

**Issue by xeroiv** [Mordonus/RaidOps#82]
I just had a guildee check the ROPSMM to see if they could see their personal log or anyone elses once they fetched the data. The View Logs button just produced an empty window was what I was informed. The latest ROPSMM was used from what I was told.

I have log sharing enabled in the master module, I also tried with many other combinations of data sharing options turned on/off.

Another test I ran was to have a guildee import my epgp backup string. It pulled into his Ui with the correct names and numbers. However none of the revision logs came with it.

**Comment by Drutol** [comment]
Can your guildee fetch standings? 

The logs won't be exported because they are just too big and it leads to lua errors , all I can do is to export them independently  and hope that they are small enough.

**Comment by xeroiv** [comment]
They can fetch the standings just fine. So was the view logs button on the
member module originally supposed to do that but you found it to not work
as planned?

**Comment by Drutol** [comment]
It was working when I last checked , I will investigate.

**Comment by Drutol** [comment]
Fixed in rev 139.
