### ISSUE TITLE
Addon won't work with German client

### ISSUE THREAD

**Issue by Eikju** [Mordonus/RaidOps#83]
Heyho!

As I mentioned in the title, the addon won't work with the German client. I use the addon in the version v2.0 rev 137.

The following error occurred:

...aming\NCSOFT\WildStar\Addons\EasyDKP\locale/enUS.lua:4: attempt to index local 'L' (a nil value)
stack trace:
...aming\NCSOFT\WildStar\Addons\EasyDKP\locale/enUS.lua:4: in main chunk

**Comment by Drutol** [comment]
Hmm , try swapping the first two lines of enUS.lua with this:

```
local L = Apollo.GetPackage("Gemini:Locale-1.0").tPackage:NewLocale("EasyDKP", "enUS",true)
if not L then return end
```

**Comment by Eikju** [comment]
Seems that it works for me. Thank you :)

**Comment by Drutol** [comment]
Uff , good to hear. I'll put an update on curse asap , what is the main window title now?

**Comment by Eikju** [comment]
the title of the main window is "RaidOps - DKP/EPGP Management (in German :D)"

I also see that you have a German language file. If you want, I can do the whole translation work for you.

**Comment by Drutol** [comment]
Right now Hysteriana has translated the 1st part , it is on github and will be on curse in a few minutes 
(there's always going to be a slight delay). The 2nd part is waiting to be translated though , so clone the file , translate and request merge :).

New strings to translate begin here : https://github.com/Mordonus/RaidOps/blob/master/EasyDKP/locale/enUS.lua#L85
This is the file you want to paste your translation in :
https://github.com/Mordonus/RaidOps/blob/master/EasyDKP/locale/deDE.lua#L98

**Comment by Hysteriana** [comment]
Eiku just mentioned, he got a error with the latest r138 and his german client

**Comment by Drutol** [comment]
The same one?

**Comment by Eikju** [comment]
This is the error:

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:2991: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:2991: in function 'SettingsRestore'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:419: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:193>

**Comment by Drutol** [comment]
Fixed rev 138a
