### ISSUE TITLE
Bug : r138 : Lua Error after /reloadui

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#85]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:2991: attempt to index a nil value
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:2991: in function 'SettingsRestore'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:419: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:193>

**Comment by Drutol** [comment]
Fixed rev 138a
