### ISSUE TITLE
Masterloot LUA Error - Version 129ish - Bug

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#9]
when i try to assign some loot

...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2794: attempt to get length of field 'tSelectedItems' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2794: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:2784>
    (tail call): ?

**Comment by Drutol** [comment]
Fixed in rev 129ish a
