### ISSUE TITLE
Bug : r139 : Lua Error when setting guild channel in data sharing

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#90]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:1830: attempt to index field 'wndBid2Settings' (a nil value)
stack trace:
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:1830: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\BID.lua:1828>

**Comment by Drutol** [comment]
Fixed rev 140.
