### ISSUE TITLE
Bug : r139 : Critical : Changes are not saved after /reloadui

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#91]
i made a decay and then /reloadui to save it. but after the /reloadui i got the old values.
same with settings.. i change something, do /reloadui, reopen settings and get the old config.

**Comment by Hysteriana** [comment]
i nailed it down a bit... 
when i purge the database, settings and epgp changes are saved again with /reloadui
but when i import my actual database, changes are ignored.

actual database: http://pastebin.com/2NsaTTUM

**Comment by Drutol** [comment]
Fixed rev 139a
