### ISSUE TITLE
Request : r139 : Chatbidding

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#92]
1. Send notification messages by whisper to avoid channel spam
2. option to change bidding, like from !bid to !off
3. option to pass on bidding like from !bid or !off to !pass
4. option to assign stuff from the chat bidding window
5. to be continue

**Comment by Drutol** [comment]
Tbh I'm halfway through rewriting this , I was just busy throughout the weekend and didn't manage to finish.

**Comment by Hysteriana** [comment]
yeah dont sweat it.. was just a memo since there was no open issue about it anymore.

**Comment by Drutol** [comment]
Right now I'll skip the 2nd point , the rest is already implemented.
