### ISSUE TITLE
Bug : r139 : Weapons are only shown for equipable class.

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#95]
cant random assign weapons to whole raid, cause only the class who is able to use them is shown in the list.

**Comment by Drutol** [comment]
Even with having class filtering off?

**Comment by Hysteriana** [comment]
yes, also sometimes that filter doesnt seem to have any effect at all.
i will write done every item that behaves oddly.

**Comment by Drutol** [comment]
As it turns out it's something on the carbine's side...
