### ISSUE TITLE
Bug : r139 : Lua error by random assign

### ISSUE THREAD

**Issue by Hysteriana** [Mordonus/RaidOps#97]
...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3716: bad argument #1 to 'SetText' (string expected, got nil)
stack trace:
    [C]: in function 'SetText'
    ...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3716: in function <...pData\Roaming\NCSOFT\WildStar\Addons\EasyDKP\DKP.lua:3694>

**Comment by Drutol** [comment]
Fixed rev 140.
